### ISSUE TITLE
inference in GGUF models is extremely slow

### ISSUE THREAD

**Issue by Datron** [huggingface/candle#1008]
Hi I really like candle and am using it for one of my projects right now. My machine specs are:
```
16 inch Macbook Pro
CPU: 2.6 GHz 6-Core Intel Core i7
GPU: Intel UHD Graphics 630 1536 MB
Memory: 16 GB 2667 MHz DDR4
```
I am running llama2 with tiny-llama-fast-tokenizer. When I run it with the quantized example in candle-examples, it works fine. I get about 5 tokens/s. When I run the same model with my code, I maybe get 1 token/minute. After investigating I'm seeing an issue where my code halts at `model.forward`. When I copy pasted my code into one of the examples (the exact path is candle-examples/examples/quantized/main.rs), it ran fine.

I'm pretty sure I've setup the repo wrong, I have replicated the cargo.toml from the example code but still the problem persists. What could be wrong? Any help is appreciated

[Repository](https://github.com/Datron/jusdoc)
model:  [llama-2-7b-chat.Q4_K_M.gguf](https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/resolve/main/llama-2-7b-chat.Q4_K_M.gguf)
tokenizer: [tiny-llama-fast-tokenizer](https://huggingface.co/fxmarty/tiny-llama-fast-tokenizer)

**Comment by LaurentMazare** [comment]
You may also want to replicate the [.cargo/config.toml file](https://github.com/huggingface/candle/blob/main/.cargo/config.toml) or compile with the `-C target-cpu=native` compile flags. This should ensure that the simd instructions of your cpu are properly leveraged.

**Comment by Datron** [comment]
Hi @LaurentMazare , thanks for the reply. I added the config.toml file, but I still see that the inference speed is very slow - about 1 token every 2 - 3 minutes. Anything else that I could've missed?

**Comment by LaurentMazare** [comment]
Oh that's sad. Could you update your repo with this and I'll see if I can reproduce the issue.

**Comment by LaurentMazare** [comment]
(also obviously you should compile in `release` mode to enable optimization but I guess you already double checked this bit)

**Comment by Datron** [comment]
> (also obviously you should compile in release mode to enable optimization but I guess you already double checked this bit)

I missed this. Retried with  the `--release` flag and I am getting the same performance that I get with the candle repo. Thanks a ton @LaurentMazare!

**Comment by LaurentMazare** [comment]
Closing as solved, feel free to re-open if needed!
