### ISSUE TITLE
Target wasm32-unknown-unkown not supported

### ISSUE THREAD

**Issue by clarkmcc** [huggingface/candle#1032]
I've trained a tensorflow model that I'm porting to candle so that I can run inference at the edge. Am I doing something wrong? I've seen other tickets elude to wasm32 support, but I can't seem to get this to build.

My cargo.toml file looks like this

```toml
[dependencies]
candle-nn = "0.3.0"
candle-core = "0.3.0"
```

But I get this error when building
```shell
➜  candle-tensorflow-experiment git:(master) ✗ cargo build --target wasm32-unknown-unknown
    Blocking waiting for file lock on build directory
   Compiling memoffset v0.9.0
   Compiling crossbeam-epoch v0.9.15
   Compiling num-traits v0.2.16
   Compiling proc-macro2 v1.0.67
   Compiling crossbeam-utils v0.8.16
   Compiling libm v0.2.7
   Compiling rayon-core v1.12.0
   Compiling paste v1.0.14
   Compiling getrandom v0.2.10
   Compiling lazy_static v1.4.0
error: the wasm*-unknown-unknown targets are not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
   --> /Users/clark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.10/src/lib.rs:285:9
    |
285 | /         compile_error!("the wasm*-unknown-unknown targets are not supported by \
286 | |                         default, you may need to enable the \"js\" feature. \
287 | |                         For more information see: \
288 | |                         https://docs.rs/getrandom/#webassembly-support");
    | |________________________________________________________________________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> /Users/clark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/getrandom-0.2.10/src/lib.rs:341:9
    |
341 |         imp::getrandom_inner(dest)?;
    |         ^^^ use of undeclared crate or module `imp`

   Compiling ppv-lite86 v0.2.17
For more information about this error, try `rustc --explain E0433`.
error: could not compile `getrandom` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

```

**Comment by radames** [comment]
hi @clarkmcc it doesn't look it's a Candle issue, the error above points to https://docs.rs/getrandom/latest/getrandom/#webassembly-support and recommends this setup
```toml
[dependencies]
getrandom = { version = "0.2", features = ["js"] }
```

**Comment by clarkmcc** [comment]
Is `getrandom` not a dependency of Candle? Maybe I'm confused but my cargo toml only has candle, so I assumed it was a downstream issue of candle.

**Comment by LaurentMazare** [comment]
`getrandom` is indeed a dependency of the main candle crate but the `Cargo.toml` of this crate has no way of knowing that the final build is for `wasm32` so you will have to override it in your crate as @radames suggested, hopefully it's not too much of an inconvenience (and I think there are a bunch of other crates that require the exact same `getrandom` override).

**Comment by clarkmcc** [comment]
Yeah that's totally fine with me, although usually what I see in other creates is a feature like js, or wasm or something which automatically enables these other downstream features like js for the getrandom crate. Something like that would be nice in the future.

On a related note, I got passed this error but I'm getting new compile errors. Is candle _supposed_ to be wasm compatible? I'm getting the following when compiling for wasm32-unknown-unknown, and I'm not sure if I'll be able to work around this one.

```
The following warnings were emitted during compilation:

warning: In file included from oniguruma/src/regexec.c:36:
warning: oniguruma/src/regint.h:110:10: fatal error: 'stdlib.h' file not found
warning: #include <stdlib.h>
warning:          ^~~~~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `onig_sys v69.8.1`
```

**Comment by Narsil** [comment]
This looks like `tokenizers` compilation.

For wasm targets you need to disable the feature `onig` and use `fancy-regex` instead (it's unstable as it's a different regex engine therefore we can never be really fully sure they are 100% compat, but it should work for the most part)

The candle wasm examples should already do that I think

**Comment by clarkmcc** [comment]
Thanks for the help! Add these to my Cargo.toml got everything working.

```toml
[dependencies]
tokenizers = { version = "0.14.0", default-features = false, features = ["unstable_wasm"] }
getrandom = { version = "0.2", features = ["js"] }
```
