### ISSUE TITLE
How to fine-tune large models?

### ISSUE THREAD

**Issue by nullptr2nullptr** [huggingface/candle#1036]
Hello all,

How should I finetune a large model? Are there implementations like `peft` in Python for Candle? Specifically, how should I train a quantized, LoRA model? I saw [candle-lora](https://github.com/EricLBuehler/candle-lora), and plan to use that but do not know how to quantize a large model.

**Comment by okpatil4u** [comment]
An example with a pipeline such as this could be extremely useful.

**Comment by LaurentMazare** [comment]
Might be worth making an issue in the candle-lora repo for this?

**Comment by nullptr2nullptr** [comment]
Sure!

**Comment by jnnnnn** [comment]
https://github.com/EricLBuehler/candle-lora/issues/17

**Comment by super-fun-surf** [comment]
is there anyway with candle to make finetune of say mistral? instead of a lora?
