### ISSUE TITLE
Cuda backend uses a fixed seed

### ISSUE THREAD

**Issue by mneilly** [huggingface/candle#1055]
Running the stable diffusion demo with the same prompt always results in the same image. [Latent initialization calls Tensor::randn()](https://github.com/huggingface/candle/blob/2e5fb0b2518aa7f7c666967fe4160462578cf8d0/candle-examples/examples/stable-diffusion/main.rs#L440) but printing the latents reveals that they are always the same for the same prompt. 

It appears that a fixed seed is used to seed the random number generator when the [Cuda backend is created in cuda_backend.rs](https://github.com/huggingface/candle/blob/2e5fb0b2518aa7f7c666967fe4160462578cf8d0/candle-core/src/cuda_backend.rs#L217).

It  would be useful to seed the RNG based on a user provided seed or randomly by default so that images could be either regenerated or newly generated as determined by the user.

**Comment by LaurentMazare** [comment]
Right, I've just merged some changes that should add a `set_seed` method to the cuda device. For now it's not implemented on the cpu side as this need a bit more thinking but that should help at least for your use cases.

**Comment by mneilly** [comment]
Great. I'll check it out later today.

**Comment by mneilly** [comment]
Thanks. The randomness is there now such that the same prompt can generate different images. 

However, results are not reproducible with the same prompt and same seed without creating a new device or rerunning the demo. I guess this is related to how curand works. Can curandSetGeneratorOffset() be exposed through the device as set_rng_offset() or something? Then, the user code can control the reproducibility.

I.e. - I want the option for prompt "a red dragon" with seed 42 to produce the same image every time.

**Comment by LaurentMazare** [comment]
Ah thanks for pointing this out. It's indeed a bit unintuitive that the state of the rng is not just defined by the seed and requires other parameters to be set. The `cudarc` crate does not expose these generator offset in a safe way at the moment (they're only exposed in the sys/unsafe part) so what I've just done is that `set_seed` now re-creates the cudarng object, and this should ensure that the same values are properly generated from this point. There is likely some performance impact of doing so but I feel that re-seeding the rng is rarely done in a hot loop.

**Comment by mneilly** [comment]
Great thanks! I'll try it out. That should suffice for my case. I wouldn't expect the performance change to have any real impact. It'll take longer for the user to type a seed and click a button and much longer to generate the image. :) FWIW - I did file a pull request yesterday with cudarc to expose a set_offset().

**Comment by mneilly** [comment]
Ok. I'm using 59ab6d7832600083a1519aa0511e9c7c832ae01c. If I reseed with the same seed I do not get the same image so it seems that either I don't have the change or it isn't working.
