### ISSUE TITLE
Cuda FP16 SDXL returns black image

### ISSUE THREAD

**Issue by mneilly** [huggingface/candle#1060]
The following command running on GPU and using 16b float returns a black  image:

`run --release --features cuda,cudnn,flash-attn,mkl -- --use-f16 --use-flash-attn`

If I use a different set of VAE weights from [madebyollin/sdxl-vae-fp16-fix](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix) I get images returned.

`run --release --features cuda,cudnn,flash-attn,mkl -- --use-f16 --vae-weights diffusion_pytorch_model.safetensors --use-flash-attn`

**Comment by LaurentMazare** [comment]
Thanks for reporting this and providing the fix, #1064 tweaks the default to use the weights you mentioned.

**Comment by LaurentMazare** [comment]
Closing this as it should hopefully be all good know, feel free to re-open or create a new issue if you have more thoughts.
