### ISSUE TITLE
Don't quite understand code in npy.rs

### ISSUE THREAD

**Issue by szguoxz** [huggingface/candle#1077]
There's a function in candle-core/src/npy.rs, from line 246: and I don't understand the last 3 lines. We read the file to data vec, and don't do anything with it? And we call from reader, but the reader is already reached the end. What do I miss here?

    pub fn read_npy<T: AsRef<Path>>(path: T) -> Result<Self> {
        let mut reader = File::open(path.as_ref())?;
        let header = read_header(&mut reader)?;
        let header = Header::parse(&header)?;
        if header.fortran_order {
            return Err(Error::Npy("fortran order not supported".to_string()));
        }
        let mut data: Vec<u8> = vec![];
        reader.read_to_end(&mut data)?;
        Self::from_reader(header.shape(), header.descr, &mut reader)
    }

**Comment by LaurentMazare** [comment]
Oh nice catch, I think this might be a bug that was introduced through some debugging. `read_npy` is probably never used as `read_npz` is much more convenient. If you have the cycles to write a small test, check that it fails, and remove the two weird lines then check that it works, that would be great! Otherwise no worries I'll take a stab at it later today or tomorrow.

**Comment by szguoxz** [comment]
To be honest, I am new to the AI stuff, and not even sure what npy means. :-) That's the reason I start leaning by reading the source code. Probably nobody found it before because nobody actually read the source code unless they hit a wall. :-)
Never used python, so I think I can't help this for the moment. Just trying get my head around what is a model, and what is a tensor, and how exactly they work for now.:-)

**Comment by LaurentMazare** [comment]
Just created #1080 that adds a test for reading npy and npz files. Reading npy files indeed fails and passed after removing the lines you noticed, thanks again for reporting 🙏
