### ISSUE TITLE
Documentation to compile a model to WASM?

### ISSUE THREAD

**Issue by filopedraz** [huggingface/candle#1079]
### Description

I see that there are examples of models running in the browser, but I don't see any documentation on how to compile a Candle model to WASM.

**Comment by LaurentMazare** [comment]
Did you look at the examples readme files? Most of them have ones, e.g. https://github.com/huggingface/candle/tree/main/candle-wasm-examples/whisper
(I would recommend using the non-pure rust UI as they usually look a lot better than the pure rust ones)

**Comment by LaurentMazare** [comment]
Closing as hopefully you know have all the details needed now, feel free to re-open or create a new issue if it's not the case.
