### ISSUE TITLE
How to run a model in Fp16?

### ISSUE THREAD

**Issue by joeyballentine** [huggingface/candle#1105]
EDIT: Never mind, see below comment

**Comment by joeyballentine** [comment]
Ah of course I figured it out so soon after I made an issue... So I started off correctly by loading the weights as F16 as well converting the image to a F16 tensor, but it seems there's an issue where `.to_dtype(DType::U8)` is not supported for fp16 tensors, meaning to convert it back to an image i need to go to a fp32 tensor then to a u8 tensor. That seems like a good reason to keep this issue open, but let me know if I'm just doing something wrong.

**Comment by LaurentMazare** [comment]
Could you provide the actual error message that you get as well as ideally a standalone minimal repro? That would be super helpful to track the issue down.

**Comment by joeyballentine** [comment]
Yep, will do as soon as I can 👍

**Comment by joeyballentine** [comment]
The actual error is this: ```called `Result::unwrap()` on an `Err` value: Cuda(Load { cuda: DriverError(CUDA_ERROR_NOT_FOUND, "named symbol not found"), module_name: "cast_f16_u8" })```

Example code (apologies if this is horrible rust code, i'm still a bit new to the language)
```rust
fn main() {
    let device = Device::new_cuda(0).unwrap();

    let model_path = "4xBox.safetensors";

    let vb =
        unsafe { VarBuilder::from_mmaped_safetensors(&[model_path], DType::F16, &device).unwrap() };

    let model = ESRGAN::load(vb, 3, 3, 4, 64, 23, 32).unwrap();

    let img = image::open("example.png").unwrap();
    let height: usize = img.height() as usize;
    let width: usize = img.width() as usize;
    let data = img.to_rgb8().into_raw();
    let tensor = Tensor::from_vec(data, (height, width, 3), &device)
        .unwrap()
        .permute((2, 0, 1))
        .unwrap();
    let image_t =
        (tensor.unsqueeze(0).unwrap().to_dtype(DType::F16).unwrap() * (1. / 255.)).unwrap();

    let mut result = model.forward(&image_t).unwrap().squeeze(0).unwrap();
    result = (result.clamp(0., 1.).unwrap() * 255.).unwrap();

    let result = result
        .permute((1, 2, 0))
        .unwrap()
        .to_dtype(DType::U8)
        .unwrap()
        .detach()
        .unwrap();

    let data = result.to_vec3::<u8>().unwrap();
    let out_img = vec_to_image(data);

    out_img.save("out_sr.png").unwrap();
}
```

The issue here is the `.to_dtype(DType::U8)`

**Comment by joeyballentine** [comment]
Aha! And of course, posting that error made me realize it was cuda related. If I change the result step to this:
```rust
    let result = result
        .permute((1, 2, 0))
        .unwrap()
        .detach()
        .unwrap()
        .to_device(&cpu)
        .unwrap()
        .to_dtype(DType::U8)
        .unwrap();
```

It works fine. Just had to move it to the cpu.

**Comment by LaurentMazare** [comment]
Thanks for the repro, indeed it's cuda related. I've reworked this bit in #1112 and it should now work without having to go through the cpu. Let me know if it's not the case.

**Comment by joeyballentine** [comment]
Awesome, I'll test that out later and get back to you.
