### ISSUE TITLE
Would it be possible to use Qwen  through candle ?

### ISSUE THREAD

**Issue by Fred2022HR** [huggingface/candle#1107]
Hi

This is a chinese model with pretty interesting characteristics : https://huggingface.co/Qwen/Qwen-14B-Chat

Would it be complex to use it through candle ?

**Comment by LaurentMazare** [comment]
PyTorch based transformers model are usually quite straightforward to port to candle. For this one, I came across [qwen.rs](https://github.com/yportne13/qwen.rs) though I have no clue whether it is in a workable state or not. Maybe you can give it a try or ask the author.

**Comment by Fred2022HR** [comment]
Thanks
I will give it a try

**Comment by Fred2022HR** [comment]
will do
