### ISSUE TITLE
Error: cannot find tensor image_encoder.patch_embed.proj.weight

### ISSUE THREAD

**Issue by spursy** [huggingface/candle#1118]
When I get image embedding, I get the followed error.

```
Error: cannot find tensor image_encoder.patch_embed.proj.weight
```

[This is my recurrent code on github](https://github.com/spursy/rust-candle-images)

**Comment by LaurentMazare** [comment]
This [line](https://github.com/spursy/rust-candle-images/blob/a37b68eead2f54438d6dd3b9c918e02fef6d8167/src/main.rs#L15) downloads the weights for the tiny-vit backbone, but on this [line](https://github.com/spursy/rust-candle-images/blob/a37b68eead2f54438d6dd3b9c918e02fef6d8167/src/main.rs#L25) you use the full backbone so when loading the weight you would indeed get some errors about not being able to find the tensors for some names.

**Comment by spursy** [comment]
@LaurentMazare Thanks, I fix my issue
