### ISSUE TITLE
how to modify the contents of a Tensor?

### ISSUE THREAD

**Issue by laptou** [huggingface/candle#1163]
what is the `candle` equivalent of this?

```python
t[2, :] *= 2;
```

**Comment by LaurentMazare** [comment]
This is actually not possible and on purpose, only variables are mutable, tensors by default are not. The goal is to favor a functional approach and avoid all sort of mutability. Do you have some specific use cases where this would be especially useful? (you may want to look at the yolo examples as the python implementation of these had some in place ops on slices that were converted to some `cat` etc operations).

**Comment by laptou** [comment]
Thanks for pointing me to the yolo examples. I looked through some of the other examples and couldn't really figure out how this was translated from Python.

**Comment by LaurentMazare** [comment]
Closing this as done but feel free to reopen or create a new issue if you have further questions.
