### ISSUE TITLE
How do I raise 2 to the power of a tensor?

### ISSUE THREAD

**Issue by laptou** [huggingface/candle#1165]
How do I write:

```python
x = 2 ** (y * z)
```

Where `y` is an integer and `z` is a tensor?
I tried to use `powf`, but it only works with float arguments.

**Comment by LaurentMazare** [comment]
Haven't tried but I think something like the following should work: `(z * (y as f64 * f64::log(2))?.exp()?`

**Comment by laptou** [comment]
ah I should've thought of that, thanks

**Comment by LaurentMazare** [comment]
Closing this as done but feel free to reopen or create a new issue if you have further questions.
