### ISSUE TITLE
Question: what is the add_special_tokens parameter of Tokenizer::encode?

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#1173]
As stated above, what does the parameter add_special_tokens do? Does it add bos/eos tokens? Thanks!

**Comment by LaurentMazare** [comment]
This actually comes from the [tokenizers crate](https://github.com/huggingface/tokenizers) so might be better to ask there directly as they would certainly know better.

**Comment by EricLBuehler** [comment]
Ah, right. Thanks!
