### ISSUE TITLE
Llama models quantized with tensor-tools don't have llama.attention.head_count in metadata

### ISSUE THREAD

**Issue by soupslurpr** [huggingface/candle#1182]
When trying to run models quantized from safetensor to gguf with tensor-tools, when trying to load a model, I get an error:

'Result::unwrap()' on an 'Err' value: Msg("cannot find llama.attention.head_count in metadata")

**Comment by LaurentMazare** [comment]
Right, when a model is built with tensor-tools it's to be used with a custom model rather than the `quantized` model that uses the metadata from the gguf file.
Not sure what your exact use case is, you can either hack tensor-tools or write your custom quantizer that injects the proper metadata file, or do this in python using candle-pyo3 (not sure if everything is exposed to do this but the goal is clearly to make it easy for such use case to be done with a couple lines of python).
Is your model supported by `llama.cpp` and so should work fine in candle's `quantized` example provided that the appropriate metadata were available?

**Comment by soupslurpr** [comment]
I think the model should be supported by llama.CPP as it is a model trained by the llama.c example, but I haven't tested myself. So yes I think it would work fine if the appropriate metadata were available.

**Comment by soupslurpr** [comment]
I see here a blank metadata is provided. So I could just make it and pass it here (this is in tensor-tools)

`    gguf_file::write(&mut out_file, &[], &qtensors)?;`

**Comment by LaurentMazare** [comment]
Yep that's exactly what I meant by making your custom quantizer, just hack it in there.

**Comment by soupslurpr** [comment]
Thanks for the tip, I tried ripping the metadata off of another gguf llama 2 architecture gguf (it works, I tested it. Its from TheBloke), but I get 

'Result::unwrap()' on an 'Err' value: Msg("cannot find tensor-infor for token_embd.weight")

**Comment by LaurentMazare** [comment]
I doubt there is. The error means that the model code is expecting to find a tensor named token_embd.weight but this doesn't exist in the gguf file. You can use the `ls` subcommand from the tensor-tools example to list all tensors in a file and maybe it's using some different naming convention there?

**Comment by soupslurpr** [comment]
Ohh, I think I see my mistake. I assumed the model trained by the llama.c example would be compatible with the quantized example but I was wrong, it seems to have an entirely different structure.

**Comment by soupslurpr** [comment]
Wait actually is it just a slightly different name

**Comment by soupslurpr** [comment]
Nope, it is a different structure, when copying quantized_llama.rs and changing it so that the llama.c example trained model loads, the shapes are mismatched.

`called `Result::unwrap()` on an `Err` value: ShapeMismatchBinaryOp { lhs: [36, 288], rhs: [1, 36, 2048], op: "reshape" }`

**Comment by LLukas22** [comment]
@soupslurpr The problem you are facing with the "ec_dot_q4_0_q8_0: 9 is not even" error is that the ggml quantizations only support tensor shapes that are devidable by 8, meaning one of your weights isn't divisable by 8. You could circument this by not quantizing tensors that are not dicvisible by 8, e.g. keeping them in f16 or f32.

**Comment by soupslurpr** [comment]
@LLukas22 Thanks for the advice! I'm very confident all of the numbers shown when I do tensor-tools ls on the model are divisible by 8. But the whole reason I used q4_0 and not something like q3k is because the q3k didn't quantize most of it for some reason. Anyways, using the q3k model made it successfully work! The ls for the q4_0 one is below if anyone is interested.

`lm_head.weight: [[32000, 288]; Q4_0]
model.embed_tokens.weight: [[32000, 288]; Q4_0]
model.layers.0.input_layernorm.weight: [[288]; F32]
model.layers.0.mlp.down_proj.weight: [[288, 768]; Q4_0]
model.layers.0.mlp.gate_proj.weight: [[768, 288]; Q4_0]
model.layers.0.mlp.up_proj.weight: [[768, 288]; Q4_0]
model.layers.0.post_attention_layernorm.weight: [[288]; F32]
model.layers.0.self_attn.k_proj.weight: [[288, 288]; Q4_0]
model.layers.0.self_attn.o_proj.weight: [[288, 288]; Q4_0]
model.layers.0.self_attn.q_proj.weight: [[288, 288]; Q4_0]
model.layers.0.self_attn.v_proj.weight: [[288, 288]; Q4_0]
model.layers.1.input_layernorm.weight: [[288]; F32]
model.layers.1.mlp.down_proj.weight: [[288, 768]; Q4_0]
model.layers.1.mlp.gate_proj.weight: [[768, 288]; Q4_0]
model.layers.1.mlp.up_proj.weight: [[768, 288]; Q4_0]
model.layers.1.post_attention_layernorm.weight: [[288]; F32]
model.layers.1.self_attn.k_proj.weight: [[288, 288]; Q4_0]
model.layers.1.self_attn.o_proj.weight: [[288, 288]; Q4_0]
model.layers.1.self_attn.q_proj.weight: [[288, 288]; Q4_0]
model.layers.1.self_attn.v_proj.weight: [[288, 288]; Q4_0]
model.layers.2.input_layernorm.weight: [[288]; F32]
model.layers.2.mlp.down_proj.weight: [[288, 768]; Q4_0]
model.layers.2.mlp.gate_proj.weight: [[768, 288]; Q4_0]
model.layers.2.mlp.up_proj.weight: [[768, 288]; Q4_0]
model.layers.2.post_attention_layernorm.weight: [[288]; F32]
model.layers.2.self_attn.k_proj.weight: [[288, 288]; Q4_0]
model.layers.2.self_attn.o_proj.weight: [[288, 288]; Q4_0]
model.layers.2.self_attn.q_proj.weight: [[288, 288]; Q4_0]
model.layers.2.self_attn.v_proj.weight: [[288, 288]; Q4_0]
model.layers.3.input_layernorm.weight: [[288]; F32]
model.layers.3.mlp.down_proj.weight: [[288, 768]; Q4_0]
model.layers.3.mlp.gate_proj.weight: [[768, 288]; Q4_0]
model.layers.3.mlp.up_proj.weight: [[768, 288]; Q4_0]
model.layers.3.post_attention_layernorm.weight: [[288]; F32]
model.layers.3.self_attn.k_proj.weight: [[288, 288]; Q4_0]
model.layers.3.self_attn.o_proj.weight: [[288, 288]; Q4_0]
model.layers.3.self_attn.q_proj.weight: [[288, 288]; Q4_0]
model.layers.3.self_attn.v_proj.weight: [[288, 288]; Q4_0]
model.layers.4.input_layernorm.weight: [[288]; F32]
model.layers.4.mlp.down_proj.weight: [[288, 768]; Q4_0]
model.layers.4.mlp.gate_proj.weight: [[768, 288]; Q4_0]
model.layers.4.mlp.up_proj.weight: [[768, 288]; Q4_0]
model.layers.4.post_attention_layernorm.weight: [[288]; F32]
model.layers.4.self_attn.k_proj.weight: [[288, 288]; Q4_0]
model.layers.4.self_attn.o_proj.weight: [[288, 288]; Q4_0]
model.layers.4.self_attn.q_proj.weight: [[288, 288]; Q4_0]
model.layers.4.self_attn.v_proj.weight: [[288, 288]; Q4_0]
model.layers.5.input_layernorm.weight: [[288]; F32]
model.layers.5.mlp.down_proj.weight: [[288, 768]; Q4_0]
model.layers.5.mlp.gate_proj.weight: [[768, 288]; Q4_0]
model.layers.5.mlp.up_proj.weight: [[768, 288]; Q4_0]
model.layers.5.post_attention_layernorm.weight: [[288]; F32]
model.layers.5.self_attn.k_proj.weight: [[288, 288]; Q4_0]
model.layers.5.self_attn.o_proj.weight: [[288, 288]; Q4_0]
model.layers.5.self_attn.q_proj.weight: [[288, 288]; Q4_0]
model.layers.5.self_attn.v_proj.weight: [[288, 288]; Q4_0]
model.norm.weight: [[288]; F32]
rot.freq_cis_imag: [[256, 24]; F32]
rot.freq_cis_real: [[256, 24]; F32]`

**Comment by soupslurpr** [comment]
I really want to be able to quantize it with it working since the q4_0 was 14 MB but the q3k is 91 MB. But its really cool I got it running in the first place.

**Comment by LLukas22** [comment]
I think if you try to quantize it with `q3k` it isn't quantized at all, since the k-quants need their tensors to be devisible by 256 and i believe tensors that aren't divisible by that will simply be skipped and "quantized" to f16 or f32. Thats why your model is 4 times the size of the `q4_0` version.

**Comment by soupslurpr** [comment]
Oh, I see. The model unfortunately is producing trash, at least compared to when I run it from the llama2-c example. Even though I "quantized" it to f32 (it was already in f32).

**Comment by LaurentMazare** [comment]
Could you point me at the model that you're trying to quantize? I can give it a quick spin just to see if there is anything obvious (and also hopefully to help with this workflow though longterm I hope it's the kind of thing that we can do with the pyo3 api that @LLukas22 is putting together).

**Comment by soupslurpr** [comment]
I did look into those, but they are too big in size, so I was hoping this could be smaller

**Comment by soupslurpr** [comment]
Thank you so much for that, it works great. Btw, q4_0 still fails with the same not even issue for some reason

**Comment by soupslurpr** [comment]
Also, I may be wrong but isn't the config already configurable? I can simply change the values in the Config struct. Or were you talking about something else?

**Comment by LaurentMazare** [comment]
> Btw, q4_0 still fails with the same not even issue for some reason

Right, I think this one is also not needed as we don't support avx512 at the moment (and probably won't support it until it's stabilized), so I've made #1202 to remove it. Give it a spin and let me know how it gets.

> Also, I may be wrong but isn't the config already configurable? I can simply change the values in the Config struct. Or were you talking about something else?

It is configurable in the api but not in the command line example. When using a binary file, the config comes from the binary file, when using safetensors/gguf the config is assumed to be `tiny` [here](https://github.com/huggingface/candle/blob/main/candle-examples/examples/llama2-c/main.rs#L265).

**Comment by soupslurpr** [comment]
> Right, I think this one is also not needed as we don't support avx512 at the moment (and probably won't support it until it's stabilized), so I've made #1202 to remove it. Give it a spin and let me know how it gets.

It works :D

> It is configurable in the api but not in the command line example. When using a binary file, the config comes from the binary file, when using safetensors/gguf the config is assumed to be `tiny` [here](https://github.com/huggingface/candle/blob/main/candle-examples/examples/llama2-c/main.rs#L265).

Could it have an option to store a gguf instead of a safetensors so that the correct metadata could be included and loaded?

**Comment by LLukas22** [comment]
> Could it have an option to store a gguf instead of a safetensors so that the correct metadata could be included and loaded?

@soupslurpr GGUF can store Key-Value pairs in its metadata section, meaning you could store the entire config in your gguf file with your weights, resulting in a single file you need to distribute. But you probably have to write code to load these metadata fields into candles config struct.

**Comment by LaurentMazare** [comment]
I think we already have code that would read this in the `quantized` example, the nice thing with adding the data as part of the tensor-tools quantized command is that then the files could be used with this example without additional flag but also probably with llama.cpp.

**Comment by soupslurpr** [comment]
Yeah that's what I thought, it would be easier to use

**Comment by LaurentMazare** [comment]
That's actually harder to do than what I would have thought as when quantizing we don't have the proper config any more. So what I just did is in the example, when using `.gguf` weights, the config is inferred from the shape of the weights. Some information is missing at this stage so this would only work if the config is one of the variant that gets used in Karpathy's repo, see #1208 for the actual change.

**Comment by soupslurpr** [comment]
That sounds pretty good, I'll try it later. Thank you again 😊. Should I close this issue now?

**Comment by soupslurpr** [comment]
Just tried and it works perfectly 💯 . I'll close this issue now as everything seems resolved :D
