### ISSUE TITLE
Feature Request: quantized Linear layer?

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#1191]
I noticed that there seems to be lacking support for a quantized Linear layer. I may be misunderstanding the motivations here, but it seems like Linear would be implementable? My only concern is that the current `broadcast_add` call in Linear::forward:
> https://github.com/huggingface/candle/blob/c8e197f68c46122dcde36830310450bb94376163/candle-nn/src/linear.rs#L52

would mean that the `bias` member of this quantized linear could not be quantized.

Are there any plans for quantized layers? I would be happy to contribute one.

**Comment by LaurentMazare** [comment]
Curious what you would use this layer for? We already have `QMatmul` which is what is needed for all the quantized model that I've seen so far (you can see that we have a bunch of example of these at the moment).
If you have some interest in this area, it would be nice if someone built a more fully featured llama.cpp like application on top of candle, typically supporting chat like interactions etc. This should probably be an external crate/application as it's too large for a candle example but it would be a great way to showcase how the candle crates can be used to build some apps on top of.

**Comment by EricLBuehler** [comment]
True, good point! Because I have no biases in my Linear layers, I do not need a QLinear.

What about a quantized Embedding layer? Can this be implemented with only QMatMul?

**Comment by LaurentMazare** [comment]
I don't feel this would bring much, we already have the layers needed for transformers like architectures, no need for anything specific besides that at the moment. Convs are tricky to get to work well with quantization, that's more of a research problem and I don't feel we should integrate anything on the candle side for this for now.

**Comment by EricLBuehler** [comment]
Ok, I agree about Conv. Just to clarify: I want to add quantized LoRA types for my candle-lora, and preferably, I would be able to have Linear and Embedding quantized LoRA layers. 

Is it possible to implement a quantized Embedding layer, and if so, do you have any advice on how to do it? Thanks!

**Comment by LaurentMazare** [comment]
I'm not sure what that would mean, the embedding layer gets accessed via an `index_select` op so I cannot see much downside to the way we're handling it currently (dequantizing the weights at model load time then applying the op), you might save very slightly on memory but that's likely negligible compared to the rest of the memory usage. Maybe I'm missing something here though. All these layers should be implementable as custom ops, that's actually how the quantized matmul is implemented so you can give this a try directly in candle-lora and let us know how it goes.

**Comment by EricLBuehler** [comment]
Ok, I plan on implementing a quantized LoRA shortly. Thank you for confirming that I would have to dequantize the Embedding layer weights anyway. From what I understand, implementing a quantized Embedding LoRA layer would not have a benefit.

I am going to close this issue as I think it is resolved. Thank you for your help!
