### ISSUE TITLE
BackwardNotSupported { op: "gelu" } ?

### ISSUE THREAD

**Issue by omkar-12bits** [huggingface/candle#1227]
let  cls_tensor = hidden_states.get(i)?.get(0)?.unsqueeze(0)?;
let cls_tensor = hidden_states.i((..,0))?;

both of the above methods throw the same error when used 
 optimizer.backward_step(&loss).unwrap();

i'm training bert model and i need to pull out that cls tokens from  hidden states . will it be okay if i convert the tensor into vector and convert the vector back into tensor after the operation? won't it break the backward graph of tensor?

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BackwardNotSupported { op: "gelu" }', src/train.rs:184:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by LaurentMazare** [comment]
Converting to a vector will indeed break the computation graph used for the backward pass.
Is it possible that you're using an old version of candle? The backward pass for gelu was only added recently, could you try using the github tip if that's not already the case?

**Comment by omkar-12bits** [comment]
Thanks !!! it worked with the latest version of candle :)
