### ISSUE TITLE
Add a way to get all parameters from VarBuilder?

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#1231]
Hello everybody,

I was looking at the `VarBuilder` API, but realized there is no way to get a tree of all parameters stored in VarBuilder? I think an API similar to Pytorch's [`named_parameters`](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.named_parameters) would be great.

What are your thoughts?

**Comment by LaurentMazare** [comment]
This wouldn't really make sense for a `VarBuilder` as these define ways to build tensors - these can either be coming from disk (in which case the lower level `safetensors`/... apis will tell you about the list of tensors), initialize a new tensor on the flight or do anything arbitrary.
On the other end, this is defined for `VarMap` and can be accessed via the `data()` method [here](https://github.com/huggingface/candle/blob/36fb84f03802073e137ead8738b01cfd3e470256/candle-nn/src/var_map.rs#L116) (or `all_vars` if you don't need the names).

**Comment by EricLBuehler** [comment]
Ah, ok. Thanks!
