### ISSUE TITLE
Example candle-wasm-examples/llama2-c is currently broken

### ISSUE THREAD

**Issue by katopz** [huggingface/candle#1238]
<img width="1059" alt="image" src="https://github.com/huggingface/candle/assets/97060/8103fa0a-ab5b-4eda-a90a-a0a05c498cc9">

```
error in worker "model creation error CannotFindTensor { path: \"lm_head.bias\" }"
```

Maybe only me?

**Comment by radames** [comment]
probably, I see @LaurentMazare has been working on [quantized](https://github.com/huggingface/candle/commits/main/candle-examples/examples/llama2-c) version, we might have to adapt the example, @LaurentMazare could you create a model page with the new weights? thanks

**Comment by LaurentMazare** [comment]
Ah thanks for reporting this (and thanks @radames for looking into it). I definitely broke this in #1194 , sorry about that. I just pushed a tentative fix but I cannot easily test it at the moment (some conflict versions with my nix environment) - could you give it another spin and let me know how it goes?

**Comment by katopz** [comment]
> Ah thanks for reporting this (and thanks @radames for looking into it). I definitely broke this in #1194 , sorry about that. I just pushed a tentative fix but I cannot easily test it at the moment (some conflict versions with my nix environment) - could you give it another spin and let me know how it goes?

Working now case closed! Thanks!

**Comment by radames** [comment]
thanks @LaurentMazare ! is it worth to add the quantized example as well?
