### ISSUE TITLE
How inference on a new model, have to hand written model.rs manually?

### ISSUE THREAD

**Issue by lucasjinreal** [huggingface/candle#1239]
Just wonder if there scripts convert a pth or onnx to candle format maybe?

**Comment by LaurentMazare** [comment]
There is no automated convesion script for onnx or pth at the moment so the model description has to be written manually. There is this [candle-tutorial](https://github.com/ToluClassics/candle-tutorial) that describes how to do this.

**Comment by lucasjinreal** [comment]
thank u. will it consider support in the future? also, wanna ask how's the speed compares with onnxruntime c++?

**Comment by LaurentMazare** [comment]
It's likely for onnx to be supported at some point - though this don't have to be done in the main candle repo, hopefully it could be an external crate. Supporting pth in general is harder so I'm less optimistic on this.
Re performance, this depends a lot on the model that you consider so the best is probably to run your own benchmarks on the models that you cared about. [text-embeddings-inference](https://github.com/huggingface/text-embeddings-inference#text-embeddings-inference) has some benchmarks where candle outperforms the onnx backend - note that this uses a bunch of custom kernels on the candle side.
