### ISSUE TITLE
Candle REST api webserver support for t5 models

### ISSUE THREAD

**Issue by bm777** [huggingface/candle#1247]
Will you also provide this feature, I'm specifically interested in t5 models.

If not, would be open to contributing to setting up a rest API support for the t5 model, and then for all models depending on the inference pipeline.

**Instruction or guide:**
Either use Rocket or Actrix

**Comment by LaurentMazare** [comment]
Providing some serving infrastructure on top of candle model would be great but is probably not in the scope of this repo - the best would be to build this in a separate repo & crate. If you end up doing so and it works well, happy to add a link to it in the "external resources" section so that it's easier to discover.

**Comment by bm777** [comment]
Ok @LaurentMazare 
great, thank you then for the clarification :)
I will let you know when it is ready.

**Comment by Liangdi** [comment]
i am writing some web server examples using actix , but not t5 , it's blip and whisper , when done, i will create a github repo.

**Comment by bm777** [comment]
@Liangdi 
It is obvious to do for `llama` or `whisper`, because it follows the trends, for my case I will do for `t5`. I have been waiting for so long for people to build stuff around the models. They mostly focus on encoder-only or decoder-only. They never provide support for the **encoder-decoder**. Talking about `vllm`, `llama.cpp`, until now it is still in the roadmap. 
Sorry to tell you that, I'm not gonna wait for someone else for `t5` :)

**Comment by EricLBuehler** [comment]
@bm777, I have been working on https://github.com/EricLBuehler/candle-vllm for the past week now. I support an OpenAI API, and have added a Llama pipeline. If you want to contribute a T5 pipeline, feel free!

**Comment by bm777** [comment]
@EricLBuehler Basically, it is only this I want in fact, to infer -> [this]( https://github.com/huggingface/candle/tree/main/candle-examples/examples/t5)

Requested  https://github.com/EricLBuehler/candle-vllm/issues/1

**Comment by LaurentMazare** [comment]
Closing this for now as out of scope, feel free to re-open or create a new issue if you see any way we can help.
