### ISSUE TITLE
What's the equivalent of `logn_tensor[:, seq_start:seq_end, :, :]` in candle?

### ISSUE THREAD

**Issue by arkxfly** [huggingface/candle#1249]
What's the equivalent of `logn_tensor[:, seq_start:seq_end, :, :]` in candle?

BTW:  It seems that discord has not created candle's channel.

**Comment by LaurentMazare** [comment]
You can do:
```rust
use candle::IndexOp; // brings the proper trait in scope for .i to work.

let res = logn_tensor.i((.., seq_start..seq_end))?;
```

The discord channel should be available on the huggingface discord and is working well at the moment as far as I can tell.
