### ISSUE TITLE
Add the Zephyr model?

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#1280]
Hello everybody,

I have noticed there is no Zephyr model implementation. Here is a link to the HF model hard: [zephyr-7b](https://huggingface.co/HuggingFaceH4/zephyr-7b-alpha).

Is there a plan to add this model? Thanks!

**Comment by EricLBuehler** [comment]
Oh, ok. Thanks!

**Comment by LaurentMazare** [comment]
Also just to mention that zephyr is already supported specifically in the quantized example, see [here](https://github.com/huggingface/candle/blob/main/candle-examples/examples/quantized/main.rs#L52).
