### ISSUE TITLE
Type Mismatch for reading Mistral7B Quantized weights compilation error

### ISSUE THREAD

**Issue by sagarpatel-MarutiIO** [huggingface/candle#1301]
Hi, I am trying to use Mistral7B quantized version. I was following the code from the examples repo, but I came across this error. 

Here is my code: 

```
let model_path = "../mistral/mistral7b.gguf";
    let mut file; 
    match std::fs::File::open(&model_path){
        Ok(model_file)=>file=model_file,
        Err(err)=>{
            panic!("Error loading model from file during inference: {:?}",err);
        }
    }
    let start = std::time::Instant::now();

let model_content = match gguf_file::Content::read(&mut file){
        Ok(file_data)=>file_data,
        Err(err)=> {
            panic!("Error loading file data from model file: {:?}",err);
        }
    };
println!(
        "loaded {:?} tensors in {:.2}s",
        model_content.tensor_infos.len(),
        start.elapsed().as_secs_f32(),
    );
 let mut model = match ModelWeights::from_gguf(model_content, &mut file){
        Ok(model_weights)=>model_weights,
        Err(err)=>{
            panic!("Error extracting weights from gguf: {:?}",err);
        }
    };
```

Here is the error that I get: 

```
error[E0308]: mismatched types
   --> src/models/mistral_inference.rs:88:51
    |
88  |     let mut model = match ModelWeights::from_gguf(model_content, &mut file){
    |                           ----------------------- ^^^^^^^^^^^^^ expected `Content`, found a different `Content`
    |                           |
    |                           arguments to this function are incorrect
    |
    = note: `Content` and `Content` have similar names, but are actually distinct types
note: `Content` is defined in crate `candle_core`
```

When I try to compile the code I get a warning stating that the function from_gguf was expecting a input of type Content, but received another struct of type Content. I am not sure what to do here. I would appreciate any help! Thanks :)

**Comment by LaurentMazare** [comment]
Your example works fine for me, below is the version that I've put in a `main.rs` file.
Would you be able to provide the full way to reproduce the issue? Maybe creating a small repo with the code that fails for you with the `Cargo.toml` and all as well as the command that you run?

```rust
use candle::quantized::gguf_file;
use candle_transformers::models::quantized_llama as model;
use model::ModelWeights;

fn main() -> anyhow::Result<()> {
    let model_path = "../mistral/mistral7b.gguf";
    let mut file;
    match std::fs::File::open(&model_path) {
        Ok(model_file) => file = model_file,
        Err(err) => {
            panic!("Error loading model from file during inference: {:?}", err);
        }
    }
    let start = std::time::Instant::now();

    let model_content = match gguf_file::Content::read(&mut file) {
        Ok(file_data) => file_data,
        Err(err) => {
            panic!("Error loading file data from model file: {:?}", err);
        }
    };
    println!(
        "loaded {:?} tensors in {:.2}s",
        model_content.tensor_infos.len(),
        start.elapsed().as_secs_f32(),
    );
    let _model = match ModelWeights::from_gguf(model_content, &mut file) {
        Ok(model_weights) => model_weights,
        Err(err) => {
            panic!("Error extracting weights from gguf: {:?}", err);
        }
    };

    Ok(())
}
```

**Comment by sagarpatel-MarutiIO** [comment]
Hi, I was able to solve the issue. I think I can also reliabily recreate it too. I assume more people might run into it, so I would like to help out fix this issue before it becomes a problem. This is what I understand about the issue so far. Overall the issues comes up because for some reason Rust is distinguishing between candle_core library that is being pulled from crates.io, and the one being used in the overall candle repo. For example candle_transformers doesn't get candle_core from crates.io it gets it from a local directory/same repo. Rust is flagging that candle_core is a different version than the one you get from crates.io. Adding candle_nn to the mix confuses the compiler more. 

I will try and create a small repo with the same issue for you to check out. The way I was able to fix it is by adding all the files from candle_nn, and candle_transformers that my program needed to run the infrence. The result is my inference time is extremely slow. So I am currently trying to optimize that. 

Maybe I used the repo the wrong way, and I was supposed to pull the entire github repo and use that instead of getting individual libraries from crates.io? 

Also just wanted to thank you for all your efforts! I really appreciate everything you have done for the open source community! :)

**Comment by sagarpatel-MarutiIO** [comment]
Hi Here is the repo that reproduces the error. https://github.com/Maruti-io/ReproducingError . It is the same code as yours pretty much, but this one throws an error. I think the reason why this throws an error is because I was importing candle_core from git, and not from crates.io. If you look at the Cargo.toml file you can see that. This seems to be an issue on my part though, sorry about that! I think I was following the instructions on this page: https://huggingface.github.io/candle/guide/installation.html .

Then I realized I needed candle_transformers, and added that using cargo add candle-transformers. But then I get the error I mentioned above. I hope this helps. Either way I think we can say that the issue is resolved right?

**Comment by Ather23** [comment]
I had the same problem. Had to change from this:
```
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.3.1" }
```
to this:
```candle-core = "0.3.1"``

It seems like cargo downloads crates from git differently compared to how it get's it from crates.io.
