### ISSUE TITLE
Is there a plan to support calculating the `variance` of Tensor

### ISSUE THREAD

**Issue by antodyn** [huggingface/candle#1302]
I  found the functions about [`mean`](https://docs.rs/candle-core/latest/candle_core/?search=mean), which corresponds to the [`torch.mean`](https://pytorch.org/docs/stable/generated/torch.mean.html) function in PyTorch. But I did not find a function to compute the variance of the Tensor, similar to the [`torch.var`](https://pytorch.org/docs/stable/generated/torch.var.html#torch.var) function in PyTorch. Is there a plan to support the calculation of Tensor variance?

**Comment by LaurentMazare** [comment]
Thanks for the suggestion, a method similar to `torch.var` has been added in #1315 .

**Comment by LaurentMazare** [comment]
Closing for now, feel free to re-open if needed or create a new issue.
