### ISSUE TITLE
How to repeat_interleave on Tensor?

### ISSUE THREAD

**Issue by bragovo** [huggingface/candle#1304]
There is [repeat_interleave](https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html) function, but I can't find analog in candle.

I need convert `tensor([[6110,    1]])` to `tensor([[6110,    1], [6110,    1], [6110,    1]])`

I found some examples [like](https://github.com/huggingface/candle/blob/f772213e844fdfcc8dbaf662fc11819f4028dc78/candle-transformers/src/models/segment_anything/mask_decoder.rs#L234) this and [this](https://github.com/huggingface/candle/blob/73d02f4f57c788c43f3e11991635bc15701c25c0/candle-transformers/src/models/mpt.rs#L137). But in my case the result is `tensor([6110, 6110, 6110, 1, 1, 1])`.

Looks like I do something wrong: :-D I expect result the same as from python https://github.com/huggingface/transformers/blob/main/src/transformers/generation/utils.py#L3090C31-L3090C31

How I can repeat python example in current candle version?

**Comment by LaurentMazare** [comment]
Sorry I'm a bit confused here, `repeat_interleave` seems to do what I would have expected based on the specified axis, e.g.:
```rust
use candle_core::{Device, Result, Tensor};

fn repeat_interleave(img: &Tensor, repeats: usize, dim: usize) -> Result<Tensor> {
    let img = img.unsqueeze(dim + 1)?;
    let mut dims = img.dims().to_vec();
    dims[dim + 1] = repeats;
    img.broadcast_as(dims)?.flatten(dim, dim + 1)
}

fn main() -> Result<()> {
    let inp = Tensor::new(&[[6610u32, 1]], &Device::Cpu)?;
    println!("{inp}");
    let r = repeat_interleave(&inp, 3, 0)?;
    println!("{r}");
    let r = repeat_interleave(&inp, 3, 1)?;
    println!("{r}");
    Ok(())
}
```
```
[nix-shell:~/github/candle]$ cargo run --example basics
[[6610,    1]]
Tensor[[1, 2], u32]
[[6610,    1],
 [6610,    1],
 [6610,    1]]
Tensor[[3, 2], u32]
[[6610, 6610, 6610,    1,    1,    1]]
Tensor[[1, 6], u32]
```
And this to me seems in line with the [PyTorch implementation](https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html#torch-repeat-interleave) (except that we don't flatten the original tensor by default). What would you expect it to return?

**Comment by bragovo** [comment]
Oh, no... my bad, sorry.. I didn't notice that `tokenizer.encode(...)` return just `[6610, 1]` instead `[[6610,    1]]` 🤦 
Thank you.
