### ISSUE TITLE
q6k quantization is missing model.safetensors for flan-t5-xl model using Tensor-tools

### ISSUE THREAD

**Issue by bm777** [huggingface/candle#1311]
To quantize flan t5 models, you proposed to use `tensor-tools`, but from [google/flan-t5-xl](https://huggingface.co/google/flan-t5-xl/tree/main) hg, there is no `model.safetensors` file.
and for using tensor-tools, is there any other way to take `pytorch_model-00001-of-00001.bin` and `pytorch_model-00001-of-00002.bin` file to do the quantization? 

```bash
cargo run --example tensor-tools --release -- quantize --quantization q6k PATH/TO/T5/model.safetensors /tmp/model.gguf
```

@LaurentMazare, any recommendation is wanted.

**Comment by LaurentMazare** [comment]
The easiest there would probably be to use python to load the `.bin` files and save them to `.safetensors`.
Something along the lines of the following untested snippet:
```python
import torch

all_weights = {}
for filename in ["pytorch_model-00001-of-00002.bin", "pytorch_model-00002-of-00002.bin"]:
    _model = torch.load(filename, map_location=torch.device('cpu'))
    all_weights = { **all_weights, **_model }

from safetensors import safe_open
from safetensors.torch import save_file

save_file(all_weights, "/tmp/model.safetensors")
```

**Comment by bm777** [comment]
Thanks, it worked :)
