### ISSUE TITLE
Question: How to edit specific indices of a tensor?

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#1319]
Hello everybody,

While developing beam search for candle-sampling, I have run into a small issue where it appears there is no way to edit specific indices of a tensor after creation. For example, in Python the following works for lists (and very similar for pytorch tensors):

```python
values = [[1,2,3],[4,5,6]]
values[0][0] = 0
print(values) #[[0,2,3],[4,5,6]]
```

Is there an equivalent in `Candle` which I can use to edit specific indices of a tensor without creating a new tensor?

**Comment by ToluClassics** [comment]
It seems candle Tensors in general are not mutable;

see: https://github.com/huggingface/candle/issues/1163

**Comment by EricLBuehler** [comment]
True, makes sense.
