### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dan-ilin** [huggingface/candle#1325]
Hi, would it be possible to push up a new release to crates.io?
There are a few features that have been added in the last few weeks that I would like to use in my project, but it seems the last release was a month ago.

**Comment by LaurentMazare** [comment]
Right, I actually just bumped the version to 0.3.1 so as to be able to make a release, should land tomorrow hopefully.

**Comment by dan-ilin** [comment]
Thank you!

**Comment by LaurentMazare** [comment]
`0.3.1` should be available on crates.io now.
