### ISSUE TITLE
Cannot run Mistral-7B with `--features metal`

### ISSUE THREAD

**Issue by Paulescu** [huggingface/candle#1343]
Hi there!

I am trying to run the Mistral example on my Macbook M2 Pro.

It works when I only use CPUs:
```
$ cargo run --example mistral --release -- --prompt 'Write helloworld code in Rust' --sample-len 150
```

But it doesn't when I try to use my Metal hardware:
```
$ cargo run --example mistral --release --features metal -- --prompt 'Write helloworld code in Rust' --sample-len 150
   Compiling candle-core v0.3.1 (/Users/paulabartabajo/src/candle/candle-core)
error[E0432]: unresolved import `metal_backend`
  --> candle-core/src/lib.rs:92:9
   |
92 | pub use metal_backend::{MetalDevice, MetalError, MetalStorage};
   |         ^^^^^^^^^^^^^ use of undeclared crate or module `metal_backend`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `candle-core` (lib) due to previous error
```

Any ideas where is the problem?

Thanks in advance,

Pau

**Comment by LaurentMazare** [comment]
The metal backend is not fully integrated yet, sorry about that. You can run with `--features accelerate` instead which should make the matmul run on the neural engine of your cpu if any.

**Comment by Paulescu** [comment]
Thanks for your response @LaurentMazare .

When will the `--features metal` backend be available?

By the way, great job guys. So far I am loving candle 🕯️ ❤️

**Comment by ivarflakstad** [comment]
I've been helping out a bit with this feature.
Can't give you a reliable estimate, but we're working on it when we have the opportunity.

The `metal4` branch supports running some models, for example phi if you want to test it. There is a bug on the M1 Pro though.

There are some bugs to squash and several kernels left to implement  before we can say candle fully supports metal.
After that there are surely many optimisations to look into as well.

**Comment by henry-merrilees** [comment]
I am sure this Is known but same thing with mi_x_tral on metal as well. Wish I knew enough to help it along. If there is somewhere else like metal-rs I should be reporting this to, please lmk! Candle is wonderful, so thank you all so much!

```
>  cargo run --features metal --example mixtral --release -- --tracing --prompt "def print_prime(n): "
    Finished release [optimized] target(s) in 0.19s
     Running `target/release/examples/mixtral --tracing --prompt 'def print_prime(n): '`
avx: false, neon: true, simd128: false, f16c: false
temp: 0.00 repeat-penalty: 1.10 repeat-last-n: 64
retrieved the files in 63.021167ms
Error: Metal error Error while loading function: "Function 'cast_bf16_f32' does not exist"

Caused by:
    Error while loading function: "Function 'cast_bf16_f32' does not exist"
```

**Comment by ivarflakstad** [comment]
I believe this is solved by now @LaurentMazare :)


@henry-merrilees regarding bf16 this is most likely because your mac does not have native bfloat support.
