### ISSUE TITLE
Example phi with cuda and model phi-hermes gives 404 error

### ISSUE THREAD

**Issue by thomas9911** [huggingface/candle#1345]
When trying out phi example with the model phi-hermes it returns a 404 error

To reproduce:

```sh
cargo run --example phi --release --features cuda -- --model phi-hermes --prompt 'Hallo'
```

Error:

```text
https://huggingface.co/lmz/candle-quantized-phi/resolve/main/model-phi-hermes-1_3B.safetensors: status code 404
```

Indeed looking at https://huggingface.co/lmz/candle-quantized-phi/tree/main it is not there.

**Comment by LaurentMazare** [comment]
Ah thanks for pointing this out, somehow I forgot to upload these weights when creating the model. These should be available now.

**Comment by thomas9911** [comment]
No problem, thank you for uploading

**Comment by yugaljain1999** [comment]
@thomas9911  I am not able to run cargo with "cuda" as feature, it's throwing following error

```
thread 'main' panicked at 'Could not get Cuda compute cap: no gpu codes parsed from nvcc', /home/azureuser/.cargo/git/checkouts/candle-0c2b4fa9e5801351/8d8f48c/candle-kernels/build.rs:106:41

warning: build failed, waiting for other jobs to finish...
```

Here Compute capability is 7.0 , nvidia-smi prints 12.1 cuda version and nvcc prints 9.1 cuda compilation tools.
If you can tell me what cuda and nvidia driver version you are using, then also it may help.

Thanks

**Comment by thomas9911** [comment]
It looks like Cuda is not configured correctly (but I'm no expert on it) do any other example work? @yugaljain1999 

In the end my graphics card did not work with the hermes model because its too old (I have a GTX 1080ti) and it is using some new data format
