### ISSUE TITLE
Unable to Run Yi-6B Model Example: Tensor "model.layers.0.ln1.weight" Not Found

### ISSUE THREAD

**Issue by jlvihv** [huggingface/candle#1378]
**Description of the Issue**:
I encountered an issue when trying to run the `yi` example project included with the Yi-6B model. The initialization of the model fails due to the tensor `"model.layers.0.ln1.weight"` not being found.

**Steps to Reproduce**:
1. Execute the command `cargo run --example yi -- --prompt "hello"` to run the `yi` example project.
2. Observe that the model initialization fails, with the specific error indicating the absence of the tensor `"model.layers.0.ln1.weight"`.

**Expected Behavior**:
The `yi` example project runs successfully, with the Yi-6B model being properly initialized and the provided prompt ("hello") being processed.

**Actual Behavior**:
The execution of the `yi` example project fails during model initialization. The error message states that the tensor `"model.layers.0.ln1.weight"` cannot be found, preventing the model from being loaded correctly.

**Contextual Information**:
- The failure occurs in the `Model::new` function during the instantiation of `DecoderLayer`.
- Functions `RmsNorm::new` and `candle_nn::rms_norm` are involved in the initialization process. These functions set up a `LayerNormConfig` with `affine: false`.
- The function `layer_norm` attempts to create a `weight` tensor, but it appears to be unsuccessful in locating or creating this tensor for the path `"model.layers.0.ln1.weight"`.

I am seeking assistance in resolving this issue to successfully run the `yi` example project with the Yi-6B model.

**Comment by LaurentMazare** [comment]
Thanks for reporting this, it looks like the naming convention for tensors was changed to follow the llama convention a week ago or so. I've just merged #1381 which should hopefully fix this, please give it a spin and let me know how it goes.
