### ISSUE TITLE
norm, matrix_norm, Frobenius norm, nuclear norm

### ISSUE THREAD

**Issue by rockerBOO** [huggingface/candle#1380]
Wondering what approach is expected for getting these norms.

I'm specifically trying to get the matrix norm. In most specific terms trying to get `tensor.norm()` from pytorch. I understand that `.norm()` is deprecated now but I am looking at the matrix_norm of Frobenius norm for a matrix. I am fresh off learning about norms so my terminology or usage may not be accurate. 

In this example I have a LoRA with lora_up and lora_down and I combine them and want to find the norm of the new tensor.

```rust
    #[test]
    fn test_to_tensor_norm() {
        let device = candle_core::Device::Cpu;
        let data: Vec<f32> = vec![
            1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        ];

        let up_tensor = Tensor::from_vec(data, (1, 1, 4, 4), &device).expect("to get up tensor");

        let data: Vec<f32> = vec![
            1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        ];

        let down_tensor =
            Tensor::from_vec(data, (1, 1, 4, 4), &device).expect("could not get down tensor");

        assert_eq!(
            to_tensor_norm(&up_tensor, &down_tensor, 32.).expect("to get tensor norm"),
            128.0
        );
    }

fn to_tensor_norm(
    up_tensor: &Tensor,
    down_tensor: &Tensor,
    alpha: f32,
) -> Result<f32, candle_core::Error> {
    let dim = down_tensor.shape().dims()[0];
    let scale = alpha / dim as f32;
    let updown = up_tensor.matmul(down_tensor)?;
    let updown = updown.broadcast_mul(&Tensor::new(scale, &Device::Cpu)?)?;
    let norm = updown
        .abs()?
        .powf(2.)?
        .sqrt()?
        .max(2)? // get the row max? that's my intention at least
        .flatten(0, 2)? // put all the tensors together to get the max value from
        .max(0)?; // get the max of all the row'd max values
    norm.to_scalar()
}
  ```

So I'm wondering what the approach should be here. There is no matrix_norm function that I could find in candle_core or candle_nn but maybe I'm missing where it would be. 

Pytorch example
```python
>>> import torch
>>> torch.ones(1, 1, 4, 4)
tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])
>>> ones = torch.ones(1, 1, 4, 4)
>>> ones.norm() * 32
tensor(128.)
```

Thank you!

https://pytorch.org/docs/stable/generated/torch.linalg.matrix_norm.html#torch.linalg.matrix_norm
https://pytorch.org/docs/stable/generated/torch.norm.html

**Comment by LaurentMazare** [comment]
I'm not sure about your computation, isn't the frobenius norm just the square root of the sum of the squares of the coefficients (for a real matrix)? In this case one can just do something like `m.sqr()?.sum_all()?.sqrt()?`. That's assuming that there is no batch dimension, if there is one (or multiple ones), then `m.sqr()?.sum((D::Minus2, D::Minus1))?.sqrt()?` should be better.

**Comment by rockerBOO** [comment]
Yes this makes sense to me and works as expected. Thank you!

For others who may be translating from PyTorch. Order calculations are on [torch.linalg.matrix_norm.html](https://pytorch.org/docs/stable/generated/torch.linalg.matrix_norm.html#torch.linalg.matrix_norm) if you need the other orders. `tensor.norm()` defaults to Forbenius. 

```rust
pub fn matrix_norm_forbenius_2d(t: &Tensor) -> Result<f32, Error> {
    t.sqr()?.sum((D::Minus2, D::Minus1))?.sqrt()?.to_scalar()
}

pub fn matrix_norm_forbenius(t: &Tensor, dims: (D, D)) -> Result<Tensor, Error> {
    t.sqr()?.sum(dims)?.sqrt()
}
...
let t = Tensor::arange(0., 27., &Device::Cpu)
    .unwrap()
    .reshape((3, 3, 3))
    .unwrap()
    .to_dtype(candle_core::DType::F32)
    .unwrap();
assert_eq!(
    matrix_norm_forbenius(&t, (D::Minus2, D::Minus1))
        .unwrap()
        .to_vec1::<f32>()
        .unwrap(),
    Tensor::from_vec(vec![14.282857, 39.76179, 66.45299], 3, &Device::Cpu)
        .unwrap()
        .to_dtype(candle_core::DType::F32)
        .unwrap()
        .to_vec1::<f32>()
        .unwrap()
);

```

```python
>>> a = torch.arange(27).to(dtype=torch.float32).reshape(3, 3, 3)
>>> torch.linalg.matrix_norm(a)
tensor([14.2829, 39.7618, 66.4530])
```
