### ISSUE TITLE
Yi  example error when I try to to run on GPU(metal).

### ISSUE THREAD

**Issue by overheat** [huggingface/candle#1382]
`Error: to dtype BF16 - F32`

BTW, `--features accelerate` works for me on my MacBook. I just wondering how much performance improvement when enable metal.

**Comment by okpatil4u** [comment]
Yes, same here. This was the command I used.

`cargo run --example mistral --release --features metal -- --prompt 'Write helloworld code in Rust' --sample-len 150`

**Comment by rozgo** [comment]
Yolo does the same:

`cargo run --example yolo-v8 --release --features metal -- candle-examples/examples/yolo-v8/assets/bike.jpg`

**Comment by noahgift** [comment]
Love candle, but I also got this issue, so temporarily moved to Llamafile:  https://github.com/Mozilla-Ocho/llamafile

**Comment by ivarflakstad** [comment]
Not that surprising since metal support is very new and still being actively implemented.

Maybe it's improved now. Welcome to try out with `--quantized` as well 😊

**Comment by LaurentMazare** [comment]
The necessary bits for yolo-v8 have been added so should be all good now, mistral should also be all good if your hardware/installed metal version support bfloats.
