### ISSUE TITLE
LeoLM is in the category of general LLM (llama example)?

### ISSUE THREAD

**Issue by bm777** [huggingface/candle#1396]
Could we use the llama example to run other extended llama model like LeoLM?

**Comment by LaurentMazare** [comment]
Yes if it's a standard llama2 model, it should work out of the box with the llama example. I've just merged some changes to add support for it for the quantized model, you can easily try it out with:
```bash
cargo run --example quantized --release  -- --prompt " " --which 7b-leo
```

**Comment by bm777** [comment]
@LaurentMazare thank you.
