### ISSUE TITLE
Will NPU be supported in the future？

### ISSUE THREAD

**Issue by hubertshelley** [huggingface/candle#1403]

**Comment by LaurentMazare** [comment]
I don't even know what is meant by NPU here, I would guess "neural processing unit" but that's a generic term that could be used for lots of different architectures so would probably need more details to answer. If it's about the ANE used in apple silicon chips, these are already supported through the use of apple accelerate framework (but you have to use `--feature accelerate`).

**Comment by mokeyish** [comment]
It seems like this

https://support.huawei.com/enterprise/en/doc/EDOC1100141951/cd9f992b/npu-board-components

**Comment by hubertshelley** [comment]
> I don't even know what is meant by NPU here, I would guess "neural processing unit" but that's a generic term that could be used for lots of different architectures so would probably need more details to answer. If it's about the ANE used in apple silicon chips, these are already supported through the use of apple accelerate framework (but you have to use `--feature accelerate`).

@LaurentMazare Sorry, I didn't add a detailed description.
This issue is about Huawei's NPU chip by  as described by @mokeyish

**Comment by LazyGeniusMan** [comment]
Intel open source its NPU implementation library. Looks like it's using OpenVINO

https://github.com/intel/intel-npu-acceleration-library
https://intel.github.io/intel-npu-acceleration-library/cpp_reference.html
https://github.com/intel/openvino-rs
