### ISSUE TITLE
Missing Timestamps in Whisper output

### ISSUE THREAD

**Issue by WenqingZong** [huggingface/candle#1417]
Hi, I want to ask another question about the whisper implementation. 

<img width="1169" alt="image" src="https://github.com/huggingface/candle/assets/43934749/9fd17a11-304b-4d2f-beac-3d0286e526a9">

(Figure taken from [original paper](https://cdn.openai.com/papers/whisper.pdf))

If I understand correctly, Whisper should output `timestamps tokens` for every texts it recognises should I provide tokens `[SOT_Token, English_Token, Transcribe_Token]` (i.e., no `NO_TIMESTAMPS_TOKEN`), but I didn't see any `timestamps tokens` in the output. 

This situation is even wired when it comes to using different models. It seems only `distil_large` model correctly outputs `timestamps_tokens` but `tiny`, `base`, `small`, `medium`, and `large_v2` all failed to do so. 

I found this problem as I noticed there is some [missing logic](https://github.com/openai/whisper/blob/e58f28804528831904c3b6f2c0e473f346223433/whisper/transcribe.py#L257C1-L343C58) when compared to python version, and I cannot get any `timestamp_tokens` when I tried to add them.

**Comment by LaurentMazare** [comment]
Just to be sure, you did try the whisper example with the `--timestamps` flag (which adds support for timestamps on the candle side) and it didn't work out and produce the appropriate timestamp tokens? I think I tested it on a few examples a couple months back and it was producing appropriately timestamped data.

**Comment by WenqingZong** [comment]
Thanks for your reply, I didn't notice the `--timestamps` flag. I'll close the issue then.
