### ISSUE TITLE
MoE support?

### ISSUE THREAD

**Issue by runvnc** [huggingface/candle#1421]
Any plans to support MoE such as the new Mistral 8x7b model? https://github.com/open-compass/MixtralKit/blob/main/README.md

**Comment by bofen97** [comment]
I'm also following this work and really hope to implement it in candle.

**Comment by LaurentMazare** [comment]
I actually have a PR in flux to implement it, #1437 . Currently it's able to generate text but it's garbled so there is a bit of lining up with the python implementation to be done.

**Comment by bofen97** [comment]
> I actually have a PR in flux to implement it, #1437 . Currently it's able to generate text but it's garbled so there is a bit of lining up with the python implementation to be done.

I am looking at #1437. I am actually studying the source code of candle and learning how to add new models to candle. This PR has helped me a lot, thank you.

**Comment by LaurentMazare** [comment]
Just merged a first cut of #1437 as it seems to generate decent text, there is a [dedicated example](https://github.com/huggingface/candle/tree/main/candle-examples/examples/mixtral).
It's currently very slow, especially to load the weights, not sure what is going on here and it might be an issue with my box but some more investigation is likely required.

**Comment by LaurentMazare** [comment]
Closing this now that MoE is supported in both the mistral model and the quantized example (using `llama.cpp` gguf files). Feel free to reopen if further issues.
