### ISSUE TITLE
Probably a dumb question about IndexOps

### ISSUE THREAD

**Issue by cchance27** [huggingface/candle#1427]
Just wondering, is their a correct way to implement the pytorch equivilent of 

attn_mask[:, 0] = 1

i know that i can do attn_mask.i((.., 0))? but that doesn't allow me to fill that area of the tensor like the existing code from pytorch.

**Comment by EricLBuehler** [comment]
One option is to create a tensor with the correct shape filled with ones, and then use `slice_assign`. Would that work?

**Comment by cchance27** [comment]
That seems to have simulated what i was looking for though wow that's not as nice as doing it in python lol

```rust
pub fn random_attention_mask(shape: Vec<usize>, _name: Option<String>, device: &Device) -> anyhow::Result<Tensor> {
    let vocab_size = 2;
    let mut attn_mask = ids_tensor(shape, vocab_size, None, device)?;
    // make sure that at least one token is attended to for each batch
    // we choose the 1st token so this property of `at least one being non-zero` still holds after applying causal mask

    // attn_mask[:, 0] = 1
    let ones = Tensor::ones((vocab_size, 1), candle_core::DType::U32, device)?; // Create a Tensor of 1's (vocab_size, 1) 
    attn_mask = attn_mask.slice_assign(&[0..vocab_size, 0..1], &ones)?; // Assign the ones to the tensor

    Ok(attn_mask)
}```

This is what i came up with that worked.

**Comment by cchance27** [comment]
i feel like their should be function for setting a dimension like this
