### ISSUE TITLE
Text-to-Speech example?

### ISSUE THREAD

**Issue by overheat** [huggingface/candle#1428]
Could you provide an example for Text-to-Speech, like this:
https://huggingface.co/tasks/text-to-speech

**Comment by ToluClassics** [comment]
Hi @overheat is there a particular model you'd like to see?

**Comment by Catchawink** [comment]
Not @overheat but how about [XTTS-v2](https://huggingface.co/coqui/XTTS-v2)?

**Comment by soupslurpr** [comment]
It would be great to see a permissive licensed TTS implemented in candle, preferably one that supports streaming and runs fast on mobile devices.
