### ISSUE TITLE
Discrepancy in NO_SPEECH_TOKENS constant between GitHub and crates.io versions

### ISSUE THREAD

**Issue by edesalve** [huggingface/candle#1431]
**candle-transformers 0.3.1**

The `NO_SPEECH_TOKENS` constant in the `candle_transformers::models::whisper` module as defined in the GitHub repository is:

```rust
pub const NO_SPEECH_TOKENS: [&str; 2] = ["<|nocaptions|>", "<|nospeech|>"];
```

When importing candle-transformers from crates.io, the definition differs, as shown:

```rust
pub const NO_SPEECH_TOKEN: &str = "<|nocaptions|>";
```

This discrepancy leads to a mismatch with the GitHub version and affects the whisper example in candle-examples.

**Comment by LaurentMazare** [comment]
This will be solved the next time we release the crate, hopefully when I'm back from neurips.

**Comment by LaurentMazare** [comment]
Version `0.3.2` of the crate has been released a couple days back so this should hopefully be fixed now. Feel free to re-open if not the case.
