### ISSUE TITLE
How to do to quantize manually a phi-2 version, starting from safetensors file

### ISSUE THREAD

**Issue by fcn94** [huggingface/candle#1457]
Hi

I have fine tuned a phi-2 model using lora

I merged adapter with base model to get a trained one

I now have a bunch of safetensors file

How is it possible to convert these files into a gguf file ( llama.cpp concerter does not support phi)

In other words, how is it possible to achieve the same as :  model-v2-q4k.gguf in lmz/candle-quantized-phi

**Comment by LaurentMazare** [comment]
You can try something like the following. The `tensor-tools` binary contains various tools for manipulating tensor files including quantizing them.
```bash
cargo run --example tensor-tools --release -- quantize --quantization q4k model.safetensors /tmp/model.gguf
```

**Comment by fcn94** [comment]
That was fast. Thank for the answer. I will try

**Comment by fcn94** [comment]
Seems to work OK. Thanks again
