### ISSUE TITLE
from_gguf only supports CPU?

### ISSUE THREAD

**Issue by sparqyeti** [huggingface/candle#1486]
creating a quantized var builder is done with the code below:
in file: candle-transformers/src/quantized_var_builder.rs
```
impl VarBuilder {
    pub fn from_gguf<P: AsRef<std::path::Path>>(p: P) -> Result<Self> {
        let mut file = std::fs::File::open(p)?;
        let content = candle::quantized::gguf_file::Content::read(&mut file)?;
        let mut data = std::collections::HashMap::new();
        for tensor_name in content.tensor_infos.keys() {
            let tensor = content.tensor(&mut file, tensor_name)?;
            data.insert(tensor_name.to_string(), Arc::new(tensor));
        }
        Ok(Self {
            data: Arc::new(data),
            path: Vec::new(),
            device: Device::Cpu,
        })
    }
```
this implies GGUF only supports CPU and not GPU? Am I missing something is this actually a constraint.

**Comment by LaurentMazare** [comment]
Yes, quantized tensors are only supported on cpu at the moment.

**Comment by danielclough** [comment]
## Related open issues

Support for quantisation: https://github.com/huggingface/candle/issues/359
CUDA support for QMatMul: https://github.com/huggingface/candle/issues/655
Error: no cuda implementation for qmatmul: https://github.com/huggingface/candle/issues/696
Quantized models on Cuda: https://github.com/huggingface/candle/issues/1250
You are here: https://github.com/huggingface/candle/issues/1486

**Comment by hubertshelley** [comment]
固定金属 : #1627

**Comment by LaurentMazare** [comment]
Closing this now in favor of #1250 , #1754 should also help with cuda support.
