### ISSUE TITLE
Strange Error when trying to use gguf files ( not generated by tensor-tools)

### ISSUE THREAD

**Issue by fcn94** [huggingface/candle#1510]
I adapted the example below , and I tried to use a different gguf model
https://github.com/huggingface/candle/blob/main/candle-examples/examples/mistral/main.rs

My adapted example works well with 
**model-q4k.gguf** located in **lmz/candle-mistral**
and also with a model I fine tuned , and transformed into gguf using **tensor_tools** from candle

But when I wanted to use another gguf file from a popular repo in huggingface , like thebloke , I ended up with the below error ( That I did not have time yet to investigate) :
**_called `Result::unwrap()` on an `Err` value: cannot find tensor weight_**

For example, I tried to use :
Repo of Mistral quantized model : TheBloke/Mistral-7B-Instruct-v0.2-GGUF
Quantized file : mistral-7b-instruct-v0.2.Q4_K_M.gguf
Repo of tokenizer.json : mistralai/Mistral-7B-Instruct-v0.2

Has anybody faced this same issue yet ?

**Comment by LaurentMazare** [comment]
The `gguf` files that are not generated by `tensor-tools` are generally to be used with the `quantized` example rather than the `mistral` or `llama` ones.
E.g.:
```bash
cargo run --example quantized --release  -- --prompt " " --model foo.gguf --tokenizer tokenizer.json
```

**Comment by fcn94** [comment]
Oh. I see.
Thanks for fast response

**Comment by fcn94** [comment]
All clear
