### ISSUE TITLE
[Examples] yi running with gpu enabled gives an error loading function: "Function 'cast_bf16_f32' does not exist"

### ISSUE THREAD

**Issue by fankaiLiu** [huggingface/candle#1532]
**Describe the bug**
yi running with gpu enabled gives an error loading function: "Function 'cast_bf16_f32' does not exist"
**To Reproduce**
1. cargo run --release --features metal  --example yi -- --prompt "hi"

**Expected behavior**
Normal Output Results

**Screenshots**
``` shell
avx: false, neon: true, simd128: false, f16c: false
temp: 0.00 repeat-penalty: 1.10 repeat-last-n: 64
retrieved the files in 583ns
Error: Metal error Error while loading function: "Function 'cast_bf16_f32' does not exist"
```
**Desktop (please complete the following information):**
 - OS: mac,m1
 - Version:latest main

**Additional context**
It works fine with just the cpu.

**Comment by ltouati** [comment]
I think PR #1524 need to be merged to support Metal inference of models that use Bf16

**Comment by ivarflakstad** [comment]
`cast_bf16_f32` already exists [here](https://github.com/huggingface/candle/blob/main/candle-metal-kernels/src/cast.metal#L61-L64), which begs the question - does your computer have metal version > 3.10?
You can run `xcrun metal --version` to check 😊

I'm downloading the model for the example now (slow connection). I'll report back if it runs on my machine 👍

**Comment by fankaiLiu** [comment]
> `cast_bf16_f32` already exists [here](https://github.com/huggingface/candle/blob/main/candle-metal-kernels/src/cast.metal#L61-L64), which begs the question - does your computer have metal version > 3.10? You can run `xcrun metal --version` to check 😊
> 
> I'm downloading the model for the example now (slow connection). I'll report back if it runs on my machine 👍
> 
> Edit: I do not get the error reported above, so it should be related to the metal version.

Thanks for the validation!
here is the result of my execution of xcrun metal --version, it looks to be version 3.10 or higher, but unfortunately I still get the message that the function in question can't be found when I run it.
```  shell
xcrun metal --version                                                 
Apple metal version 31001.720 (metalfe-31001.720.3)
Target: air64-apple-darwin23.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/bin
```

cargo run --release --features metal  --example yi -- --prompt "hi"
``` shell
Error: Metal error Error while loading function: "Function 'cast_bf16_f32' does not exist"

Caused by:
    Error while loading function: "Function 'cast_bf16_f32' does not exist"
```

**Comment by ivarflakstad** [comment]
@fankaiLiu try this branch:
https://github.com/huggingface/candle/pull/1540

**Comment by fankaiLiu** [comment]
> @fankaiLiu try this branch: #1540
> 
> Note that It may not run correctly, but if it loads then this bug can be closed (on merge)

``` shell
git branch
* ivarflakstad/metal-better-bfloat-capability-check
```
I switched branches and
1. run `cargo clean`
2. run `cargo run --release --features metal  --example yi -- --prompt "你好" `

Still getting the same error, is it because there is a cache somewhere? It looks like the latest code update didn't take effect?
``` shell
avx: false, neon: true, simd128: false, f16c: false
temp: 0.00 repeat-penalty: 1.10 repeat-last-n: 64
retrieved the files in 167ns
Error: Metal error Error while loading function: "Function 'cast_bf16_f32' does not exist"

Caused by:
    Error while loading function: "Function 'cast_bf16_f32' does not exist"
```
I seem to be the only one running with this issue, so if it is determined that this is a rare and isolated occurrence, please close this issue.

**Comment by ivarflakstad** [comment]
I think you just don't have bfloat support on your machine unfortunately. Get any results from this?
`grep -R bfloat /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/`

**Comment by fankaiLiu** [comment]
> I think you just don't have bfloat support on your machine unfortunately. Get any results from this? `grep -R bfloat /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/`

Okay, I run this command, but there is no outputIt looks like the update didn't work?

**Comment by ivarflakstad** [comment]
Looks like you don't have bfloat. Mlx does a decent job of simulating bfloat on the gpu if you want to try that.

**Comment by fankaiLiu** [comment]
> Looks like you don't have bfloat. Mlx does a decent job of simulating bfloat on the gpu if you want to try that.

Thanks for the suggestion, I installed mlx using pip install mlx but it's not working yet, is there a step I'm missing?

**Comment by ivarflakstad** [comment]
mlx is not related to candle. I am suggesting it as an alternative since your GPU does not support bfloat.

**Comment by fankaiLiu** [comment]
Thanks for the reply, it should be that my GPU is not supported, I'll turn off this issue

**Comment by Narsil** [comment]
@fankaiLiu usually models that can run on bfloat can also run on f16. Maybe just try to cast the model into F16 and see how this goes ?

**Comment by fankaiLiu** [comment]
> @fankaiLiu usually models that can run on bfloat can also run on f16. Maybe just try to cast the model into F16 and see how this goes ?

I changed
``` rust
    let dtype = if device.is_cuda() {
        DType::BF16
    } else {
        DType::F32
    };
```
to
``` rust
    let dtype = DType::BF16; 
```
But I get an error.
``` shell
avx: false, neon: true, simd128: false, f16c: false
temp: 0.00 repeat-penalty: 1.10 repeat-last-n: 64
retrieved the files in 208ns
Error: Metal error Error while loading function: "Function 'cast_f32_bf16' does not exist"

Caused by:
    Error while loading function: "Function 'cast_f32_bf16' does not exist"
```

**Comment by Narsil** [comment]
```rust
    let dtype = DType::F16; 
```

**Comment by LaurentMazare** [comment]
Fwiw `F32` is usually a far better default when trying out a `BF16` model as it has the exact same range, using `F16` make it quite possible to run into some nan/inf issues, the only advantage I would see is speed if your hardware supports it at 2x the speed of `F32`.

**Comment by fankaiLiu** [comment]
> ```rust
>     let dtype = DType::F16; 
> ```
I try ,but
``` shell
avx: false, neon: true, simd128: false, f16c: false
temp: 0.00 repeat-penalty: 1.10 repeat-last-n: 64
retrieved the files in 167ns
Error: Metal contiguous to_dtype BF16 F16 not implemented
```
