### ISSUE TITLE
NLL cause unclear failure

### ISSUE THREAD

**Issue by BDUG** [huggingface/candle#1539]
Why does the following code cause "unsupported dtype F32 for op gather"? 

    let x: [[f32; 1]; 2] = [ [2.6263], [1.1000] ];
    let y: [u32; 2] = [8, 5];

    let a = Tensor::new(&x, &dev).unwrap();
    let b = Tensor::new(&y, &dev).unwrap();

    let rst = candle_nn::loss::nll(&a, &b);

In addition the following should also work, or?
    let x: [f32; 12] = [ 2.6263, 1.1000];
    let y: [u32; 2] = [8, 5];

    let a = Tensor::new(&x, &dev).unwrap();
    let b = Tensor::new(&y, &dev).unwrap();

    let rst = candle_nn::loss::nll(&a, &b);

**Comment by LaurentMazare** [comment]
The following example based on your snippet worked fine for me. Maybe you're using a different device or optimization level that triggers the issue but note that it doesn't make sense to have values in the second argument which index is out of bounds for the first argument for such a nll loss.
```rust
use candle::{DType, Device, Result, Tensor};

fn main() -> Result<()> {
    let x: [[f32; 1]; 2] = [[2.6263], [1.1000]];
    let y: [u32; 2] = [8, 5];

    let dev = Device::Cpu;
    let a = Tensor::new(&x, &dev).unwrap();
    let b = Tensor::new(&y, &dev).unwrap();

    let rst = candle_nn::loss::nll(&a, &b);
    Ok(())
}
```
