### ISSUE TITLE
[QUESTION] Getting error when running Phi-2 on Metal

### ISSUE THREAD

**Issue by sebasarango1180** [huggingface/candle#1547]
Hi, got this error message after trying to run Phi-2 on my local machine (Apple M1 Pro - 16 GB):

```bash
cargo run --example phi --release --features metal -- --model 2 --prompt "Write a Python function that sorts each word of a string by their number of occurrences:"
    Finished release [optimized] target(s) in 0.15s
     Running `target/release/examples/phi --model 2 --prompt 'Write a Python function that sorts each word of a string by their number of occurrences:'`
avx: false, neon: true, simd128: false, f16c: false
temp: 0.00 repeat-penalty: 1.10 repeat-last-n: 64
retrieved the files in 12.749292ms
Error: Metal error Error while loading function: "error: air version set to 2.5.0 (!9 = !{i32 2, i32 5, i32 0}), but expecting 2.4 in \n"
```

I'm new to Rust and Cargo so not sure what might be going on here. I wasn't even able to find the "air"module. However this does run on CPU as expected (really slow though).

Thanks for any help!

**Comment by ivarflakstad** [comment]
This is actually only related to Metal, not Rust or Cargo.
Air is the intermediate representation for Metal (Apple Intermediate Representation).
I think I know what the cause is, but I don't know if it is something that's easy to fix or not.

It's a bit strange though. I have an M1 pro 32 GB and it runs fine 🤷

**Comment by jmviz** [comment]
I ran into this in my own project trying to run on Metal with several different sentence-transformers BERT models, so it's not specific to this example. But I can confirm I also get the same error on the above Phi-2 example. Also on an M1 Pro 16GB.

**Comment by sebasarango1180** [comment]
FYI - managed to solve it by upgrading my MacOS version. It was at Monterrey 12.7 and suddenly, after bumping it to Sonoma 14.2, the issue disappeared. Not sure if this can be considered a general way of fixing it though.

**Comment by ivarflakstad** [comment]
I'm fairly confident updating your MacOS is the solution. At least for now.

The metal lib we are using ([mfa](https://github.com/philipturner/metal-flash-attention)) for gemm is the fastest that exists, but it has slightly stricter requirements than for example MPS.
Skipping details: you need to have metal/air versions that are compatible with Xcode 14.2 or later.

I want to fall back to MPS if we can't use mfa, but there is (at least was) a bug on the M3 arch.
Maybe I'll have time to look into it this weekend.

**Comment by ivarflakstad** [comment]
According to the [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14_2-release-notes) for Xcode 14.2 it requires macOS >= Monterey 12.5 (you would have to update xcode) or simply update your macOS to >= Ventura 13.1

**Comment by jmviz** [comment]
Thank you! I can confirm that upgrading from Monterrey 12.7 to Sonoma 14.2 worked for me as well.
