### ISSUE TITLE
Support for RWKV/v5-Eagle

### ISSUE THREAD

**Issue by okpatil4u** [huggingface/candle#1633]
Given the launch for eagle-7b model, is it worth adding it to the default examples ?

https://blog.rwkv.com/p/eagle-7b-soaring-past-transformers

It would be a nice example to have.

**Comment by LaurentMazare** [comment]
This has been added as an example [here](https://github.com/huggingface/candle/tree/main/candle-examples/examples/rwkv).

**Comment by okpatil4u** [comment]
Thank you Laurent !
