### ISSUE TITLE
Why does the imagenet example crop the image?

### ISSUE THREAD

**Issue by soupslurpr** [huggingface/candle#1708]
Why does the candle imagenet example crop the image using resize_to_fill() instead of stretching it using resize_exact()? I'd like the model to be able to see the full image and was wondering if using resize_exact() would be okay or if there is a reason for using resize_to_fill().

**Comment by LaurentMazare** [comment]
The problem with a pure resize is distortion if one axis has too stretch more than the other. I'm afraid there is no perfect solution here, you have to pick between distortion, cropping (so removing a part of the original image), or padding.

**Comment by soupslurpr** [comment]
I see, that makes sense. Another solution is maybe distorting up to a certain amount and after that splitting the image and running it through in multiple steps. It's problem specific tradeoff. Thanks.
