### ISSUE TITLE
Does candle supports offloading layers to gpu and remaining running on CPU ?

### ISSUE THREAD

**Issue by akhildevelops** [huggingface/candle#1714]
llama.cpp has a feature to offload some layers to gpu. Does candle also have some kind of similar feature ?

I've a GPU with 6GB VRAM and host is 16GB RAM and I can run models easily on CPU as I have sufficient RAM but slow. If I try to use GPU then app crashes. It would be helpful to offload 6GB of layers to GPU and run remaining on CPU.

**Comment by LaurentMazare** [comment]
Using candle you can select the device on which each of the tensors live so having some layers on GPU and some others on CPU is certainly doable. That said in our model library `candle-transformers`, we put usually everything on the same device for simplicity. If you want to experiment with this layer offloading, you can try to duplicate the model code from `candle-transformers` and adapt it the way you want, one of the design goal of `candle-transformers` is that the model code should be easy to transplant and tweak without having to drag a lot of dependencies.

**Comment by akhildevelops** [comment]
I believe this feature helps to run models on consumer grade laptops / desktops utilising most of the hardware. Curious to know the amount of development efforts needed to create this feature.  I’ll try to implement and check. Thanks 👍
