### ISSUE TITLE
Candle pickle produces wrong float number when parsing into Object::Float

### ISSUE THREAD

**Issue by antimora** [huggingface/candle#1729]
I'm integrating a configuration extractor into Burn, specifically designed to extract model configuration values from Whisper's `.pt` file. Luckily, Candle provides APIs capable of parsing `.pt` files, which has been instrumental for this feature. 

During the development of comprehensive tests for this new functionality, I encountered an issue with Candle's handling of float numbers in pickle files. To facilitate investigation and resolution of this problem, I'm providing a minimal reproducible example. You can find the necessary files to reproduce the bug in the following GitHub repository: [Minimal Reproducible Example for Candle Pickle Bug](https://github.com/huggingface/candle/files/14323251/bug.zip).

For convenience, I am also including the main file from the example in this description for a quicker overview.

```rust
use std::{fs::File, io::BufReader};

use candle_core::pickle::{Object, Stack};
use zip::ZipArchive;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Deserialize the config file to object
    let mut zip = ZipArchive::new(BufReader::new(File::open("config.pt")?))?;
    let data_pkl_path = "config/data.pkl";
    let reader = zip.by_name(&data_pkl_path)?;
    let mut reader = BufReader::new(reader);
    let mut stack = Stack::empty();
    stack.read_loop(&mut reader)?;
    let obj = stack.finalize()?;

    println!("{obj:#?}");

    match obj {
        Object::Dict(key_values) => {
            for (_, value) in key_values {
                match value {
                    Object::Bool(v) => assert_eq!(v, true),
                    Object::Int(v) => assert_eq!(v, 1),
                    Object::Unicode(v) => assert_eq!(v, "hello"),
                    Object::Float(v) => assert_eq!(v, 0.1), // FAILS HERE
                    _ => unreachable!("unexpected object type"),
                }
            }
        }
        _ => unreachable!("unexpected object type"),
    }
    Ok(())
}
```

Output:

```
Dict(
    [
        (
            Unicode(
                "some_str",
            ),
            Unicode(
                "hello",
            ),
        ),
        (
            Unicode(
                "some_bool",
            ),
            Bool(
                true,
            ),
        ),
        (
            Unicode(
                "some_int",
            ),
            Int(
                1,
            ),
        ),
        (
            Unicode(
                "some_float",
            ),
            Float(
                -1.5423487136675799e-180,
            ),
        ),
    ],
)
thread 'main' panicked at src/main.rs:25:41:
assertion `left == right` failed
  left: -1.5423487136675799e-180
 right: 0.1
```

**Comment by LaurentMazare** [comment]
Thanks for reporting this and for the very easy to use repro, that's very helpful!
Somehow floats in pickle are encoded using big-endian whereas I assumed little-endian (as is the case for ints), so this is certainly a bug on our side that should be fixed in #1730 .
Also not sure what your pickle configuration extractor does, in candle we're more leaning towards using safetensor+json for the configs as it's somewhat the standard on the huggingface hub but if you think such an exctractor would make sense on the candle side too, certainly happy to discuss it!

**Comment by antimora** [comment]
@LaurentMazare, thank you for the quick fix! I appreciate your attention to this matter.

I am currently working on importing the OpenAI Whisper model. As you are aware, OpenAI exports the weights and model configuration in a `.pt` file (see [model dimension loading lines](https://github.com/openai/whisper/blob/main/whisper/__init__.py#L149)).

Thanks to your work with the PyTorch `.pt` file and enhancements to Burn, we can now import weights. However, I am now working on enhancing Burn to deserialize configuration values using serde. See my recent PR on how I utilized Candle: https://github.com/tracel-ai/burn/pull/1323.

Candle also could be enhanced with a simple Serde deserializer that deserializes `Object` values. With this, one could use `dims` from Whisper `pt` file.

**Comment by antimora** [comment]
I have tested your solution and I can confirm it's fixed.
