### ISSUE TITLE
Poor generation when using quantised models on cuda

### ISSUE THREAD

**Issue by LaurentMazare** [huggingface/candle#1765]
_Originally posted by @akhildevelops in https://github.com/huggingface/candle/issues/1754#issuecomment-1965815906_
            
Tried hands-on and below are the results from cuda (gpu) and mkl (cpu) by running a 4bit wuantized 7b mistral model. The prompt was: `Who created you ?`

Cuda:
```shell
cargo run --example quantized --release --features cuda -- --which 7b-mistral-instruct-v0.2 --prompt "<s>[INST]Who created you ?[/INST]" --seed 87654
    Finished release [optimized] target(s) in 0.21s
     Running `target/release/examples/quantized --which 7b-mistral-instruct-v0.2 --prompt '<s>[INST]Who created you ?[/INST]' --seed 87654`
avx: true, neon: false, simd128: false, f16c: true
temp: 0.80 repeat-penalty: 1.10 repeat-last-n: 64
loaded 291 tensors (4.14GB) in 0.15s
model built
<s>[INST]Who created you ?[/INST]Additional Information:

**Company Name:** Acurify Solutions Corp.

**Address:** 123 Main Street, Suite 400, Anytown, USA

**Email:** info@acurifysol.com

**Phone:** 555-555-5555

**Year Founded:** 2018

**Website:** www.acurifysol.com

Acurify Solutions Corp. is a technology consulting firm that was founded in 2018 by a team of experienced professionals with a passion for delivering exceptional results to their clients. Our mission is to help businesses improve their operations and increase their efficiency through the innovative use of technology solutions. We specialize in cloud computing, data analytics, and software development services. Our team of experts have extensive experience working with leading technologies such as Microsoft Azure, Amazon Web Services (AWS), and Google Cloud Platform (GCP).

At Acurify Solutions Corp., we believe that every business is unique, which is why we offer customized solutions tailored to our clients' specific needs. We take a collaborative approach to working with our clients, ensuring that we fully understand their goals and challenges before providing recommendations and implementing solutions. Our team of experts will work closely with your team to ensure a seamless transition and maximum value from your technology investment.

Contact us today to learn more about how Acurify Solutions Corp. can help your business achieve its full potential through innovative technology solutions.

**Services:**

- Cloud Computing Consulting & Migration
- Data Analytics & Business Intelligence
- Software Development
  - Web Applications
  - Mobile Applications
  - Custom Applications
- Technical Support & Managed Services

**Technologies:**

- Microsoft Azure: A comprehensive set of cloud services that allows businesses to build, deploy, and manage applications through the Microsoft Azure platform.
- Amazon Web Services (AWS): A secure cloud services platform offering computing power, storage, databases, and various functionalities required for modern application development.
- Google Cloud Platform (GCP): A suite of cloud computing services that allows businesses to create, deploy, and manage applications, websites, and services in a flexible infrastructure.

  13 prompt tokens processed: 19.33 token/s
 482 tokens generated: 20.24 token/s
```

CPU:
```shell
cargo run --example quantized --release --features mkl -- --which 7b-mistral-instruct-v0.2 --prompt "<s>[INST]Who created you ?[/INST]" --seed 87654    
    Finished release [optimized] target(s) in 0.17s
     Running `target/release/examples/quantized --which 7b-mistral-instruct-v0.2 --prompt '<s>[INST]Who created you ?[/INST]' --seed 87654`
avx: true, neon: false, simd128: false, f16c: true
temp: 0.80 repeat-penalty: 1.10 repeat-last-n: 64
Running on CPU, to run on GPU, build this example with `--features cuda`
loaded 291 tensors (4.14GB) in 0.04s
model built
<s>[INST]Who created you ?[/INST]I was created by Mistral AI. I'm an artificial intelligence language model designed to generate human-like text based on the data I was trained on. I don't have a physical form or the ability to create other entities. I exist purely as a program running on computer servers.

  13 prompt tokens processed: 7.76 token/s
  59 tokens generated: 5.83 token/s
```
CPU was good and Cuda performed poor in generating response.

**Comment by LaurentMazare** [comment]
Thanks for reporting this issue, I agree that there is certainly something going wrong here though I haven't been to the bottom of it. I've added a `--split-prompt` flag to the example in #1766 that makes it possible to process the prompt incrementally rather than as a whole and with this the generated text is far more on par with the cpu version. I'll have to do a bit more digging to find what's wrong here.

Also #1725 might be related.

**Comment by ltouati** [comment]
Hi Team, 

I think there's also something else to look at regarding this work. 

When looking at `candle-core/tests/quantized_tests.rs` if we deactivate this statement
```
// TODO Enable this later when we enable cuda.
    if device.is_cuda() {
        return Ok(());
    }

``` 

Then a some k tests are failing, which I think may explain why we see incorrect results

**Comment by ltouati** [comment]
Digging into the code, I think the issue might be to the parameters we pass to the kernel. For example to have the Q2_K test passing, I changed from 
```
let nb = (elem_count + 255) / 256;
    let cfg = cudarc::driver::LaunchConfig {
        grid_dim: (nb as u32, 1, 1),
        block_dim: (32, 1, 1),
        shared_mem_bytes: 0,
    };
```
in candle-core/src/quantized/cuda.rs:44
to
```
let nb = (elem_count / 64)
    let cfg = cudarc::driver::LaunchConfig {
        grid_dim: (nb as u32, 1, 1),
        block_dim: (64, 1, 1),
        shared_mem_bytes: 0,
    };
```

**Comment by LaurentMazare** [comment]
> Digging into the code, I think the issue might be to the parameters we pass to the kernel. For example to have the Q2_K test passing, I changed from

Nice find, the issue indeed seems related to the number of blocks, turn out it's not the same for q4k (32) than for q2k, q3k, q5k, and q6k, I've fixed it in #1767 with a pointer to the original code for more details.
This also seems to fix the generation issue, most likely because of the last layer being encoded in q6k and the path for the prompt handling being different from the streaming path and using the broken dequantize logic.

**Comment by ltouati** [comment]
Did some testing, and it works just fine for me. I think however there's a performance hotspot 
<img width="1543" alt="Capture d’écran 2024-02-27 à 18 28 27" src="https://github.com/huggingface/candle/assets/577776/cf791a8e-49d5-4db8-881d-42b1733505e1">


Looks like we're spending a disproportionate amount of time in `candle-transformers/src/models/quantized_llama.rs:masked_fill` as we're constantly copying data from the CPU to the GPU.

**Comment by LaurentMazare** [comment]
Wow, thanks (again) for looking into this and for running some profiling (it's probably obvious now that I haven't run any :) ), there is indeed an awful lot of copying to the gpu that takes place here and happens once per layer. I'll tweak that to stay entirely on the gpu side, it's fairly obvious to do and should indeed result in large speedups.

**Comment by LaurentMazare** [comment]
Also just wondering, was this done with `CUDA_LAUNCH_BLOCKING` or equivalent? If not that may not bring so much benefits as it's just a synchronisation point that would held the rest of the cuda streams behind. It's probably still a good idea to fix it though.

**Comment by ltouati** [comment]
My pleasure, thx a lot for putting so much energy into this. 

What I find very bizarre (and forget my ignorance), it that it looks like we're creating a 1D array of 1 with -inf as a value to put it in a [1,32,17,17], IMHO this should be an instance variable stored on the GPU.

**Comment by LaurentMazare** [comment]
Fixed in #1770 , this seems to have an impact on prompt processing but not much after that (we could actually disable the mask during the autoregressive process to avoid the whole operation altogether).

**Comment by ltouati** [comment]
It did not change much, as probably the GPU was busy doing something else. 

Here's a new profiling tree

<img width="1514" alt="Capture d’écran 2024-02-27 à 20 22 02" src="https://github.com/huggingface/candle/assets/577776/066cffc7-0ee9-45fc-9d58-a43a2debd6b0">

A large part comes once again from data copy (this time from GPU to CPU) 
`candle-core/src/tensor.rs:to_vec1`

**Comment by LaurentMazare** [comment]
This is probably expected and I don't think it tells us much about where the time is actually spent. The cuda api is lazy by default so all the time is spent when gather the results or on actual synchronisation points. You can either set `CUDA_LAUNCH_BLOCKING` to avoid this and get a more informed profile, or better use `nvsys` to see where the time is really spent at the kernel level on the gpu using the async calls.

**Comment by LaurentMazare** [comment]
Closing as the original issue has been fixed.
