### ISSUE TITLE
[Question] How to modify Mistral to enable multiple batches?

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#1769]
Hello everybody,

I am attempting to implement multiple batches for the Mistral forward pass. However, the `forward` method takes an argument `seqlen_offset` which seems to be specific to the batch. I have attempted to implement it with a `position_ids` tensor in [this](https://github.com/EricLBuehler/mistral.rs/blob/mistralrunner/mistralrs-core/src/models/mistral.rs) file. 
Specifically, I rewrote the rotary embedding function:
```rust
fn apply_rotary_emb_qkv(
    &self,
    q: &Tensor,
    k: &Tensor,
    position_ids: &Tensor,
) -> Result<(Tensor, Tensor)> {
    let cos = self.cos.i(position_ids)?;
    let sin = self.sin.i(position_ids)?;

    let q_embed = (q.broadcast_mul(&cos)? + rotate_half(q)?.broadcast_mul(&sin))?;
    let k_embed = (k.broadcast_mul(&cos)? + rotate_half(k)?.broadcast_mul(&sin))?;
    Ok((q_embed, k_embed))
}
```
I create the position ids with the following line:
```rust
let position_ids = Tensor::arange(
    past_key_values_length as i64,
    (past_key_values_length + seq_len) as i64,
    input_ids.device(),
)?;
```
With `past_key_values_length` as the result of
```rust
fn calculate_past_kv_len(&self, seq_len: usize) -> Result<usize> {
    let kv_cache_1 = &self.layers.first().as_ref().unwrap().self_attn.kv_cache;
    if kv_cache_1.is_none() {
        return Ok(0);
    }
    let k_cache_1 = &kv_cache_1.as_ref().unwrap().0;
    if k_cache_1.dims()[0] <= seq_len {
        Ok(0)
    } else {
        let indexed = k_cache_1.i(seq_len)?;
        let dims = indexed.dims();
        Ok(dims[dims.len() - 2])
    }
}
```
My implementation attempts to follow the [transformers implementation of calculating position ids](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mistral/modeling_mistral.py#L977-L985) and for the [implementation of `apply_rotary_emb_qkv`](https://github.com/huggingface/transformers/blob/5c341d4555ba3e4b656053317e372ebed0c5af37/src/transformers/models/mistral/modeling_mistral.py#L139-L164). However, when I copy and run the candle-examples inference script, with the only change being that I do not pass the `seqlen_offset` variable, it does not produce coherent output. While the model runs, it does not "work".

How can I implement multiple-batch forward passes? Is there a way to do it using the `seqlen_offset` variable? Thank you for any help.

**Comment by LaurentMazare** [comment]
The usual thing I would do is print the tensors on the python side and on the rust side at different points of the forward step to find out where they start being different and then check out why this is the case. The candle tensor display format is actually very close to the pytorch one, and this has been done on purpose so that it's easier to debug discrepancies.

**Comment by EricLBuehler** [comment]
Thank you, this had been implemented.
