### ISSUE TITLE
tensor `sign` operator

### ISSUE THREAD

**Issue by antimora** [huggingface/candle#1827]
This operator extracts the signs of the elements of input tensor. The behavior is the same as [PyTorch's sign operator.](https://pytorch.org/docs/stable/generated/torch.sign.html)

**Comment by LaurentMazare** [comment]
What about using a `CustomOp` for this on your side? This should be fairly straightforward to add for such unary ops, e.g. you can see an example in [this test](https://github.com/huggingface/candle/blob/754fa1e8134dd78c841c936eca746de9408e9ea7/candle-core/tests/custom_op_tests.rs#L19-L33).

**Comment by antimora** [comment]
> What about using a `CustomOp` for this on your side? This should be fairly straightforward to add for such unary ops, e.g. you can see an example in [this test](https://github.com/huggingface/candle/blob/754fa1e8134dd78c841c936eca746de9408e9ea7/candle-core/tests/custom_op_tests.rs#L19-L33).

The example you referenced is the CPU implementation. Is it possible to do the same for CUDA?

Currently, on the Burn side, the Candle backend uses a default implementation in terms of other ops, which work for CUDA, I suppose: 

```rust
    fn float_sign<const D: usize>(tensor: FloatTensor<B, D>) -> FloatTensor<B, D> {
        let zeros = B::float_zeros(B::float_shape(&tensor), &B::float_device(&tensor));
        let less_than_zero = B::float_lower_elem(tensor.clone(), 0.0f32.elem());
        let greater_than_zero = B::float_greater_elem(tensor, 0.0f32.elem());

        let mut result = B::float_mask_fill(zeros, less_than_zero, (-1.0f32).elem());
        result = B::float_mask_fill(result, greater_than_zero, 1.0f32.elem());
        result
    }
```

**Comment by LaurentMazare** [comment]
Related PR: #2012 it ended up not being a custom op but would certainly have worked for cuda/metal/etc support.

**Comment by antimora** [comment]
Closing since the PR is merged. Thank you!
