### ISSUE TITLE
Severe performance drop on WSL vs pure-Linux, but same GPU type

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#1829]
Hello all,

I am developing [mistral.rs](https://github.com/EricLBuehler/mistral.rs.git), an LLM inference platform. When running on a pure-Linux A6000 instance, I get 60-70 T/s and while running `llama.cpp` I get 50-60 T/s. However, when using my local WSL A6000, I only get 20 T/s while `llama.cpp` maintains 50-60 T/s. Therefore, I think it rules out hardware differences and implies it is a software/build issue.

When I checked that `nvcc` and `nvidia-smi` have the same version, `nvcc` was 11.8 and `nvidia-smi` 12.2. I thought this was a problem and updated $PATH so that `nvcc` was 12.1. However, this did not affect the abnormally slow speed.

Are there other steps that I can take to ensure the correct versions are used during build? Thank you for any help.

**Comment by LaurentMazare** [comment]
I would suggest trying to replicate the issue outside of candle if possible, e.g. with doing some matmul benchmarks using cudarc. This will make it clear whether the issue comes from candle or a layer underneath.

**Comment by EricLBuehler** [comment]
I will try to do that. In the meantime, I spun up a Docker instance on the machine which exhibits slow `mistral.rs` performance, and it gave the expected T/s. This seems to corroborate the idea that it is a driver issue related to WSL. Do you have any thoughts on what I could do to check that it is using the correct CUDA framework?
