### ISSUE TITLE
Yolo-v8 Mac M1 Error: Metal max_pool2d not implemented

### ISSUE THREAD

**Issue by oddpxl** [huggingface/candle#1838]
Yolo-v8 example compiled with

cargo build --example yolo-v8 -r --features metal

Unless run on CPU you get Error: Metal max_pool2d not implemented

**Comment by LaurentMazare** [comment]
Adding @ivarflakstad explicitely, would be great to add the missing metal kernels (also noticed that conv-transpose1d is missing).

**Comment by LaurentMazare** [comment]
The missing metal kernel has been added by @tomsanbear in #1863 so hopefully should work well now.
