### ISSUE TITLE
How to properly implement PT to safetensors conversion

### ISSUE THREAD

**Issue by EHW-liao** [huggingface/candle#1878]
Use the *pt format weight file obtained by pytorch training. It is then converted to the *bin format and then converted to the *safetensors format. Error message is reported in candle yolov8 with error message
Error: cannot find tensor net.b.1.0.bn.running_mean

**Comment by masc-it** [comment]
@EHW-liao how did you solved? same error here

**Comment by EHW-liao** [comment]
你好你的邮件我已收到。                                             廖海鹏
