### ISSUE TITLE
unrecognized feature for crate candle-core: metal

### ISSUE THREAD

**Issue by Chaofan34** [huggingface/candle#1889]
i want to install candle-core with metal features use command:
`cargo add --git https://github.com/huggingface/candle.git candle-core --features "metal"`

but get error message:
`error: unrecognized feature for crate candle-core: metal`

machine:  mac mini( M2 )

**Comment by LaurentMazare** [comment]
There are other reports of `cargo add` being flaky when using the `--features` flag, maybe you could just try adding it manually to your `Cargo.toml` file.

**Comment by Chaofan34** [comment]
> There are other reports of `cargo add` being flaky when using the `--features` flag, maybe you could just try adding it manually to your `Cargo.toml` file.

adding features manually to cargo.toml can fix this problem, 
`[dependencies]
anyhow = "1.0.75"
candle-core = { version = "0.4.1", features=["metal"] }
candle-transformers = {version = "0.4.1", features=["metal"]}`
