### ISSUE TITLE
no method named `data` found for struct `image::Rgb` in the current scope method not found in `Rgb<u8>`

### ISSUE THREAD

**Issue by jefftantan** [huggingface/candle#1891]
mask = mask
        .iter()
        .flat_map(|x| label_colors[x].data())
        .collect::<Vec<u8>>();

no method named `data` found for struct `image::Rgb` in the current scope
method not found in `Rgb<u8>`

**Comment by LaurentMazare** [comment]
That's odd, it may be a discrepancy between the `image` and the `imageproc` crates somehow. I've updated both crates in the main candle repo + hopefully made them more tightely linked by using the `image` re-export in `imageproc` in #1893 Let me know if this is still an issue.

**Comment by jefftantan** [comment]
Resolve the issue by the following method:
let mask = mask.iter()
              .flat_map(|x| label_colors[x].0.to_vec())
              .collect::<Vec<u8>>();
