### ISSUE TITLE
nvcc error while compiling "src/quantized.cu"

### ISSUE THREAD

**Issue by lijing5227** [huggingface/candle#1902]
cargo build --release --features cuda
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0

<img width="1068" alt="image" src="https://github.com/huggingface/candle/assets/20733031/88fb1e7b-edb3-468c-b72b-1afd6655c474">

src/quantized.cu(194): error: too many initializer values
    static_assert(sizeof(block_q4_K) == 2*sizeof(ggml_fp16_t) + 3*256/64 + 256/2, "wrong q4_K block size/padding");
                                                                                  ^

  src/quantized.cu(214): error: this declaration has no storage class or type specifier
    static_assert(sizeof(block_q5_K) == 2*sizeof(ggml_fp16_t) + 12 + 256/2 + 256/8, "wrong q5_K block size/padding");
    ^

  src/quantized.cu(214): error: variable "static_assert" has already been defined
    static_assert(sizeof(block_q5_K) == 2*sizeof(ggml_fp16_t) + 12 + 256/2 + 256/8, "wrong q5_K block size/padding");
    ^

  src/quantized.cu(214): error: too many initializer values
    static_assert(sizeof(block_q5_K) == 2*sizeof(ggml_fp16_t) + 12 + 256/2 + 256/8, "wrong q5_K block size/padding");
                                                                                    ^

  src/quantized.cu(225): error: this declaration has no storage class or type specifier
    static_assert(sizeof(block_q6_K) == sizeof(ggml_fp16_t) + 13*256/16, "wrong q6_K block size/padding");
    ^

  src/quantized.cu(225): error: variable "static_assert" has already been defined
    static_assert(sizeof(block_q6_K) == sizeof(ggml_fp16_t) + 13*256/16, "wrong q6_K block size/padding");
    ^

  src/quantized.cu(225): error: too many initializer values
    static_assert(sizeof(block_q6_K) == sizeof(ggml_fp16_t) + 13*256/16, "wrong q6_K block size/padding");
                                                                         ^

  src/quantized.cu(233): error: this declaration has no storage class or type specifier
    static_assert(sizeof(block_q8_K) == sizeof(float) + 256 + 256/16*sizeof(int16_t), "wrong q8_K block size/padding");
    ^

  src/quantized.cu(233): error: variable "static_assert" has already been defined
    static_assert(sizeof(block_q8_K) == sizeof(float) + 256 + 256/16*sizeof(int16_t), "wrong q8_K block size/padding");
    ^

  src/quantized.cu(233): error: too many initializer values
    static_assert(sizeof(block_q8_K) == sizeof(float) + 256 + 256/16*sizeof(int16_t), "wrong q8_K block size/padding");
                                                                                      ^

  src/quantized.cu(457): error: a template argument may not reference a non-external entity
        mul_mat_q<32, 2, (32 / (4 * 2)), true, block_q4_0, mmq_x, mmq_y, nwarps, allocate_tiles_q4_0<mmq_y>,
        ^

  src/quantized.cu(457): error: a template argument may not reference a non-external entity
        mul_mat_q<32, 2, (32 / (4 * 2)), true, block_q4_0, mmq_x, mmq_y, nwarps, allocate_tiles_q4_0<mmq_y>,
        ^

  src/quantized.cu(457): error: a template argument may not reference a non-external entity
        mul_mat_q<32, 2, (32 / (4 * 2)), true, block_q4_0, mmq_x, mmq_y, nwarps, allocate_tiles_q4_0<mmq_y>,
        ^

  src/quantized.cu(469): error: a template argument may not reference a non-external entity
        mul_mat_q<32, 2, (32 / (4 * 2)), true, block_q4_0, mmq_x, mmq_y, nwarps, allocate_tiles_q4_0<mmq_y>,
        ^

  src/quantized.cu(469): error: a template argument may not reference a non-external entity
        mul_mat_q<32, 2, (32 / (4 * 2)), true, block_q4_0, mmq_x, mmq_y, nwarps, allocate_tiles_q4_0<mmq_y>,
        ^

  src/quantized.cu(469): error: a template argument may not reference a non-external entity
        mul_mat_q<32, 2, (32 / (4 * 2)), true, block_q4_0, mmq_x, mmq_y, nwarps, allocate_tiles_q4_0<mmq_y>,
        ^

  src/quantized.cu(983): error: a template argument may not reference a non-external entity
        dequantize_mul_mat_vec<32, 2, dequantize_q4_0>(vx, y, dst, ncols, nrows);
        ^

  src/quantized.cu(987): error: a template argument may not reference a non-external entity
        dequantize_mul_mat_vec<32, 2, dequantize_q4_1>(vx, y, dst, ncols, nrows);
        ^

  src/quantized.cu(991): error: a template argument may not reference a non-external entity
        dequantize_mul_mat_vec<32, 2, dequantize_q5_0>(vx, y, dst, ncols, nrows);
        ^

  src/quantized.cu(995): error: a template argument may not reference a non-external entity
        dequantize_mul_mat_vec<32, 2, dequantize_q5_1>(vx, y, dst, ncols, nrows);
        ^
  45 errors detected in the compilation of "src/quantized.cu".
  src/compatibility.cuh(58): warning #940-D: missing return statement at end of non-void function "atomicAdd(__half *, __half)"
    }

src/quantized.cu(1465): error: expression preceding parentheses of apparent call must have (pointer-to-) function type
        static_assert(16%2 == 0, "16 must be divisible by K_QUANTS_PER_ITERATION");
        ^
 src/quantized.cu(998): error: a template argument may not reference a non-external entity
        dequantize_mul_mat_vec<32, 1, dequantize_q8_0>(vx, y, dst, ncols, nrows);
        ^

**Comment by lijing5227** [comment]
lspci | grep -i nvidia
17:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1)
17:00.1 Audio device: NVIDIA Corporation GP102 HDMI Audio Controller (rev a1)
65:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1)
65:00.1 Audio device: NVIDIA Corporation GP102 HDMI Audio Controller (rev a1)

**Comment by vebodev** [comment]
@lijing5227 
I met the similar errors as yours, how did you fix it? Appreciate your advice.

**Comment by bryagd** [comment]
+1
