### ISSUE TITLE
The current `squeeze` and `unsqueeze` implementations may be degreasing in some EXAMPLES.

### ISSUE THREAD

**Issue by higumachan** [huggingface/candle#1942]
Similar #1905

In my environment `RUST_BACKTRACE=1 cargo run --example dinov2 --release -- --image . /candle-examples/examples/yolo-v8/assets/bike.jpg ` did not work.

<details><summary>Output</summary>
<p>

Running on CPU, to run on GPU(metal), build this example with `--features metal`
loaded image Tensor[dims 3, 224, 224; f32]
model built
Error: MatMulUnexpectedStriding { lhs_l: Layout { shape: [1, 6, 257, 64], stride: [98688, 16448, 64, 1], start_offset: 0 }, rhs_l: Layout { shape: [1, 6, 64, 257], stride: [296064, 64, 1, 1152], start_offset: 384 }, bmnk: (6, 257, 257, 64), msg: "non-contiguous rhs" }
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/backtrace.rs:331:13
   3: candle_core::error::Error::bt
   4: candle_core::cpu_backend::MatMul::striding_error
   5: <candle_core::cpu_backend::CpuStorage as candle_core::backend::BackendStorage>::matmul
   6: candle_core::storage::Storage::matmul
   7: candle_core::tensor::Tensor::matmul
   8: <candle_transformers::models::dinov2::Attention as candle_core::Module>::forward
   9: <candle_transformers::models::dinov2::Block as candle_core::Module>::forward
  10: <candle_transformers::models::dinov2::DinoVisionTransformer as candle_core::Module>::forward
  11: dinov2::main
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: std::rt::lang_start::{{closure}}
  14: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  15: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  16: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  17: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  18: std::rt::lang_start_internal::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  19: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  20: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  21: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  22: std::rt::lang_start_internal
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  23: _main

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/backtrace.rs:331:13
   3: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   4: dinov2::main
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: std::rt::lang_start::{{closure}}
   7: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
   8: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
   9: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  10: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  11: std::rt::lang_start_internal::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  12: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  13: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  14: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  15: std::rt::lang_start_internal
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  16: _main

</p>
</details> 

For this problem, I went looking for which commit was no longer executable using `git bisect`.

Then I found at this commit(https://github.com/huggingface/candle/commit/455c42aa729d8019fcb496106478e75dd3246c08)
As a test, I reverted the squeeze and unsqueeze implementations back to before this commit and now this example works.

https://github.com/huggingface/candle/pull/1906 may have solved some problems, but in this case it still doesn't seem to work, can I have it checked?

--- 

My environment

commit hash: 4523ecfb2a3a3690aa3b037a5a096354f2ca612b
runtime mode: cpu

OS: Mac OS 13.1（22C65）
CPU: Apple M1 Max

**Comment by LaurentMazare** [comment]
Indeed this was broken by the PR you mentioned, hopefully #1943 fixes it.

**Comment by higumachan** [comment]
@LaurentMazare Thanks a lot!
#1943 fixed it.
