### ISSUE TITLE
.sum() with a u8 tensor overflows after 255

### ISSUE THREAD

**Issue by michaeleisel** [huggingface/candle#1944]
When I call .sum() on a U8 tensor that should return 5,000, it instead returns 136 (5,000 % 256). It seems .sum() on a u8 tensor always returns a u8 tensor regardless of how big it gets. It would be great if it instead used a larger dtype as necessary. Code:
```
Tensor::ones(5000, DType::U32, default_device())?.eq(1u32)?.sum(0)?; // Returns a u8 tensor with 136
```

**Comment by LaurentMazare** [comment]
The thing is that almost all ops including `sum` return a tensor that has the same type as the original type. Having the returned tensor type depend on the values in the argument would feel a bit dodgy to me hence this wrapping around behavior. Maybe you could just do the casting on your side via a `.eq(1u32)?.to_dtype(DType::U32)?.sum(0)?`, this would have the benefit of being more explicit about what actually takes place.

**Comment by michaeleisel** [comment]
That solution is adequate for me, we can close this since it sounds like this is intended behavior

**Comment by michaeleisel** [comment]
One thing that'd be nice is to detect if overflows occur somehow, and crash if it happens. Perhaps this already occurs on the CPU? Would be nice to at least bring that behavior to the CPU if not, and ideally other devices too, at least for the most basic arithmetic kernels

**Comment by LaurentMazare** [comment]
In rust this typically happens when compiling in debug mode. However when optimizations are enabled, the behavior is overflowing as the overflow check would have some performance impact.
