### ISSUE TITLE
How to use `topk`?

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#1971]
I am trying to use `topk` to implement X-LoRA in Candle, and want to perform `topk` in the last dimension. Specifically, I need the `indices` return value (as returned by [`torch.topk`](https://pytorch.org/docs/stable/generated/torch.topk.html)). 

These indices will either be used to creaste a mask to zero out all the values which are _not_ in the topk, and/or used to apply scalings on the nonzero values. This is a may be hard to understand, as such please see [this](https://github.com/EricLBuehler/xlora/blob/3637d1e00854649e8b9162f8f87233248577162c/src/xlora/xlora_insertion.py#L50-L63) snippet from our X-LoRA library.

Is there a way to implement this with the current Candle functions, or is this planned to be implemented as a function?

---

After looking at the Mixtral MoE selection implementation, I cannot really understand it:

> https://github.com/huggingface/candle/blob/3144150b8d1b80b2c6b469dcab5b717598f0a458/candle-transformers/src/models/mixtral.rs#L302-L323

How does this work? Thanks!

**Comment by EricLBuehler** [comment]
@gregszumel, thanks for the explanation. I would love to see this added to Candle. If you want to contribute this to mistral.rs please feel free!

**Comment by LaurentMazare** [comment]
It's certainly not an efficient top_k as indeed we fully sort the array, but the worst part is more that the operation takes place on the cpu so this triggers some synchronization point. I'm putting together #2132 that should help doing this fully on the gpu, it will still sort the whole array but actually on gpus it's not necessarily that slower than a topk as the sort is done in parallel (also the number of experts is very small, 8, so this wouldn't be much of an issue even on the cpu).

**Comment by EricLBuehler** [comment]
@LaurentMazare, thanks! I saw that PR and am very excited for it to be merged.

**Comment by gregszumel** [comment]
@EricLBuehler Looks like it got merged - thanks at @LaurentMazare! 

I hope to find some time this week to implement top-k; I'm thinking it's home is probably in either in mistral.rs or candle-ext, but the argsort is probably a great workaround for now.

**Comment by EricLBuehler** [comment]
@gregszumel, that sounds great! If you decide to contribute it to mistral.rs, that would be much appreciated.

**Comment by EricLBuehler** [comment]
For future reference, here's the implementation: https://github.com/EricLBuehler/mistral.rs/blob/6aec940499be1cf72c628f7ddaa8b3e59bcb4fda/mistralrs-core/src/ops.rs#L482-L504
