### ISSUE TITLE
 Error When Running Stable-Diffusion Example 

### ISSUE THREAD

**Issue by keisuke-niimi-insightedge-jp** [huggingface/candle#1992]
I encountered an error while attempting to run the stable-diffusion example as instructed in the README.md. The specific command used was:
`cargo run --example stable-diffusion --release --features=cuda,cudnn     -- --prompt "a cosmonaut on a horse (hd, realistic, high-def)" --cpu `

The execution resulted in the following error:
`Error: MatMulUnexpectedStriding { lhs_l: Layout { shape: [1, 1, 4096, 4096], stride: [16777216, 16777216, 4096, 1], start_offset: 0 }, rhs_l: Layout { shape: [1, 1, 4096, 512], stride: [2097152, 512, 512, 1], start_offset: 0 }, bmnk: (1, 4096, 512, 4096), msg: "non-contiguous rhs" }`

After thoroughly reviewing the code and the recent changes, I suspect that the error might be related to the changes introduced in the following PR:(https://github.com/huggingface/candle/pull/1943/commits/c26dd7f54a44275b1a3803a95308bf8b37ed489c). The modifications in this pull request could potentially be causing the non-contiguous memory layout issue indicated by the error message.

I would like to suggest reconsidering the changes made in PR #1943 as a potential solution to this issue.

**Comment by LaurentMazare** [comment]
Thanks for reporting this, I've put a quick fix in #1993 , the longer term fix is to have this properly handled in the matmul but that's a bit more work.

**Comment by LaurentMazare** [comment]
Reverted the temporary fix in favor of a proper fix (that avoids the intermediate copy). It worked fine for me on both cpu and cuda + some tests have been added but let me know if this is still an issue on your side.

**Comment by LaurentMazare** [comment]
Closing as hopefully fixed, feel free to reopen if you run into further issues.
