### ISSUE TITLE
Writing up a "Contributing" guide

### ISSUE THREAD

**Issue by tomsanbear** [huggingface/candle#1996]
@LaurentMazare any thoughts around formalizing some of the development processes to help newcomers contribute faster? I wouldn't mind taking a stab at it if you haven't worked on this yet.

**Comment by shur-complement** [comment]
A list of starter issues would be good, things that aren't super high priority but would be welcome additions.

**Comment by tomsanbear** [comment]
Perfect, that sounds like a good idea with the book and improving rust docs on the operations as well 👍
