### ISSUE TITLE
[Possible bug?] Apparent memory leak in repeat_kv, KV cache

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#2070]
Hello all,

We are developing [mistral.rs](https://github.com/EricLBuehler/mistral.rs), an LLM serving platform, and have discovered some strange behavior when using non-quantized models. There appears to be very high peak memory usage, coming from the `repeat_kv` and KV caching functions. We have generated a trace [here](https://private-user-images.githubusercontent.com/12750442/322319382-649b3eac-2d29-423c-a9f5-87d6d4f1673f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxODQwMzMsIm5iZiI6MTcxMzE4MzczMywicGF0aCI6Ii8xMjc1MDQ0Mi8zMjIzMTkzODItNjQ5YjNlYWMtMmQyOS00MjNjLWE5ZjUtODdkNmQ0ZjE2NzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDEyMjIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjBlMTcwOGE5MjRkNDBhMzMyMWE0N2ZiYmY0NjBkNzMzMjVmMjhjYzk2ZWVkNDNhZTRlOTE3YzU2OGRkNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZYEpxqPJ-XjCFaLKlpTnx2gwLXqRsMBAX9kunjOxofY) which shows the high memory usage, on [this branch](https://github.com/EricLBuehler/mistral.rs/tree/hf_candle) to ensure no problems with our fork. We have looked at mistral.rs, and we are pretty sure that the error does not come from cached KV cache tensors (those would be too small anyway). Strangely, the issue does not occur with the official Candle implementation, even though our testing branch uses the same implementation and gets rid of all of our special caching functionality.

Is this something that may come from Candle? Our [testing branch](https://github.com/EricLBuehler/mistral.rs/tree/hf_candle) allows testing with a dependency from this repo, for reproducibility please run to start:
`cargo run --release --features cuda -- --port 1234 --log output.txt mistral`

And then send a chat completion request to generate a lot of text.

**Comment by LaurentMazare** [comment]
Maybe you could make a standalone repro, ideally as small and standalone as possible? That would be really helpful compared to having to dig through this different codebase and would help narrow down whether the issue is on the candle side or not.

**Comment by okpatil4u** [comment]
@EricLBuehler what was the resolution ?

**Comment by EricLBuehler** [comment]
We had some sort of issue with loading that when removed seemed to resolve it.
