### ISSUE TITLE
Quantized Matmul: Small batches are slower than no-batch

### ISSUE THREAD

**Issue by lucasavila00** [huggingface/candle#2074]
Thanks for the work on this repo, it's amazing.

The newly added quantized matmul kernels are great, but they're slower than using the vec kernels on small batch sizes.

On Llama.cpp I see they use the vec version if batch is <= 4 https://github.com/ggerganov/llama.cpp/pull/5351 https://github.com/ggerganov/llama.cpp/pull/5370

I'm reading https://github.com/huggingface/candle/blob/main/candle-kernels/src/quantized.cu and it seems the code was extracted from Llama.cpp before this PR was merged, and candle's version misses this optimization.

For context, this issue was noticed on mistral.rs https://github.com/EricLBuehler/mistral.rs/issues/139

**Comment by LaurentMazare** [comment]
Interesting, do you know if the new kernels are slower than the old approach for your use case? (the old approach was to dequantize then matmul so would not involve the mmv kernels). If that's the case, switching back to the old style when the input size is smaller than 4 should be a straightforward change.

**Comment by lucasavila00** [comment]
Old kernels:

batch=1 20ms
batch=2 278ms 
batch=3 354ms

New kernels:

batch=1 20ms
batch=2 133ms
batch=3 144ms


They are faster. But not batching is even faster.

**Comment by lucasavila00** [comment]
What I think is happening is that candle is not checking this condition: https://github.com/ggerganov/llama.cpp/blob/master/ggml-cuda.cu#L1898-L1900

And then not using the `vec` kernels: https://github.com/ggerganov/llama.cpp/blob/master/ggml-cuda.cu#L1955

I'm not too familiar with candle's source code but I'm profiling:

bs=1
![image](https://github.com/huggingface/candle/assets/12750442/3e9cdd74-ff79-4800-b554-f5f37c333fe0)


bs=2
![image](https://github.com/huggingface/candle/assets/12750442/d40d1086-2bf9-4ac8-bafb-40c05ec02f68)

**Comment by lucasavila00** [comment]
For reference, bs=2 and llama.cpp launches the `_vec` kernels

![image](https://github.com/huggingface/candle/assets/12750442/0e56e466-607f-436e-b645-52a3985b00b4)

**Comment by LaurentMazare** [comment]
Ok, thanks for the details, I'm testing it with #2075 the downside is that it adds a lot of kernels (even up to only batch size 4) so will have an impact on the binary size, but hopefully it's worth it.

**Comment by EricLBuehler** [comment]
Yes, we saw a great performance increase after MMVQ was added, so hopefully this will improve small batch performance.

**Comment by LaurentMazare** [comment]
#2075 has been merged, would be great if you can re-run the benchmarks and see if it improved things.

**Comment by EricLBuehler** [comment]
@lucasavila00, I've added this to our fork so it is ready to test.

**Comment by lucasavila00** [comment]
bs=1 18ms
bs=2 22ms
bs=3 33ms
bs=4 37ms
bs=5 120ms
bs=6 125ms
bs=7 130ms
bs=8 135ms
bs=9 140ms


Thank you! It improved things a lot.

Is implementing this up to 8 out of question, due to binary size?

**Comment by LaurentMazare** [comment]
Great that it worked out. I just tried out adding the kernels up to 8 in #2077 and it's a ~10% increase of binary size, from 19.6MiB to 21.4MiB on my box so I'm a bit on the fence for this - as it only affects cuda targets that might be fine though.

**Comment by lucasavila00** [comment]
Thank you!
