### ISSUE TITLE
VarBuilder from custom VarMap causes OOM

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#2079]
Hello all,

During my development of mistral.rs, I have run into some inexplicable OOM errors, probably related to safetensor loading. These have gone away when I replace my loading function with `candle_nn::VarBuilder::from_mmaped_safetensors`. I have reproduced the bug in the Candle Mistral example:

```diff
let dtype = if device.is_cuda() {
	DType::BF16
} else {
	DType::F32
};
+let map = candle_nn::VarMap::new();
+{
+	let mut ws = map.data().lock().unwrap();
+	for path in filenames {
+		let tensors = unsafe { candle::safetensors::MmapedSafetensors::new(path)? };
+		for (name, _) in tensors.tensors() {
+			let t = tensors.load(&name, &device)?.to_device(&device)?.to_dtype(dtype)?;
+			ws.insert(name, candle::Var::from_tensor(&t)?);
+		}
+	}
+}
+let vb = VarBuilder::from_varmap(&map, dtype, &device);
-let vb = unsafe { VarBuilder::from_mmaped_safetensors(&filenames, dtype, &device)? };
let model = Mistral::new(&config, vb)?;
(Model::Mistral(model), device)
```

I was wondering about possible unsoundness relating to my use of `unsafe`: `unsafe { candle::safetensors::MmapedSafetensors::new(path)? };`. Is this a mistake, or is there something else going on? Thank you for any help.

**Comment by LaurentMazare** [comment]
Could you provide details on the size of the weights that you're loading as well as the memory usage that you observe?

**Comment by EricLBuehler** [comment]
I ran the following command: `cargo run --release --features cuda --example mistral -- --prompt "Write a 3 paragraph essay."`

It exhausted the memory on a 24GB A10 after starting at a normal level in a few seconds.

**Comment by LaurentMazare** [comment]
I think that the issue is likely just that you use a varmap so the model will keep track of the gradient so that you can do a backprop. Maybe you just want to use a `HashMap` of tensors (and not vars), you can build var-builders out of this.

**Comment by EricLBuehler** [comment]
Wow, I can't believe I didn't see that. Thank you!
