### ISSUE TITLE
Request: PixelShuffle

### ISSUE THREAD

**Issue by oovm** [huggingface/candle#2102]
I hope to add [PixelShuffle](https://pytorch.org/docs/stable/_modules/torch/nn/modules/pixelshuffle.html#PixelShuffle) and [PixelUnshuffle](https://pytorch.org/docs/stable/_modules/torch/nn/modules/pixelshuffle.html#PixelShuffle) in pytorch

 I found this layer missing when porting some super-resolution and GAN models

**Comment by LaurentMazare** [comment]
Wouldn't the functions in `candle_nn::ops` work for you? Here is the [pixel_shuffle](https://github.com/huggingface/candle/blob/c388be93e73d74dc42cacb61ebc2123a61d0c721/candle-nn/src/ops.rs#L460) one.
