### ISSUE TITLE
Request: Please add support in examples for the new MS/Phi-3 family 

### ISSUE THREAD

**Issue by a-agmon** [huggingface/candle#2119]
Hi, 
Microsoft just released the new set of Phi 3 models (inc quantized models) that are supposed to be a game changer in performance and quality in memory/cpu limited environments. 
Im struggling a bit to make it work with Candle and I have a feeling its related to something in the model config that also changed. 
I think supporting it with example can be tremendously valuable to the HF community.

https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf

Thanks

**Comment by LaurentMazare** [comment]
Support for the quantized version is in #2118 and already works pretty well, we'll also add support for the non quantized version hopefully very soon.

**Comment by a-agmon** [comment]
Fantastic. Thanks @LaurentMazare
