### ISSUE TITLE
Model to architecture mapping

### ISSUE THREAD

**Issue by BDUG** [huggingface/candle#2161]
Hello HF team,

how can I identify which specific architecture, according to config.json, is supported by a specific implementation e.g., of Bert? I try to find a way to map between the RUST implementation and the HF Hub model. 

Thanks in advance

**Comment by LaurentMazare** [comment]
For bert for example, you can check if the fields that you care about appear in the rust version of the config [here](https://github.com/huggingface/candle/blob/a75cd8164fb0b8377d101fc8526783d4abd18f12/candle-transformers/src/models/bert.rs#L47). This wouldn't give you full insurance that it's properly supported but at least if it doesn't appear you can be sure that it's not supported :) (lately we've tried to fail on parameter that have values which are not fully handled but that wasn't the case when adding bert etc)

**Comment by BDUG** [comment]
Thanks got it.
