### ISSUE TITLE
Incorrect EOS token(s) in meta-llama/Meta-Llama-3-8B-Instruct example

### ISSUE THREAD

**Issue by socathie** [huggingface/candle#2164]
The `EOS_TOKEN` variable is either incorrect or not working in the llama example. A simple prompt to test this is ""Only answer yes or no". And you will see the output goes on forever, including the word "assistant", indicating that the output stream did not stop at the `EOS_TOKEN`.

However, changing the `EOS_TOKEN` variable to `<|eot_id|>` or `<|end_of_text|>` also didn't work. suggesting that there is something wrong with how the `EOS_TOKEN` was handled in the tokenizer during decoding.

Still investigating, will open a PR if I happen to solve it, but if anyone has any hint or lead that would be great!

**Comment by LaurentMazare** [comment]
For llama3, the end of text should indeed be `<|end_of_text|>` (and not the hardcoded `</s>` from the main llama example). If it still doesn't produce it, one thing that may cause it is that we don't automatically add the bos token neither so maybe you want to add it as it's used in the main training, see [here](https://github.com/meta-llama/llama3/blob/d6e09315954d1a547bf45e37269978c049e73d33/llama/generation.py#L256).

**Comment by socathie** [comment]
i don't think BOS token was the issue. I have been using the following custom prompt, manually including the BOS token
`let prompt = format!("<|begin_of_text|><|start_header_id|>user<|end_header_id|>{}<|eot_id|><|start_header_id|>assistant<|end_header_id|>", args_prompt);`

**Comment by LaurentMazare** [comment]
Agreed, looks like your code should insert the right tokens. It might be worth checking the tokenizer output just in case but I wouldn't see any reason for it not to be as expected.

**Comment by socathie** [comment]
I have found more peculiar behavior. For both `<|eot_id|>` and `<|end_of_text|>`, `tokenizer.token_to_id(EOS_TOKEN)` returns `Some(128001)` but in the Python version `<|eot_id|>` is 128001 and `<|end_of_text|>` is 128009. Hence, the code never uses the correct EOS token ID unless we hardcode it to 128009.

**Comment by edesalve** [comment]
The tokenizer seems to work properly, it gives 128001 for `<|end_of_text|>` and 128009 for `<|eot_id|>`. For the instruct model 128009 is indeed the correct eos token as it is possible to see from the config.json file.
In my experience new lines play a fundamental role in the prompt template of the instruct model. Using the following works well for me:

```rust
format!("<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{system}<|eot_id|>\n<|start_header_id|>user<|end_header_id|>\n\n{user}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n")
```

**Comment by socathie** [comment]
The above comment from @edesalve is correct, somehow I cannot reproduce the error from two comments up anymore. Closing this issue for now. Thanks for the help!

In summary, here is the fix (not doing a PR since it is not universal for all supported llama models):
```rust
// change const EOS_TOKEN: &str = "</s>" to
const EOS_TOKEN: &str = "<|eot_id|>";
```
and 
```rust
// change to config.eos_token_id.or_else(|| tokenizer.token_to_id(EOS_TOKEN));
let eos_token_id = tokenizer.token_to_id(EOS_TOKEN);
```
