### ISSUE TITLE
Metal error "no metal implementation for rms-norm" for Llama3 variant

### ISSUE THREAD

**Issue by n8mellis** [huggingface/candle#2184]
I'm using NVIDIA's Llama3 variant on HuggingFace (https://huggingface.co/nvidia/Llama3-ChatQA-1.5-8B) and it works like a charm (if expectedly slow) with CPU and Accelerate but I get the above error when I try to run the model with Metal.

**Comment by LaurentMazare** [comment]
If you're doing this in your own crate, are you sure that the metal feature is activated on both `candle-core`,  `candle-nn`,  and `candle-transformers`.

**Comment by n8mellis** [comment]
That did the trick! Thanks so much. I missed that those other two crates had a metal feature as well. Appreciate the quick response!
