### ISSUE TITLE
Unable to convert t5 model to GGUF

### ISSUE THREAD

**Issue by niranjanakella** [huggingface/candle#2215]
@LaurentMazare  Hello, I am trying to convert the flan-t5 model to GGUF. I have tried browsing in many places but wasn't successful in converting flan-t5 model to GGUF. 

```
cd candle-examples/examples

cargo run --example tensor-tools --release -- quantize --quantization q6k ~/candle/flan-t5-small/model.safetensors --out-file ft5q6k.gguf
```

I have tried running the above command but it is returning the following error
```
error: no example target named `tensor-tools`.
```

My aim is to convert flan-t5-models to GGUF format. Also I wish to know if there is a high level API/python bindings to write scripts on python utilizing the candle framework. 

Please kindly help.

**Comment by niranjanakella** [comment]
@LaurentMazare I also wish not to quantize the model but instead use it at full or half precision. Please help me out in converting this model.

**Comment by omkar-12bits** [comment]
@niranjanakella  you are using wrong command ,
```bash
cargo run --release --bin tensor-tools -- quantize --quantization q4_0  \
model.safetensors --out-file model_q4_0.gguf
```

**Comment by niranjanakella** [comment]
@omkar-12bits  Thanks a lot, can you also please let me know how to run this quantized model? 

I have been following the below: 
https://github.com/huggingface/candle/tree/e37b4877677b7fd97604b2306ef2cd9023c79c6f/candle-examples/examples/quantized-t5
