### ISSUE TITLE
CUBLAS_STATUS_NOT_SUPPORTED for Conv2d

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#2218]
Hello all,

Thank you for your great work here. I am using `Cond2d` to implement vision embeddings for the Idefics 2 model. However, when testing, I ran into the error `CUBLAS_STATUS_NOT_SUPPORTED`. 

The layer is initialized as follows:
```rust
let conv_config = Conv2dConfig {
    stride: 14,
    ..Default::default()
};
let patch_embedding = conv2d(
    /* in= */ 3,
    /* out= */ 1152,
    /* kernel_size = */ 14,
    conv_config,
    vb.pp("patch_embedding"),
)?
```

And we run use the layer with input data of shape:
`Tensor[dims 5, 3, 663, 980; bf16, cuda:0]`

This results in the following error:
`Cuda(Cublas(CublasError(CUBLAS_STATUS_NOT_SUPPORTED)))`

I would be happy to provide more information such as my CUDA versions, full backtrace, etc. Thank you for any help!

**Comment by LaurentMazare** [comment]
I just ran the following code based on your example and it worked properly for me. Maybe you could provide more details on how to reproduce the issue?
```rust
fn main() -> Result<()> {
    let dev = Device::new_cuda(0)?;
    let conv_config = Conv2dConfig {
        stride: 14,
        ..Default::default()
    };
    let vb = VarBuilder::zeros(DType::BF16, &dev);
    let patch_embedding = conv2d(
        /* in= */ 3,
        /* out= */ 1152,
        /* kernel_size = */ 14,
        conv_config,
        vb.pp("patch_embedding"),
    )?;
    let t = Tensor::zeros((5, 3, 663, 980), DType::BF16, &dev)?;
    let res = patch_embedding.forward(&t)?;
    println!("{res}");

    Ok(())
}
```

**Comment by EricLBuehler** [comment]
I think I figured it out. If we set 
```rust
candle_core::cuda::set_gemm_reduced_precision_f16(true);
```
Then it crashes. I think this is not a bug though, so I'll close the issue.
