### ISSUE TITLE
Since cudarc 0.11.4 error with PTX -- CUDA_ERROR_UNSUPPORTED_PTX_VERSION

### ISSUE THREAD

**Issue by CoffeeVampir3** [huggingface/candle#2237]
Library builds, but throws a runtime error:

```
Error: DriverError(CUDA_ERROR_UNSUPPORTED_PTX_VERSION, "the provided PTX was compiled with an unsupported toolchain.") when loading cast_u32_f32
```

I have no idea where to begin debugging this, but this is a recent issue caused in the last two days with the update of cudarc 0.11.4.

System details:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:19:55_PDT_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0
```

```
gcc (GCC) 14.1.1 20240522
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Arch linux -- endeavour OS

```
[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = ">=0.5.1", features = ["cuda"] }
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = ">=0.5.1", features = ["cuda"] }
tokenizers = { version=">=0.19.1", features = ["onig"] }
anyhow = ">=1.0.71"
```

Run script: https://gist.github.com/CoffeeVampir3/b66ee4e9695e7daae4f328edb599c1d3

**Comment by LaurentMazare** [comment]
You may want to try removing your `target` directory or do some form of `cargo clean` to trigger a new compilation from scratch (the new cudarc might have picked a different cuda version on your system and you would need to recompile the PTX files).

**Comment by CoffeeVampir3** [comment]
> You may want to try removing your `target` directory or do some form of `cargo clean` to trigger a new compilation from scratch (the new cudarc might have picked a different cuda version on your system and you would need to recompile the PTX files).

Cargo clean, deleting lock file, or even making an entirely new cargo project don't have any change in outcome for me. Any new candle projects give me the same error.

**Comment by CoffeeVampir3** [comment]
Okay! After a few days of troubleshooting I've tracked down the problem. This wasn't clear to me, but the issue was a cuda 12.5 VS my driver supported cuda 12.4 mismatch. Updating to cuda 12.5 compatible drivers fixes this problem. So the issue was really not the PTX version at all, but the cuda minor version mismatch.
