### ISSUE TITLE
Qwen2: can not run with the latest Qwen2 models

### ISSUE THREAD

**Issue by zensh** [huggingface/candle#2256]
I am trying to run Qwen2 example with the latest Qwen2 0.5B model, but get a `Error: cannot find tensor lm_head.weight`.

https://huggingface.co/Qwen/Qwen2-0.5B

**Comment by LaurentMazare** [comment]
Ah thanks for reporting this, indeed there is a small difference in the new model architecture, I'm minting #2257 to support this and you should be able to use the new model with ` --model 2-0.5b`.

**Comment by zensh** [comment]
@LaurentMazare Thank you very much, it’s now running. However, the results from the 0.5B model are a bit strange, which might be due to other issues.

**Comment by deadash** [comment]
7b is incorrect
