### ISSUE TITLE
Parler TTS support?

### ISSUE THREAD

**Issue by sidharthrajaram** [huggingface/candle#2283]
Hi, are there plans to support the Parler-TTS line of models? 

Thanks!

**Comment by LaurentMazare** [comment]
No specific plans at the moment but it might not be very hard to add as:
- The text conditioning uses T5 which candle already supports.
- The audio tokenizer DAC seems to be encodec based which is also already in candle.
So the main things to add are the transformer with cross-attn model and the generation procedure from [this file](https://github.com/huggingface/parler-tts/blob/main/parler_tts/modeling_parler_tts.py).

**Comment by LaurentMazare** [comment]
I've actually started adding some support in #2431 , the DAC decoding is not handled yet - I'll look at it next and hopefully it shouldn't be too hard to do - but the rest of the generation seems to work reasonably well.

**Comment by LaurentMazare** [comment]
The DAC part has been added so no need for any python anymore, thanks for suggesting this and let us know if you run into any issues.

**Comment by sidharthrajaram** [comment]
Thanks @LaurentMazare ! Will do.
