### ISSUE TITLE
Change single value of tensor

### ISSUE THREAD

**Issue by v-espitalier** [huggingface/candle#2303]
Hi,

I guess I missed sth, as I can't figure out how to update a single value of a tensor.
(I know it's not good practice to write code with loops on indexes; it's for testing / debugging purpose)
How to change a single value of a tensor ?
Thanks for any answer

```
let mut t = Tensor::zeros((10, 10), DType::F32, &Device::Cpu)?;

t[5][5] = 3.14;
t[5][5].to_scalar() = 3.14;
t.i((5, 5))? = 3.14;
t.i((5, 5))?.to_scalar()? = 3.14;
t.i((5, 5))? = 3.14 * Tensor::ones((1), DType::F32, &Device::Cpu)?;
```

**Comment by EricLBuehler** [comment]
You can do this with the `slice_assign` method:
```rust
let a = Tensor::zeros((10, 10), DType::F32, &Device::Cpu)?;
let to_insert = (Tensor::ones((1), DType::F32, &Device::Cpu)? * 3.14f64)?;
// 0..1 means at index 0.
let b = a.slice_assign(&[0..1, 0..1], &to_insert)?;
```

**Comment by v-espitalier** [comment]
Thank you for your quick answer. Could not have found it by myself.

**Comment by EricLBuehler** [comment]
Happy to help!
