### ISSUE TITLE
Indexing the first dim of a 2D tensor with a 1D tensor

### ISSUE THREAD

**Issue by v-espitalier** [huggingface/candle#2304]
Hi,

I am translating Python code to Rust and can't figure out how to index a 2D tensor with a 1D one.
Can you please advise ? Thanks for any help.

Here is the code snippet.
```
println!("table.dims: {:?}", table.dims());
> table.dims: [2212, 12]

println!("index_list.dims: {:?}", index_list.dims());
> index_list.dims: [332929]       // (with tensor values within 0..2212)

//let bias = table[index_list];   // From Python, not working in Rust
let bias = table.gather(&index_list, 0)?;
> Error: shape mismatch in gather, lhs: [2212, 12], rhs: [332929]
Expected:
println!("bias.shape: {:?}", relative_position_bias.dims());
> bias.shape: torch.Size([332929, 12])
```

I think I need to use another function than **gather()**,
maybe get inspired by : https://github.com/huggingface/candle/issues/855
but I get lost with argmax_keepdim() and broadcast_as() functions..

**Comment by EricLBuehler** [comment]
Hi @v-espitalier, I think the function you want is [`index_select`](https://docs.rs/candle-core/latest/candle_core/struct.Tensor.html#method.index_select). All you need to do it pass the indices (a 1 dim tensor), and the dimension to index on, and it will do the equivalent of Pytorch slice indexing with a tensor in that dim (as long as the tensor contains indices).

**Comment by v-espitalier** [comment]
Thank you very much. It worked :-)
