### ISSUE TITLE
use of undeclared crate or module `candle`

### ISSUE THREAD

**Issue by lifengstone** [huggingface/candle#2312]
I have followed the instruction to install the candle-core but still got the error: use of undeclared crate or module `candle`. How to fix this issue? Thanks in advance!

**Comment by MilkFather** [comment]
I would appreciate a minimal reproducible example. But for now, my guess is that you used `use candle` instead of `use candle_core` - there is no module named `candle`, only `candle_core`.

**Comment by MilkFather** [comment]
Tricks are used here. Go up to the `Cargo.toml` file located at `candle-examples`, on Line 14, `candle` is defined to inherit the definition at the workspace root. Go further up to the `Cargo.toml` located at the project root, on Line 36, `candle` is aliased to `candle-core`.
