### ISSUE TITLE
Error in Moondream Example

### ISSUE THREAD

**Issue by iggyzuk** [huggingface/candle#2338]
Running command:
`cargo run --example moondream --release -- --prompt "What is the girl eating?" --image "./demo-1.jpg"`

Results in this error:
`Error: shape mismatch for vision_encoder.projection.mlp.fc1.weight, expected: [8192, 1152], got: [8192, 2304]`

Anyone know why the shapes don't match? Any fixes? Thanks.

**Comment by LaurentMazare** [comment]
Thanks for reporting this, this was caused by some recent changes in the moondream architecture, I've pinned the revision that we use from the HF repo so that this shouldn't happen anymore. #2340

**Comment by iggyzuk** [comment]
Nice one, thanks, works like a charm! 🎉
