### ISSUE TITLE
`gradient_accumulation_steps` b2b

### ISSUE THREAD

**Issue by Khaliq88** [huggingface/candle#2342]
We can add a check in more than one place. Although, tbh, I've never seen someone raise an issue because of setting `gradient_accumulation_steps` to be less than 1 so I don't think this is something we really need to address.

_Originally posted by @amyeroberts in https://github.com/huggingface/transformers/pull/32020#discussion_r1683019529_

**Comment by Khaliq88** [comment]
#2341 
#1469

**Comment by amyeroberts** [comment]
@Khaliq88 Please refrain from spamming the issues with copies of comments from reviews and other issues and linking to things which are unrelated.
