### ISSUE TITLE
how to specify generator for  randn function

### ISSUE THREAD

**Issue by jk2K** [huggingface/candle#2347]
pytorch
```python
noise = torch.randn(x_start.size(), dtype=x_start.dtype, layout=x_start.layout, generator=torch.manual_seed(seed)).to(x_start.device)
```

how to specify seed in candle?

**Comment by EricLBuehler** [comment]
@jk2K you can set the seed of a device with [`Device::set_seed`](https://docs.rs/candle-core/latest/candle_core/enum.Device.html#method.set_seed).

**Comment by jk2K** [comment]
Device, metal
```
    let x_start = Tensor::new(&[1., 2., 3.], &Device::Cpu).unwrap();

    let device = Device::new_metal(0).unwrap();
    let result = device.set_seed(21u64);
    if result.is_err() {
        return result
    }
    let a1 = Tensor::randn(0f64, 1f64, x_start.shape(), &device).unwrap();
    println!("{a1}");
```
got error `called `Result::unwrap()` on an `Err` value: WithBacktrace { inner: Msg("rand_uniform not implemented for F64"), backtrace: Backtrace [{ fn: "std::backtrace_rs::backtrace::libunwind::trace", fi`


Device, Cpu
```
    let x_start = Tensor::new(&[1., 2., 3.], &Device::Cpu).unwrap();


    let device = Device::Cpu;
    let result = device.set_seed(21u64);
    if result.is_err() {
        return result
    }
    let a1 = Tensor::randn(0f64, 1f64, x_start.shape(), &device).unwrap();
    println!("{a1}");
```

get error, `Error: WithBacktrace { inner: Msg("cannot seed the CPU rng with set_seed"), backtrace: Backtrace [{ fn: "std::backtrace_rs::backtrace::libunwind::trace",`

**Comment by EricLBuehler** [comment]
So for Metal, `rand_uniform` is only implemented for f32, f16, and bf16. This should work:
```
let x_start = Tensor::new(&[1., 2., 3.], &Device::Cpu).unwrap();

let device = Device::new_metal(0).unwrap();
let result = device.set_seed(21u64).unwrap();
let a1 = Tensor::randn(0f32, 1f32, x_start.shape(), &device).unwrap();
println!("{a1}");
```

For CPU, I think setting the seed is just not supported yet.

**Comment by jk2K** [comment]
👍, thanks,
