### ISSUE TITLE
Any considerations for updates to use Llama 3.1?

### ISSUE THREAD

**Issue by BradyBonnette** [huggingface/candle#2354]
I realize that it was just released yesterday (7/23/2024) and incorporating new/updated models can take a lot of time and energy, but was wondering if Llama 3.1 (with the extended context window) was something that is on the radar for inclusion with `candle`.

Is this something you typically only handle internally? Is it something you'd take outside contributions for?

**Comment by zackangelo** [comment]
If you just point the model at the new repo it should mostly work, it's largely the same architecture. 

There is one change that's needed to incorporate some differences in the RoPE layer, but it should generate valid tokens without that.

**Comment by zackangelo** [comment]
@EricLBuehler incorporated the necessary change in mistral.rs, if someone wants to upstream it: 
https://github.com/EricLBuehler/mistral.rs/pull/618

**Comment by BradyBonnette** [comment]
@zackangelo Funny enough I started experimenting with it yesterday in the candle repo cloned locally, and after making some adjustments to the configuration expectations (i.e. reading from `config.json`, it at least loaded the model but didn't inference.

Ill take a look at what Eric has done. I am hoping it's a relatively easy import. :)

**Comment by BradyBonnette** [comment]
> if someone wants to upstream it

I can try taking a crack at it. Others here might be more successful, but for my project I could almost immediately use it if it were available.

**Comment by zackangelo** [comment]
> @zackangelo Funny enough I started experimenting with it yesterday in the candle repo cloned locally, and after making some adjustments to the configuration expectations (i.e. reading from `config.json`, it at least loaded the model but didn't inference.
> 
> Ill take a look at what Eric has done. I am hoping it's a relatively easy import. :)

Did you get an error? The model implementation I'm currently using for Mixlayer is pretty close to what's in the examples right now and it works.

**Comment by BradyBonnette** [comment]
Nope, no error, it just didn't inference at all. It returned 0 tokens.

**Comment by EricLBuehler** [comment]
@BradyBonnette @zackangelo I just opened a PR for this!

**Comment by BradyBonnette** [comment]
Closing this due to https://github.com/huggingface/candle/pull/2359 getting merged.

Huge shout out to @EricLBuehler for getting it squared away in short order, and @LaurentMazare for getting it merged in so quickly!
