### ISSUE TITLE
Tensor::log_sum_exp() loses precision for small numbers

### ISSUE THREAD

**Issue by leejuyuu** [huggingface/candle#2356]
The current implementation of the `Tensor::log_sum_exp()` function does not handle small numbers correctly. For example, the following code 

```rust
let arr = Tensor::full(-1000_f64, (10,), &Device::Cpu)?;
let logsumexp = arr.log_sum_exp(0)?;
println!("{:?}", logsumexp);
```

prints 

```
Tensor[-inf; f64]
```

whereas on torch 2.3.0  

```python
>>> arr = torch.tensor([-1000]*10)
>>> torch.logsumexp(arr, 0)
tensor(-997.6974)
```

### Version info
candle-core = "0.6.0"
Tested on Arch Linux

**Comment by LaurentMazare** [comment]
Closing based on the fix in #2367, feel free to reopen if it's still an issue.
