### ISSUE TITLE
use candle to train model in browser / Chrome / wasm32 ?

### ISSUE THREAD

**Issue by zeroexcuses** [huggingface/candle#2391]
Is it possible to use candle to TRAIN a model in browser / Chrome / wasm32 ?

The use case is: say we are explaining MNIST / covnet -- I'd like to be able to have an interactive demo for trainining a MNIST classifier in webpage, doing the traininig 
directly in browser.

Thanks!

**Comment by LaurentMazare** [comment]
Sure, the backprop/training part is independent from the backend and should work on any of them including the browser.

**Comment by zeroexcuses** [comment]
Thanks!
