### ISSUE TITLE
Unsupported cuda toolkit version: 12.6

### ISSUE THREAD

**Issue by yulan233** [huggingface/candle#2410]
error log：
warning: `G:\environment\rust\.cargo\config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
   Compiling candle-kernels v0.6.0
   Compiling cudarc v0.11.8
error: failed to run custom build command for `cudarc v0.11.8`

Caused by:
  process didn't exit successfully:  (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CUDA_ROOT
  cargo:rerun-if-env-changed=CUDA_PATH
  cargo:rerun-if-env-changed=CUDA_TOOLKIT_ROOT_DIR

  --- stderr
  thread 'main' panicked at G:\environment\rust\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\cudarc-0.11.8\build.rs:82:14:
  Unsupported cuda toolkit version: `12.6`. Please raise a github issue.
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by LaurentMazare** [comment]
cuda 12.6 support is dependent on cudarc supporting it which is currently in this PR: https://github.com/coreylowman/cudarc/pull/286

**Comment by chandeldivyam** [comment]
@LaurentMazare Thank you so much for the prompt response.

**Comment by lukas0008** [comment]
@LaurentMazare 
> cuda 12.6 support is dependent on cudarc supporting it which is currently in this PR: [coreylowman/cudarc#286](https://github.com/coreylowman/cudarc/pull/286)

That pr got merged, is it now possible to update `cudarc` to 0.12.1 to support cuda 12.6?
