### ISSUE TITLE
It should be "vb.contains_tensor("lm_head.weight")"?

### ISSUE THREAD

**Issue by ilookee** [huggingface/candle#2443]
https://github.com/huggingface/candle/blob/2ec8729d51a8561841d95b55bbe7fc4e7991eab2/candle-transformers/src/models/qwen2.rs#L364

When I load Qwen2-7B, "vb.contains_tensor("lm_head")" return false, and "vb.contains_tensor("lm_head.weight")" return true.

**Comment by LaurentMazare** [comment]
Ah good point, do you want to make a PR with the change and test that it works well on your use case? If not I can take a stab at it.

**Comment by LaurentMazare** [comment]
Closing this now as it should be fixed by the associated PR.
