### ISSUE TITLE
Error: Metal(Message("no metal implementation for layer-norm"))

### ISSUE THREAD

**Issue by Adiao1973** [huggingface/candle#2463]
When I use the Metal backend for inference https://huggingface.co/lmz/candle-sam/tree/main/mobile_sam-tiny-vitt.safetensors model, there is an Error: Metal (Message ("no metal implementation for layer-norm")) error, my chip model is M3MAX
My guess is that the Metal backend implementation of the candle library may be incomplete, and some operations (such as layer normalization) have not yet been implemented
If it's ok, please implement them, thank you.

**Comment by LaurentMazare** [comment]
Did you activate the `metal` feature on the `candle-nn` package (as well as on `candle-core`)? Otherwise that may well explain why the implementation is not included.

**Comment by Adiao1973** [comment]
I know it, this is my Cargo.toml
<img width="623" alt="image" src="https://github.com/user-attachments/assets/c1431135-3eb0-4ec0-b215-8ac1b3a664bc">
This is my demo code
<img width="1137" alt="image" src="https://github.com/user-attachments/assets/16a6341e-0713-41e2-8167-c88b74b0bc59">
But my run result is like this
<img width="778" alt="image" src="https://github.com/user-attachments/assets/aa4fc8db-069b-472f-8ac6-167357410f8d">

**Comment by Adiao1973** [comment]
Oh no, I see, I forgot to activate the feature of candle-nn, thank you, I know how to solve it.
