### ISSUE TITLE
Error running Llama example with v31-instruct

### ISSUE THREAD

**Issue by danielclough** [huggingface/candle#2575]
With the latest main, running this command:
`cargo run --example llama --release --features=cuda --   --prompt "what is your name?" --which v31-instruct`
I get this error:
`Error: Header etag is missing`

**Comment by LaurentMazare** [comment]
I guess it's related to this PR https://github.com/huggingface/hf-hub/pull/36 but it doesn't seem that there was a crates.io release since the fix was merged so it's not straightforward to switch to the patched version.

**Comment by LaurentMazare** [comment]
Should be fixed past #2576 , thanks for reporting the issue.
