### ISSUE TITLE
Layer-norm: poor batch size scaling compared to tch

### ISSUE THREAD

**Issue by JHucker** [huggingface/candle#2583]
We use tch to enumerate molecular libraries using simple auto-regressive transformer models (generally tiny models with small vocab and short sequence lengths).

We would eventually like to move over to candle to reduce the docker image sizes amongst other things. 

On a workstation with a 4090, I can get ~3,900 samples a second using full precision and ~9,200 using half on tch. I’ve done some experimental work porting the model and sampling code over to candle, but it appears that the batching does not scale nearly as well (average ms taken after a warm-up for both):

```
| batch size | total samples | tch 5 run average ms | tch samples / sec | candle 5 run average ms | candle samples / sec |
|------------|---------------|----------------------|-------------------|-------------------------|----------------------|
|          1 |            20 |                  393 |                51 |                     250 |                   80 |
|          2 |            40 |                  436 |                92 |                     337 |                  119 |
|         10 |           200 |                  436 |               459 |                     396 |                  505 |
|         50 |         1,000 |                  443 |             2,257 |                     713 |                1,403 |
|        100 |         2,000 |                  608 |             3,289 |                   1,139 |                1,756 |
|        200 |         4,000 |                1,055 |             3,791 |                   3,107 |                1,287 |
|        250 |         5,000 |                1,310 |             3,817 |                   3,366 |                1,485 |
|        300 |         6,000 |                1,539 |             3,899 |                   4,878 |                1,230 |
|        350 |         7,000 |                1,834 |             3,817 |                   5,493 |                1,274 |
|        400 |         8,000 |                2,122 |             3,770 |                   7,014 |                1,141 |
```

I annotated the code with nvtx and compared the two using a batch size of 200 in nsight systems. 

There were a few points of difference, one notable being layer normalisation. 

I then captured this over a few different batch sizes (μs are average of 6 calls in a forward pass of the last iteration of sampling):

```
| batch size | tch μs | tch samples / μs | candle μs | candle samples / μs |
|------------|--------|------------------|-----------|---------------------|
|          1 |      2 |                1 |         2 |                   1 |
|         10 |      3 |                3 |         7 |                   1 |
|        100 |     11 |                9 |        65 |                   2 |
|        200 |     20 |               10 |       130 |                   2 |
```

It would be great to see this gap in throughput close so we could switch from tch to candle. 

Is there anything else I could provide to assist here e.g. any further information or a minimal reproducible example in a repo? 

**NVIDIA details**
```
$nvidia-smi --query-gpu=name,compute_cap,driver_version --format=csv
name, compute_cap, driver_version
NVIDIA GeForce RTX 4090, 8.9, 560.35.03
```

**Relevant deps**
```
candle-core = {  version = "0.7.2", features = ["cuda"] }
candle-nn = { version = "0.7.2", features = ["cuda"] }
tch = { version = "0.17.0" }
```

**Comment by LaurentMazare** [comment]
Thanks for reporting this.
Do you know if your code ends up using the fused layer-norm kernel or if it does all the cuda operations separately? The fused kernel should be a lot faster compared to the old path but only triggers based on some conditions that you can see [here](https://github.com/huggingface/candle/blob/139ff56aeb1a6bbf0ed742f936a7a96bebccfa30/candle-nn/src/layer_norm.rs#L110). If this doesn't help, happy to see a minimal repro so that we can have a deeper look.

**Comment by JHucker** [comment]
It does meet the criteria for the fused kernel op, also seeming to confirm this: in nsight systems I can see only one kernel for the duration of the layer-norm nvtx annotation: `layernorm_f32`.

I’ll get a minimal reproducible example together in the next few days.

**Comment by JHucker** [comment]
Please see: https://github.com/JHucker/candle_2583_minrep

Let me know if you require anything further.

**Comment by LaurentMazare** [comment]
Thanks for the repro, I think the culprit is that the cuda launch config was pretty poorly tuned for small dimensions. I've tweaked it in #2591 and it seems much closer to what you observe with tch. I'll add a few tests just to check that it's still computing what it should and hopefully it should be all good then. Would be great if you can give it a spin too.

**Comment by JHucker** [comment]
This has helped a lot, rerunning the minrep shows great results. For model throughput the previous best with candle was ~1,800 samples / sec, using the faster-layer-norm branch this improves to ~2,500:

```
| batch size | total samples | ver "0.7.2" 5 run average ms | ver "0.7.2" samples / sec | "faster-layer-norm" 5 run average ms | "faster-layer-norm" samples / sec |
|------------|---------------|------------------------------|---------------------------|--------------------------------------|-----------------------------------|
|          1 |            20 |                          250 |                        80 |                                  274 |                                73 |
|          2 |            40 |                          337 |                       119 |                                  331 |                               121 |
|         10 |           200 |                          396 |                       505 |                                  364 |                               549 |
|         50 |         1,000 |                          713 |                     1,403 |                                  550 |                             1,818 |
|        100 |         2,000 |                        1,139 |                     1,756 |                                  810 |                             2,469 |
|        200 |         4,000 |                        3,107 |                     1,287 |                                2,518 |                             1,589 |
|        250 |         5,000 |                        3,366 |                     1,485 |                                2,573 |                             1,943 |
|        300 |         6,000 |                        4,878 |                     1,230 |                                3,935 |                             1,525 |
|        350 |         7,000 |                        5,493 |                     1,274 |                                4,474 |                             1,565 |
|        400 |         8,000 |                        7,014 |                     1,141 |                                5,694 |                             1,405 |
```

That branch resolves this issue for me. 

I’m motivated to get inference moved over to candle. I’ll see if I can find more reproducible examples which affect our use-case in the coming weeks.
