### ISSUE TITLE
Support Skip Layer Guidance (SLG) for Stable Diffusion 3.5 Medium

### ISSUE THREAD

**Issue by Czxck001** [huggingface/candle#2588]
Skip Layer Guidance (SLG) is a sampling technique that adds extra guidance to the original CFG in certain range of steps of sampling. The extra guidance is calculated by comparing the positive DiT model output from original model substracted by the positive model output from a variant model with certain layers removed (e.g. layer 7, 8 and 9 for Stable Diffusion 3.5 Medium).

Although SLG appears to be an optional choice, SAI seems officially prefer that enabled for Stable Diffusion 3.5 Medium. Evidance includes:
- The official repo on HuggingFace Hub offers a [ComfyUI workflow](https://huggingface.co/stabilityai/stable-diffusion-3.5-medium/blob/main/SD3.5M_SLG_example_workflow.json) with SLG enabled.
- Official reference design GitHub repo [Stability-AI/sd3.5](https://github.com/Stability-AI/sd3.5) comes with [a recent change](https://github.com/Stability-AI/sd3.5/pull/11/files) that supported SLG for SD3.5-medium.

Posts on Reddit (e.g. [this one](https://www.reddit.com/r/StableDiffusion/comments/1gf0h74/stable_diffusion_35_medium_has_been_released_and/)) and Twitter/X (e.g. [this one](https://x.com/dango233max/status/1851285093438144899)) that cover the use of SLG in Stable Diffusion 3.5 Medium suggest that the use of SLG seems to be important to "reduces the chance of anatomy failure and increases the overall coherency", with multiple independent posts cross-validate this claim.

@LaurentMazare WDYT? If this is considered recommended officially, I guess it's better to support that in the MMDiT model and example. If it's justified, I can get this implemented this week.

**Comment by LaurentMazare** [comment]
If it's in the official implementation, it seems like a good option to add as long as the added complexity isn't too bad (the python diff looks pretty reasonable).
