### ISSUE TITLE
rand problem on GPU

### ISSUE THREAD

**Issue by LonlyWinter** [huggingface/candle#2599]
Using the `Tensor::randn` method on the GPU, the same `DeviceId` produces different results, but the same device generates the same result in order.

For example, every time the GPU device generates the same data:
> [-1.8935767, 0.9397, 1.0709493, -0.013547109]
> [-0.23097327, -0.41472757, -0.1733321, 0.3322222]
> [0.1011943, 0.46094573, -0.51607126, 0.11089408

Thank you.

Platform: Windows 11, WSL 2, AnolisOS, NVIDIA GeForce RTX 4060 Laptop GPU
candle-core: version=0.7.2, fearures=["cuda"]
cudarc: version=1.12.1
![1](https://github.com/user-attachments/assets/6b03a396-00d2-45d3-82f0-88cbac91df81)

**Comment by LaurentMazare** [comment]
That's actually the expected behavior, you can change the seed of the rng via `set_seed` if you want to have different values each time.

**Comment by LonlyWinter** [comment]
Thanks, it works.
