### ISSUE TITLE
candle-transformers is not compiling

### ISSUE THREAD

**Issue by profitgrowinginnovator** [huggingface/candle#2621]
Compiling candle-transformers v0.8.0 (/projects/ai/candle/candle/candle-transformers)
error[E0716]: temporary value dropped while borrowed
   --> candle-transformers/src/models/chinese_clip/text_model.rs:157:22
    |
155 |         let token_type_ids = match token_type_ids {
    |             -------------- borrow later stored here
156 |             Some(token_type_ids) => token_type_ids,
157 |             None => &self.token_type_ids.i((.., 0..seq_length))?,
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^-
    |                      |                                         |
    |                      |                                         temporary value is freed at the end of this statement
    |                      creates a temporary value which is freed while still in use
    |
help: consider using a `let` binding to create a longer lived value
    |
155 ~         let binding = self.token_type_ids.i((.., 0..seq_length))?;
156 ~         let token_type_ids = match token_type_ids {
157 |             Some(token_type_ids) => token_type_ids,
158 ~             None => &binding,
    |

error[E0716]: temporary value dropped while borrowed
   --> candle-transformers/src/models/stable_diffusion/vae.rs:399:39
    |
397 |         let xs = match &self.post_quant_conv {
    |             -- borrow later stored here
398 |             None => xs,
399 |             Some(post_quant_conv) => &post_quant_conv.forward(xs)?,
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^-
    |                                       |                          |
    |                                       |                          temporary value is freed at the end of this statement
    |                                       creates a temporary value which is freed while still in use
    |
help: consider using a `let` binding to create a longer lived value
    |
397 ~         let binding = post_quant_conv.forward(xs)?;
398 ~         let xs = match &self.post_quant_conv {
399 |             None => xs,
400 ~             Some(post_quant_conv) => &binding,
    |

For more information about this error, try `rustc --explain E0716`.
error: could not compile `candle-transformers` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

**Comment by LaurentMazare** [comment]
You might have to update your rust toolchain, see #2598

**Comment by profitgrowinginnovator** [comment]
Thanks for the amazingly quick response
