### ISSUE TITLE
[question] decoding onnx model from buf?

### ISSUE THREAD

**Issue by oblivisheee** [huggingface/candle#2669]
Hello, I'm writing a structure to decode model from buf and I've got a question: How i can use `candle_onnx::onnx::ModelProto::decode` out of candle-onnx crate?
I don't want to use `candle_onnx::read_file` because it doesn't fit my needs.
Because now when I'm trying `candle_onnx::onnx::ModelProto::decode` it calls error.
Here is my code:
```rust

pub struct OnnxModel {
    inner: candle_onnx::onnx::ModelProto,
}
impl<'a> Model<'a> for OnnxModel {
    fn deserialize(buf: &[u8]) -> KiroshiResult<Self> {
        use prost::Message;
        Ok(OnnxModel {
            inner: candle_onnx::onnx::ModelProto::decode(buf)?,
        })
    }
}
```

Error:
```
no function or associated item named `decode` found for struct `ModelProto` in the current scope
function or associated item not found in `ModelProto`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B2%5D?2#file%3A%2F%2F%2FUsers%2Foblivisheee%2FDocuments%2FProjects%2Fkiroshi-ai-vision-core%2Fsrc%2Fmodel.rs)
message.rs(17, 1): there are multiple different versions of crate `prost` in the dependency graph
model.rs(27, 51): there is a method `encode` with a similar name: `encode`
```

**Comment by oblivisheee** [comment]
Fixed.

**Comment by raphaelmenges** [comment]
@oblivisheee: May I ask how you fixed this for you?

I managed to call `candle_onnx::onnx::ModelProto::decode` only after adding the exact same version of `prost` to my `Cargo.toml` and adding `use prost::Message;` before the decoding. I think `candle_onnx` should atleast reexport its `prost` dependency such that one does not need to add `prost` to their own dependencies.

**Comment by oblivisheee** [comment]
@raphaelmenges 
Like you, I simply added the same version of prost to `Cargo.toml`. They should definitely re-export prost, at least prost::Message.
