### ISSUE TITLE
phi3::Model::forward => shape mismatch in broadcast_add

### ISSUE THREAD

**Issue by gitced** [huggingface/candle#2685]
Hello,

Newbie here, i'm trying to learn both rust and candle with a small test project: a web page with an input field, and submit button, and an answer field.
chatgpt generated the axum/tokio base, and i adapted the candle/phi3 example code for my TextGeneration.run() function.
The general strategy is that i create one pipeline and then reuse it for every generation.

I have a strange bug:
If i prompt a single token (like "hello"), it works well, i can get as many generations as i want.
But if i prompt multiple tokens (like "lovingly", or any longer prompt), it works once, and crashes the second time with this error:
`shape mismatch in broadcast_add, lhs: [1, 32, 2, 103], rhs: [1, 1, 2, 2]`

Here's the beginning of the trace.
You can see that the first inference of "lovingly" goes well, and the second triggers the panic.

```
E:\rust\candle_as_a_service>cargo run --release --features cuda
   Compiling candle_as_a_service v0.1.0 (E:\rust\candle_as_a_service)
    Finished `release` profile [optimized] target(s) in 2.92s
     Running `target\release\candle_as_a_service.exe`
retrieved the files in 2.4639ms
loaded the model in 2.6557335s
Listening on 127.0.0.1:8000
starting the inference loop
lovingly
100 tokens generated (33.65 token/s)
starting the inference loop
lovinglythread 'tokio-runtime-worker' panicked at src/main.rs:34:45:
Error running text generation: shape mismatch in broadcast_add, lhs: [1, 32, 2, 103], rhs: [1, 1, 2, 2]
   0: std::backtrace_rs::backtrace::dbghelp64::trace
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2: std::backtrace::Backtrace::create
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\backtrace.rs:331
   3: std::backtrace::Backtrace::capture
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\backtrace.rs:296
   4: candle_core::error::Error::bt
   5: candle_core::shape::Shape::broadcast_shape_binary_op
   6: candle_core::tensor::Tensor::broadcast_add
   7: candle_transformers::models::phi3::Model::forward
   8: <F as axum::handler::Handler<(M,T1,T2),S>>::call::{{closure}}
```

I'm quite lost here, any idea of what i can do with that ?
Is there a way to reset the internal pipeline state (if that makes sense) so that every new inference looks like it's the first one ?
I guess i could recreate a new pipeline at every generation, it would certainly solve the issue, but that doesn't seem like a very elegant idea.

Thanks for any help.
Cedric

**Comment by LaurentMazare** [comment]
The phi3 model includes its kv cache so you may want to call `clear_kv_cache` in between the different generations.
If you want to use a model for multiple sessions in parallel, you can just clone the model after creating it, this will results in separate kv cache but the model weights will still be shared.

**Comment by gitced** [comment]
That solved it, thank you so much Laurent :-)
