### ISSUE TITLE
Add ONNX support

### ISSUE THREAD

**Issue by cospectrum** [huggingface/candle#348]
Any plans to support ONNX? An ONNX converter would be very helpful, but implementation details may vary.

I know that [burn](https://github.com/burn-rs/burn/tree/main/burn-import) tries to generate Rust code `from` ONNX and then include it as a module. Codegen provides some performance benefits.

On the other hand, it is possible to create a model `from` ONNX at runtime, similar to [tract](https://github.com/sonos/tract/tree/main/onnx).

Converting `to` ONNX also requires some effort, as branches and loops can introduce errors.

**Comment by Narsil** [comment]
Codegen to create code from ONNX files is definitely something we have been thinking about.
We would have to export the weights to `safetensors` at the same time. 

Exporting to ONNX is indeed a lot more work and not something we plan in the short term.

**Comment by cospectrum** [comment]
I think with codegen from ONNX, weights can be handled in different ways.

Firstly, they can be embedded in the source code during the codegen stage. My only concern is the footprint; for example, in mobile apps, you usually compile for different architectures and then merge binaries together, final size will be huge.

The second approach is to give the user the ability to pass weights as arguments at runtime. This could be in the form of an ONNX file/bytes, `safetensors`, or other data structures.

The ability to run models in both inference mode and training mode, device selection, parallelization, optimization, and other details require solutions as well.

**Comment by askgh69** [comment]
Hey @cospectrum @Narsil , I'm trying to convert pix2struct-doc-vqa base model to ONNX. I am confused as to how to convert both encoder and decoder to one onnx model. I'll be happy to share the code I'm trying to use and also share the error I'm facing. I'm not using the cli commands, I', using torch.onnx.export() instead. Your help is needed.

**Comment by Narsil** [comment]
@askgh69 This is not the correct place to ask for such support.

I'll close this since ONNX support is not on our short term goals:
https://github.com/huggingface/candle/issues/360

**Comment by askgh69** [comment]
Hey @Narsil ! Thanks for reaching out. I'll keep that in mind for the future. Cheers.
