### ISSUE TITLE
Contributing 

### ISSUE THREAD

**Issue by leifu1128** [huggingface/candle#354]
Cool project, I would love to contribute in my free time. What needs to be done at this point?

**Comment by Narsil** [comment]
Hi

Here is a list of things we have in mind in the near future:

https://github.com/huggingface/candle/issues/360

Basically it's about having most of the hot topics covered in the lib and improving DX in general ! 
Any help is welcome.

Also if you want to contribute, it doesn't necessarily means contributing to core directly.
People have mentionned creating youtube videos. Creating pet projects and trying to voice all the things which are not nice/could use some improvement in usability.
Docs and the book could use some help too ! 

Does this answer your question ?

**Comment by nicognaW** [comment]
I'm not skilled but it'd be nice if someone add SDXL support for the stable diffusion example.

**Comment by Narsil** [comment]
@LaurentMazare is on it. He's off this week, which means he only works like 4h a day :).

I'm going to close this so we can keep track of actually opened issues right now.
