### ISSUE TITLE
huggingface/transformers to candle porter

### ISSUE THREAD

**Issue by okpatil4u** [huggingface/candle#358]
Would it possible to build a porter, which can take any huggingface transformer model and convert into rust ?

**Comment by Narsil** [comment]
@okpatil4u I'm not sure it's worth the investment to write a fully blown "porter" that would work on any given model.

If you check out our [examples](https://github.com/huggingface/candle/blob/main/candle-examples/examples/falcon/model.rs) you'll see the code looks a lot like `transformers` already.
Having freedom to rework the code also allows for some flexibility.

For instance we could model the code like this instead: https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py

That being said, maybe having a script that would start the legwork could be interesting !
