### ISSUE TITLE
Version 0.2.0 Features

### ISSUE THREAD

**Issue by Narsil** [huggingface/candle#360]
- [ ] Having Q4 (GGML like) inference
- [x] Stable Diffusion example (not necessarily highly optimized, but functional on CUDA + CPU)
  - [ ] Make it reasonably fast (CUDA at least :) )
- [ ] More unit tests
- [ ] More benchmarks points (M1, CPU, MKL, CUDA, WASM) x  (Whisper, LLama2) at least
- [ ] Optimize CPU backend
- [ ] Better errors for older GPUs (https://github.com/huggingface/candle/issues/353)
- [ ] More complete book (Training loop, adding Cuda debugging/profiling section, adding CPU tracing information at least)
- [ ] `VarBuilder` reconsideration (We know it's not a great abstraction, we just don't have a good replacement idea yet)

**Comment by LaurentMazare** [comment]
Stable diffusion is now functional on cpu, try it out with:
```bash
cargo run --example stable-diffusion --features image --release -- --prompt "a rusty robot holding a fire torch"
```
It's certainly on the slow side so we're currently optimizing it. Next steps include cuda and mkl support.

**Comment by McDonnellJoseph** [comment]
Hey, I love the idea behind this project and I'd like to make some contributions to improve with rust. Do you have any suggestions of how I could help for 0.2.0 ?

**Comment by LaurentMazare** [comment]
Closing stale issues.
