### ISSUE TITLE
Tensor::avg_pool2d not working as expected

### ISSUE THREAD

**Issue by LeeeSe** [huggingface/candle#364]
I'm an ML beginner and a Rust beginner, and I don't know if there's something wrong with my usage or understanding, but the avg_pool2d function doesn't seem to work as expected!

main.rs
```rust
use candle_core::{Device, Tensor};
fn main() {
    let device = Device::Cpu;
    
    let data: Vec<f32> = vec![1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,];
    let t = Tensor::from_vec(data, (1, 1, 4, 4), &device).unwrap();
    
    let pool = t.avg_pool2d((2, 2), (2, 2)).unwrap();
    
    println!("{}", t.to_string());
    println!("{}", pool.to_string());
}
```

output
```
scale:0.25
sum:2
sum:2
sum:2
sum:2
[[[[1., 1., 1., 1.],
   [0., 0., 1., 1.],
   [1., 1., 1., 1.],
   [1., 1., 1., 1.]]]]
Tensor[[1, 1, 4, 4], f32]

[[[[0.5000, 0.5000],
   [0.5000, 0.5000]]]]
Tensor[[1, 1, 2, 2], f32]
```

**Comment by LaurentMazare** [comment]
Thanks for reporting this issue, indeed this is a bug in `avg_pool2d`. I just merged some fix and added your example as a test in #365. Fwiw we've added this operation earlier this week and didn't put any testing which was a mistake. It might still have some bugs so I'll add more tests that check that it's in line with the pytorch output (same as we do for conv), hopefully this will be done later today.
