### ISSUE TITLE
Randn only generates positive numbers

### ISSUE THREAD

**Issue by jakesnell** [huggingface/candle#381]
I can't seem to get randn to generate any negative numbers. Any ideas what is happening here?

Code:
```rust
use anyhow::Result;
use candle_core::{Device, Tensor};

fn main() -> Result<()> {
    let n = 200;
    let t = Tensor::randn(0f32, 1f32, n, &Device::Cpu)?;

    let count = Tensor::sum_all(&Tensor::gt(&t, &Tensor::zeros_like(&t)?)?)?;

    println!("{count} out of {n} elements are > 0");

    Ok(())
}
```

Output:
```
[200]
Tensor[[], u8] out of 200 elements are > 0
```

**Comment by leifu1128** [comment]
The CPU implementation uses [rand](https://docs.rust-embedded.org/cortex-m-rt/0.6.1/rand/index.html)::[distributions](https://docs.rust-embedded.org/cortex-m-rt/0.6.1/rand/distributions/index.html)::[Standard](https://docs.rust-embedded.org/cortex-m-rt/0.6.1/rand/distributions/struct.Standard.html) which generates in the [0, 1) range.

**Comment by jakesnell** [comment]
That makes sense for rand, but I would have expected that randn is drawn from a standard normal?

**Comment by leifu1128** [comment]
It's probably an oversight, I'll make a pr.

**Comment by jakesnell** [comment]
This is the problematic section, right?

https://github.com/huggingface/candle/blob/25ec2d9f6bf36ff51c04f54f6c243828f6f4a8da/candle-core/src/cpu_backend.rs#L2064-L2106

**Comment by leifu1128** [comment]
Should be

**Comment by leifu1128** [comment]
See #382, should be working now.

**Comment by LaurentMazare** [comment]
Thanks for the fix and for the test, this was indeed an oversight because of `Standard` not meaning the standard distribution in the rand crate :)

**Comment by LaurentMazare** [comment]
Closing this as hopefully fixed but feel free to re-open if you run into further issues.

**Comment by jakesnell** [comment]
Thank you, it works for me!
