### ISSUE TITLE
Parameter Grouping

### ISSUE THREAD

**Issue by leifu1128** [huggingface/candle#402]
Optimizers like Lars and Lamb do per-layer weight updates. Is there functionality to group certain parameters together? Pytorch equivalent would be ```nn.ModuleDict```.

**Comment by Narsil** [comment]
Not yet.

However there's nothing blocking it fundamentally if you look at the current SGD implementation: https://github.com/huggingface/candle/blob/main/candle-nn/src/optim.rs
