### ISSUE TITLE
Serialize/Deserialize Varmap in memory

### ISSUE THREAD

**Issue by GiviMAD** [huggingface/candle#410]
Is there any way to serialize a Varmap instance into a u8 vector instead of writing to a file? If not, can it be added?

I'm using candle 0.1.0 and I'm unable to accomplish that.

Thank you in advance.

**Comment by Narsil** [comment]
No, not yet.

For `safetensors` you can use this : https://docs.rs/safetensors/latest/safetensors/tensor/fn.serialize.html directly to get what you want.

**Comment by LaurentMazare** [comment]
What would be your actual use case for this? I just exposed a `.data()` method so that you can retrieve the tensors from a `VarMap` together with their names. I would think than then you can iterate on the tensors, retrieve their contents, and convert the typed data to bytes but depending on specific use cases we might provide helper functions for this.

**Comment by GiviMAD** [comment]
Thank you for the quick response.

> What would be your actual use case for this? I just exposed a `.data()` method so that you can retrieve the tensors from a `VarMap` together with their names. I would think than then you can iterate on the tensors, retrieve their contents, and convert the typed data to bytes but depending on specific use cases we might provide helper functions for this.

Yes, that would allow my to do it, because there is no way to access to the tensor names right now (I nether haven't been able to access to the tensor data to use the workaround suggested by @Narsil which is what I was trying to do, but I think that is my fault). But also having a "save_to_bytes" method that return the same data that is written into the file would be nice, so the serialization/deserialization of the varmap is handled by the library as it's when using a file.

The use case for it it just to add some additional data that is needed for the application to work with-in a single file, so what I was trying to do is to serialize the varmap into a u8 vector and add it as field in another structure that I would then write to a file.

**Comment by LaurentMazare** [comment]
Makes sense, I think for now your best chance is to used the newly introduced `data` and `write_bytes` function, i.e. something like:
```rust
for (name, tensor) in varmap.data().lock().unwrap().iter() {
  // Serialize the name in the way you want.
  tensor.write_bytes(&mut w);
}
```
The downside is that you will need to decide on the "file format" yourself based on how you want to encode the names etc.

**Comment by GiviMAD** [comment]
Thank you for the help and the code sample, I was able to convert the varmap into a seriable structure and backwards.

Waiting for the next release, amazing project :)
