### ISSUE TITLE
error: failed to run custom build command for candle-kernels

### ISSUE THREAD

**Issue by ui-ir** [huggingface/candle#422]
cargo run --example stable-diffusion --features cuda --features image -- --prompt "a rusty robot holding a fire torch"
   Compiling candle-kernels v0.1.0 (HOME/candle/candle-kernels)
error: failed to run custom build command for `candle-kernels v0.1.0 (HOME/candle/candle-kernels)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `HOME/candle/target/debug/build/candle-kernels-c1d996e014c93c27/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rustc-env=CUDA_INCLUDE_DIR=/usr/include
  cargo:rerun-if-changed=src/
  cargo:rerun-if-env-changed=CUDA_COMPUTE_CAP
  cargo:rustc-env=CUDA_COMPUTE_CAP=sm_75

  --- stderr
  src/compatibility.cuh(11): error: identifier "__hmax" is undefined

....

  # stderr
  ', candle-kernels/build.rs:207:13
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
     1: core::panicking::panic_fmt
               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
     2: build_script_build::cuda::build_ptx
     3: build_script_build::main
     4: core::ops::function::FnOnce::call_once

**Comment by ui-ir** [comment]
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

$ uname -a
Linux lenovo 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by LaurentMazare** [comment]
You may want to update to cuda 12 if this is an option on your side. Besides this, note that the stable-diffusion example is not cuda compatible at the moment, this will hopefully be the case in the next few days.

**Comment by ui-ir** [comment]
Hello,
Thanks.

Without cuda, it crashes:

$ cargo run --example stable-diffusion --release --features image -- --prompt "a rusty robot holding a fire torch"
    Finished release [optimized] target(s) in 35.31s
     Running `target/release/examples/stable-diffusion --prompt 'a rusty robot holding a fire torch'`
Running on CPU, to run on GPU, build this example with `--features cuda`
Running with prompt "a rusty robot holding a fire torch".
Building the Clip transformer.
Building the autoencoder.
Building the unet.
Timestep 0/30
Killed

**Comment by LaurentMazare** [comment]
I would think it's likely that the process is running out of memory. Maybe you want to check your `dmesg` or equivalent on linux?

**Comment by ui-ir** [comment]
[  933.048186] [   7533]  1000  7533  3136379  2584247 20901888        0             0 stable-diffusio
[  933.048188] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=containerd.service,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/app.slice/snap.rustup.cargo.8ecddea2-c15c-4539-b7b3-675317b1363d.scope,task=stable-diffusio,pid=7533,uid=1000
[  933.048216] Out of memory: Killed process 7533 (stable-diffusio) total-vm:12545516kB, anon-rss:10336836kB, file-rss:152kB, shmem-rss:0kB, UID:1000 pgtables:20412kB oom_score_adj:0

**Comment by LaurentMazare** [comment]
Looks like it, we're currently using f32 for all the computations in stable-diffusion, it's on the list to support f16 but that will only happen after the gpu support.

**Comment by ui-ir** [comment]
Thanks.

**Comment by NatanFreeman** [comment]
> You may want to update to cuda 12 if this is an option on your side. Besides this, note that the stable-diffusion example is not cuda compatible at the moment, this will hopefully be the case in the next few days.

Upgrading to from CUDA version 11.5.119 to 12.0.140 resolved the issue for me. Maybe a line should be added to the [instillation instructions](https://huggingface.github.io/candle/guide/installation.html) specifying which CUDA versions are supported?
