### ISSUE TITLE
Compiling candle-examples v0.1.0 error

### ISSUE THREAD

**Issue by rockspring** [huggingface/candle#442]
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
   Compiling candle-examples v0.1.0 (~/github.com/huggingface/candle/candle-examples)
error[E0308]: mismatched types
   --> candle-examples/examples/whisper/main.rs:174:21
    |
174 |             .decode(tokens.clone(), true)
    |              ------ ^^^^^^^^^^^^^^ expected `&[u32]`, found `Vec<u32>`
    |              |
    |              arguments to this method are incorrect
    |
    = note: expected reference `&[u32]`
                  found struct `Vec<u32>`
note: method defined here
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokenizers-0.13.4/src/tokenizer/mod.rs:814:12
    |
814 |     pub fn decode(&self, ids: &[u32], skip_special_tokens: bool) -> Result<String> {
    |            ^^^^^^
help: consider borrowing here
    |
174 |             .decode(&tokens.clone(), true)
    |                     +

For more information about this error, try `rustc --explain E0308`.
error: could not compile `candle-examples` (example "whisper") due to previous error

**Comment by LaurentMazare** [comment]
Closing this as we now have released candle 0.1.1 that include the fix.
