### ISSUE TITLE
What is the minimal requirements of Intel MKL version?

### ISSUE THREAD

**Issue by iwanhae** [huggingface/candle#443]
Hello, Thanks for the great work!

I've got an error while compiling with the `-features mkl` option. 
For example `cargo install --git https://github.com/huggingface/candle.git candle-examples --examples bert -F mkl`

The error said
```bash
  = note: /usr/bin/ld: /workspaces/Kuberian/searcher/target/debug/deps/libcandle_core-0afc8671b4dae8af.rlib(candle_core-0afc8671b4dae8af.candle_core.b11884625c01537d-cgu.13.rcgu.o): in function `candle_core::mkl::hgemm':
          /usr/local/cargo/git/checkouts/candle-0c2b4fa9e5801351/60cd155/candle-core/src/mkl.rs:162: undefined reference to `hgemm_'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
```

I initially thought that I did not install intel mkl libs properly, but I found that 
1. [intel-mkl-src](https://github.com/rust-math/intel-mkl-src) automatically downloads the required library from ghcr
2. `intel mkl 2020.01`, which automatically downloaded from [here](https://github.com/rust-math/rust-mkl-container), simply does not implement `hgemm` while they do implement `sgemm` and `dgemm`
3.  the latest version of intel mkl does implement `hgemm`

So I tried the latest version of intel mkl, but it seems `intel-mkl-src` does not support it.

I'm wondering which `intel-mkl` version do you use for your development environment?

**Comment by LaurentMazare** [comment]
I'm using `2023.1.0`, it worked out of the box with `intel-mkl-src` for me, no need to tweak anything.

**Comment by iwanhae** [comment]
Thx, I solved the problem.

For someone who might have trouble like me: 
I'm using a dev container like below, and it works!
```Dockerfile
ARG VARIANT="bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/rust:1-${VARIANT}

RUN wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
| gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null && \
  echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | \
  sudo tee /etc/apt/sources.list.d/oneAPI.list

RUN apt update

# for builder
RUN apt install -y intel-oneapi-mkl-devel
# for runtime environment
RUN apt install -y libomp-dev
```
Just installing `intel-oneapi-mkl` is not enough for static linking.
I recognize my mistake from your hint. Thx @LaurentMazare  :-)

**Comment by akhildevelops** [comment]
Thanks @iwanhae, I was also struggling to run my binary, enabling mkl feature.
`intel-mkl-src` crate fetches [outdated libraries](https://github.com/orgs/rust-math/packages/container/rust-mkl%2Flinux%2Fmkl-static-lp64-iomp/41433181?tag=2020.1-3038006115), if the system doesn't have mkl. 

It didn't worked even when I pointed to [latest ones](https://github.com/rust-math/rust-mkl-container/pkgs/container/rust-mkl%2Flinux%2Fmkl-static-lp64-iomp/124058842?tag=2020.1-6048495329).

Finally I had to download the latest from Intel website as pointed by you.
```bash
apt install -y intel-oneapi-mkl-devel
apt install -y libomp-dev # (This is not from intel)
```

**Comment by nklsla** [comment]
For others who stumble upon this issue:
I got the same error message when I tried to build the `vgg`-example but in my case I had taken out the `candle-examples/vgg/main.rs` along with necessary parts and added it into another project.
The solution for me was suprisingly that I could not build it with the `debug`-mode but as soon as I tried `release`-mode it worked!

I'm quite new to Rust and I cannot explain why this is the case. If anyone do know I would apprecaite an explaination.

**Comment by birajsilwal** [comment]
using `sudo cargo build` and `sudo cargo run` worked for me.

**Comment by nklsla** [comment]
As I progressed into using a docker container the problem rised again. This time I solved thanks to @iwanhae with some slight modifications.
I wanted to use `rust`'s offical docker image which also run on debian, had to remove the `sudo` commands otherwise it was the same, se full `dockerfile` below:


```
FROM rust:latest
WORKDIR /app
COPY /models .

RUN wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
    | gpg --dearmor | tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null \
    && echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | \
    tee /etc/apt/sources.list.d/oneAPI.list \
    && apt-get update \
    && apt-get install -y libomp-dev intel-oneapi-mkl-devel \
    && cargo build --release

CMD ["./target/release/models","linear"]
```
