### ISSUE TITLE
Is `compatibility.cuh` taken from dfdx?

### ISSUE THREAD

**Issue by ViliamVadocz** [huggingface/candle#460]
I was reading through some of the issues and came across #353 which mentions `compatibility.cuh`. I remember writing a file with the same name for [dfdx](https://github.com/coreylowman/dfdx).

- [dfdx `compatibility.cuh`](https://github.com/coreylowman/dfdx/blob/main/src/tensor_ops/utilities/compatibility.cuh)
- [candle `compatibility.cuh`](https://github.com/huggingface/candle/blob/main/candle-kernels/src/compatibility.cuh)

Was the file taken from dfdx and changed?
I am not worried about attribution. I don't think it is necessary as per the relevant licenses.
Instead, I am interested whether anything was changed that dfdx could also benefit from.

Maybe there should be a separate library for cuda kernels so that both libraries could benefit from improvements and bug fixes. Let me know what you think.

**Comment by LaurentMazare** [comment]
Just to mention that this is also discused on the [dfdx discord](https://discord.com/channels/998570811650748417/998570812590260336/1141276673208242209).

**Comment by ViliamVadocz** [comment]
Summary of discussion:
- Yes, the compatiblity header was taken from dfdx. It is also mentioned in a [README](https://github.com/huggingface/candle/blob/main/candle-kernels/README.md).
- The kernels between dfdx and candle are not directly compatible, so there is probably not too much to be gained from distributing them separately.
- The compatibility header [was changed to fix some issues](https://github.com/huggingface/candle/pull/395). This change could be ported to dfdx as well.
