### ISSUE TITLE
Why is `candle_nn` not re-exported by `candle_core`?

### ISSUE THREAD

**Issue by ViliamVadocz** [huggingface/candle#461]
It took me a while to figure out I should add `candle_nn` as a dependency separately to get access to types such as `VarBuilder`. It was additionally confusing because the examples use crates with different names, such as `candle` instead of `candle_core`: https://github.com/huggingface/candle/blob/main/candle-examples/examples/mnist-training/main.rs#L7

Is the intent to have `candle_nn` as its own crate or is this an oversight? Please share your insight.

**Comment by mirrironline** [comment]
because the examples use their own workspace context (`~/Cargo.toml`) where `candle = { path = "../candle-core", version = "0.1.1", package = "candle-core" }`.

If you want to replicate the examples make sure to add each module individually.

**Comment by mirrironline** [comment]
relevant: https://github.com/huggingface/candle/issues/446#issuecomment-1678536334

**Comment by LaurentMazare** [comment]
Exactly, the goal is to have smaller/composable crate, though we might decide to group more things at some point or to split in even more crates, it will really depend on how things evolve.
Closing this for now, feel free to open other issues if needed or join the discord server for general discussion.
