### ISSUE TITLE
Quick Tensor creation functions

### ISSUE THREAD

**Issue by okpatil4u** [huggingface/candle#477]
Converting Tensor to vector is pretty straightforward. Is there any easy way for taking a vector and converting it into a Tensor ?

**Comment by LaurentMazare** [comment]
There are various ways to create a tensor object from a vec/slice:
- `Tensor::from_vec(vec![1f32, 2f32, 3f32, 4f32], (2, 2), &Device::Cpu)`: this creates a 2D vector with 2 rows and 2 columns by passing ownership of the argument vector.
- `Tensor::from_slice(&[1f32, 2f32, 3f32, 4f32], (2, 2), &Device::Cpu)`: similar but without passing ownership.
- `Tensor::new(&[1f32, 2f32, 3f32, 4f32], &Device::Cpu)`: this one would infer the shape from the argument, i.e. in this case it would be a 1d vector but you can get a 2d vector via `Tensor::new(&[[1f32, 2f32], [3f32, 4f32]], &Device::Cpu)`

**Comment by okpatil4u** [comment]
I will try this out, thanks !!
