### ISSUE TITLE
Equivalent of torch.add function

### ISSUE THREAD

**Issue by okpatil4u** [huggingface/candle#478]
I am trying to write a code similar to the following

```
import torch
a = torch.ones((4, 8, 32))
b = torch.ones((8,32))
print(a+b)
```

For following code

```
use candle::*;
fn main() -> Result<()> {
    let a = Tensor::randn(0f32, 1., (4,8, 32), &Device::Cpu)?;
    let b = Tensor::randn(0f32, 1., (8, 32), &Device::Cpu)?;

    let c = a.add(&b)?;
    println!("{c}");
    Ok(())
}

```

I am getting this error. Am I missing something ?

`ShapeMismatchBinaryOp { lhs: [4, 8, 32], rhs: [8, 32], op: "add" }`

**Comment by LaurentMazare** [comment]
Right, additions don't broadcast by default in candle, you can do `a.broadcast_add(b)?` in this case.

**Comment by okpatil4u** [comment]
Yes. It's working like a charm. Thank you !!
