### ISSUE TITLE
cargo run --example whisper --release compile error!

### ISSUE THREAD

**Issue by exceedzhang** [huggingface/candle#484]
rustc 1.71.1 (eb26296b5 2023-08-03)

error: failed to run custom build command for `ring v0.16.20`

<img width="983" alt="image" src="https://github.com/huggingface/candle/assets/4583537/404eed27-f115-4722-a882-ecfa67e6a9dd">
new version:
<img width="976" alt="image" src="https://github.com/huggingface/candle/assets/4583537/30e49a90-039c-44a1-b7b1-c7e8bcfa4397">

**Comment by LaurentMazare** [comment]
I feel that this is more a general rust setup issue rather than something related to this crate (maybe something to do with some cross compilation setup). Maybe you can try building the `ring` crate separately and I would think that the issue would happen there too without candle being involved.

**Comment by LaurentMazare** [comment]
Closing this as it doesn't seem candle specific but feel free to re-open if you run into further issues / can provide more details.
