### ISSUE TITLE
Error while building on arm64 due to candle-gemm-f16

### ISSUE THREAD

**Issue by GiviMAD** [huggingface/candle#494]
I'm using candle-core and candle-nn as dependencies and I can not build my project on an arm64 machine. (version 0.1.1)

I have just added the final log part.

All the errors seems to point to the file candle-gemm-f16/src/microkernel.rs.

```
...
note: instantiated into assembly here
   --> <inline asm>:1:2
    |
1   |     fmul v4.8h, v8.8h, v3.8h
    |     ^

error: instruction requires: fullfp16
   --> /code/vendor/candle-gemm-f16/src/microkernel.rs:364:18
    |
364 |                 "fmul {0:v}.8h, {1:v}.8h, {2:v}.8h",
    |                  ^
    |
note: instantiated into assembly here
   --> <inline asm>:1:2
    |
1   |     fmul v2.8h, v8.8h, v1.8h
    |     ^

error: instruction requires: fullfp16
   --> /code/vendor/candle-gemm-f16/src/microkernel.rs:364:18
    |
364 |                 "fmul {0:v}.8h, {1:v}.8h, {2:v}.8h",
    |                  ^
    |
note: instantiated into assembly here
   --> <inline asm>:1:2
    |
1   |     fmul v1.8h, v8.8h, v0.8h
    |     ^

...

error: could not compile `candle-gemm-f16` (lib) due to 1141 previous errors
warning: build failed, waiting for other jobs to finish...
```

Seems there is no way to disable f16 support, please let me know if I'm wrong. That will be nice as I'm not using it, but I don't know if there is another solution to compile the project for arm/arm64 devices.

Thank you for the help.

**Comment by GiviMAD** [comment]
Seems like I'm able to build by passing RUSTFLAGS='-C target-feature=+fp16', but the effect is quite unclear to me.

**Comment by GiviMAD** [comment]
Seems to have no effect as I'm using the build in a raspberry pi 3 which I think does not support that, not sure about it. Anyway closing the issue.

BR

**Comment by Narsil** [comment]
Could you print the output of `rustc --print cfg -C target-cpu=native` on your raspberry ?

I think we're missing a compilation flag here.

**Comment by GiviMAD** [comment]
I didn't try to build in the raspberry pi, I first faced the issue while compiling in a docker build with the rust arm64 buster docker hub image, I though it could be because of the use of Qemu so I replicated the issue in a Orange Pi 5 board I got at the result was the same (tested also outside docker).

This is the output on the Orange PI 5:

```
***@orangepi5:~$ rustc --print cfg -C target-cpu=native
debug_assertions
panic="unwind"
target_arch="aarch64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="aes"
target_feature="crc"
target_feature="dotprod"
target_feature="dpb"
target_feature="fp16"
target_feature="lor"
target_feature="lse"
target_feature="neon"
target_feature="pan"
target_feature="pmuv3"
target_feature="ras"
target_feature="rcpc"
target_feature="rdm"
target_feature="sha2"
target_feature="ssbs"
target_feature="vh"
target_has_atomic="128"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="linux"
target_pointer_width="64"
target_vendor="unknown"
unix
```

**Comment by Narsil** [comment]
```
target_feature="fp16"
```
Interesting, the CPU thinks it has it..

```
target_feature="neon"
```
Is the flag we use to determine SIMD support, although f16 SIMD support might be event different

I must admit we mostly look at M1 when supporting `aarch64`.
I don't like using qemu for this sort of low level stuff, I never know if it's the emulation layer or the hardware that fails.

**Comment by GiviMAD** [comment]
Yes, I chose to use docker for the cross compilation in the CI because the crate depends on some native libraries and it simplifies the setup, apart from allowing me to run build for those platforms on my laptop if I needed it, but yes it's a problem when something fails, verifying outside Docker is the first thing I tend to do.

Maybe the feature is enabled by default when using the target aarch64-apple-darwin but not in aarch64-unknown-linux-gnu. It's the only think that makes sense for me, because I not using the cpu native option in any of the builds as I want the binary for distribution. 

I also have a build for the target aarch64-apple-darwin in the GitHub CI and it had passed without specifying any flag, so I should have open the issue just pointing to linux, my fault.

**Comment by GiviMAD** [comment]
> Maybe the feature is enabled by default when using the target aarch64-apple-darwin but not in aarch64-unknown-linux-gnu.

Seems to be something like that when I run `rustc --print target-cpus` in my debian machine, the default target is "generic" but is not the case on my Mac where it's "core2" (I still have an Intel Mac).

Thank you for pointing to it, it got me totally lost.
