### ISSUE TITLE
Support for broadcast matmul

### ISSUE THREAD

**Issue by louisfd** [huggingface/candle#513]
If I understand correctly, for now matmul needs batch dimensions to be exactly the same. Taken from candle_core::tensor doc:
`b1, b2, ..., bi, m, k` x `b1, b2, ..., bi, k, n` -> `b1, b2, ..., bi, m, n`
This is batch matrix multiplication (like [torch.bmm](https://pytorch.org/docs/stable/generated/torch.bmm.html)). 

It would be great to support broadcast, as in [torch.matmul](https://pytorch.org/docs/stable/generated/torch.matmul.html): "For example, if input is a (j×1×n×n) tensor and other is a (k×n×n) tensor, out will be a (j×k×n×n) tensor."

**Comment by LaurentMazare** [comment]
Right, could you give a try to #523 and see if it would fit your use case? (Ops are non broadcasting by default in candle as it's really easy to shot yourself in the foot with broadcasting but some have broadcasting variants).
