### ISSUE TITLE
Support for signed integer

### ISSUE THREAD

**Issue by louisfd** [huggingface/candle#514]
It would be useful to have the possibility to have a signed integer DType. 
In candle_core::dtype there is already support for many float types and unsigned int, but no signed int option. 
I suggest we add i32.

**Comment by LaurentMazare** [comment]
Right, being limited to `u32` is likely to be restrictive at some point so we're considering the different options here, the trickiness is that it adds quite some complexity to all our backends so we have to think a bit more about it before commiting to this.

**Comment by louisfd** [comment]
Okay, I thought it would be simple. Take your time! 😄

**Comment by LaurentMazare** [comment]
Out of curiosity did you have any specifics in mind when suggesting `i32`, I would slightly lean towards doing `i64` (akin to PyTorch `LongStorage`), on the upside it will cope up with potentially more models, and on the downside it will be less efficient but I wouldn't expect models to very heavily manipulate these - and having the two of them is a bit more burden - though long term maybe that's what will happen.

**Comment by LaurentMazare** [comment]
Just merged #563 which adds support for i64. Give it a spin when you can and please let us know how it gets!

**Comment by louisfd** [comment]
It's good, thank you!
