### ISSUE TITLE
Potentially incorrect outputs for q4_0 llama 7B

### ISSUE THREAD

**Issue by jafioti** [huggingface/candle#531]
When running the ggml example for llama, using llama-2-7b.ggmlv3.q4_0.bin, I get the following output:
```
My favorite theorem is 100% of the time. nobody knows what it means. everybody knows it. nobody knows it. nobody knows it. It's a theorem.
I's a theorem.
I's a theorem
I's a theorem
I'm a theorem
I'm a theorem
I'm a theorem
I'm a theorem
I'm a theorem
I'm a theorem
I'm a theorem
I'm a theorem
```
This doesn't seem correct, so there might be some mismatches in the operations. I'm not using any temperature setting

**Comment by LaurentMazare** [comment]
Which version are you currently using? If it's not the latest github version could you update? I merged #518 yesterday which lines up the output quite well with the llama.cpp one and before that there was a bug in the rope embeddings computation. The PR description has a couple generated texts that you may want to compare too.

**Comment by LaurentMazare** [comment]
Also just to mention that with the latest tip, the generated text at temp 0 seems to match well for the model you mention too as long as the repeat penalty is set to 1. (so disabled as it doesn't exist for now on the candle side).
```
./main -m llama-2-7b.ggmlv3.q4_0.bin --prompt "My favorite theorem is " --temp 0 --verbose-prompt  --repeat-penalty 1.0
```

**Comment by LaurentMazare** [comment]
Closing this as hopefully it's fixed but feel free to re-open if there are still some problems (or open new issues).
