### ISSUE TITLE
How to convert token to text?

### ISSUE THREAD

**Issue by soupslurpr** [huggingface/candle#533]
Hello, thank you for this ML library in Rust. Sorry if this is a noob question, I'm new to machine learning and this is my first time trying to use a text generation model. I'm using the latest git version. In the quantized llama example, how would I convert a token to a string? I see the print_token function but I want to convert it to a string and maybe push to a vector so I can return all the generated text when it is finished processing.

**Comment by LaurentMazare** [comment]
The llama quantized example is a bit hacky here: it decodes the token independently so as to stream them back to the user but this is not correct in general as the decoding might depend of surrounding token.
What you probably want to do is store the tokens in a vector of `u32` and convert all of them to the generated text when finished processing, you can see this done for example in the [falcon model](https://github.com/huggingface/candle/blob/912561614f0fb0fc1e9ccff49448d3d2a85302ce/candle-examples/examples/falcon/main.rs#L82).

**Comment by soupslurpr** [comment]
Thanks, that seemed to have worked, except the first generated token is not included for some reason. I did this:

```
    let mut new_tokens = vec![];
    for index in 0..to_sample {
        let input = Tensor::new(&[next_token], &Device::Cpu)?.unsqueeze(0)?;
        let logits = model.forward(&input, prompt_tokens.len() + index)?;
        let logits = logits.squeeze(0)?;
        next_token = logits_processor.sample(&logits)?;
        print_token(next_token, &tokenizer);
        // push token converted to string to a vector.
        new_tokens.push(next_token);
    }
    let dt = start_post_prompt.elapsed();
    println!(
        "\n\n{:4} prompt tokens processed: {:.2} token/s",
        prompt_tokens.len(),
        prompt_tokens.len() as f64 / prompt_dt.as_secs_f64(),
    );
    println!(
        "{:4} tokens generated: {:.2} token/s",
        to_sample,
        to_sample as f64 / dt.as_secs_f64(),
    );
    println!("{}", tokenizer.decode(&new_tokens, false).unwrap()); // TODO: use map_err or something else instead of unwrap
```

**Comment by LaurentMazare** [comment]
Maybe use the following for your first line?
```rust
let mut new_tokens = vec![next_token];
```

**Comment by soupslurpr** [comment]
Ah that worked, thank you. I guess I'll close the issue now.
