### ISSUE TITLE
How to disable openssl-sys being included?

### ISSUE THREAD

**Issue by soupslurpr** [huggingface/candle#538]
I would like to stop openssl-sys from being included in my project when using candle, I'm not sure how to do this. I tried adding the below to my Cargo.toml but it didn't change anything. The reason I want to do it is because I get an error when trying to compile my library to aarch64-linux-android saying that pkg-config has not been configured to support cross-compilation and that I should install a sysroot for the target platform, but I'd like to not include it anyways since I won't be needing it and will be loading everything locally. Thanks.

```
hf-hub = { version = "0.2.0", default-features = false }
tokenizers = { version = "0.13.4", default-features = false }
```

**Comment by LaurentMazare** [comment]
@Narsil will know better on this, for tokenizers I'm not sure why it would require `openssl-sys` when used with no-default features (I only see the `http` feature triggering `reqwest` which would trigger this), maybe you can inspect your `Cargo.lock` file to understand this and if it doesn't make sense to have this dependency report it upstream.
When it comes to `hf-hub`, you should not have this dependency when using the base crates (`candle-core` and `candle-nn`), it's actually used in `candle-examples` so maybe it's what you're trying to build here. I would be a bit reluctant to feature gate it here as it's used by every model and maintaining feature gates is a bit painful. Longer term we may move the models to `candle-transformers` and then have no dependency on `hf-hub` from there, in the meantime maybe you can just edit the examples that you care about to not use the hub and compile them without?

**Comment by Narsil** [comment]
I confirm, `tokenizers` with default-features off shoudln't require `openssl-sys`.

Unless another crate adds the dependency, I don't see where it would be coming from.
As laurent suggest, try building `candle-core`  and `candle-nn` independantly, it should work without yelling.

**Comment by soupslurpr** [comment]
Thanks @LaurentMazare and @Narsil, looking at the Cargo.lock file was useful. I saw that candle-transformers was the one that was depending on hf-hub, so I removed it and now openssl is not in the Cargo.lock file anymore. Though when compiling, tokenizers gets the following errors.

```
error[E0432]: unresolved import `onig`
 --> C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokenizers-0.13.4\src\utils\onig.rs:3:5
  |
3 | use onig::Regex;
  |     ^^^^ help: a similar path exists: `super::onig`

error[E0433]: failed to resolve: use of undeclared crate or module `onig`
  --> C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokenizers-0.13.4\src\utils\onig.rs:12:60
   |
12 |     pub fn find_iter<'r, 't>(&'r self, inside: &'t str) -> onig::FindMatches<'r, 't> {
   |                                                            ^^^^ use of undeclared crate or module `onig`

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `tokenizers` (lib) due to 2 previous errors
```

**Comment by soupslurpr** [comment]
Ah, I just had to add the onig feature for tokenizers. `cargo add tokenizers --features onig`.

But now I realized that candle-transformers is needed for logitsprocessor. I tried disabling default features for it, but it seems it adds hf-hub as a dependency anyways.

**Comment by LaurentMazare** [comment]
Right, but this was an overlook as candle-transformers actually doesn't use either of these dependencies (totally my bad). I've removed them so if you use the latest github version you should hopefully be fine. If you use the crates.io version I would suggest just copying the logitprocessor bits for the time being as they are fairly small.

**Comment by soupslurpr** [comment]
Oh, I see. I am using the latest github version and openssl is gone now. :)
