### ISSUE TITLE
How to turn off automatic translation for whisper

### ISSUE THREAD

**Issue by LeeeSe** [huggingface/candle#547]
When I input Chinese wav file , whisper outputs the English translation
```
ls@LeeeSes-MacBook-Air ~/r/candle (main)> cargo run --release --features accelerate --example whisper -- --model small --language zh --input /Users/ls/Downloads/output.wav
    Finished release [optimized] target(s) in 0.38s
     Running `target/release/examples/whisper --model small --language zh --input /Users/ls/Downloads/output.wav`
Running on CPU, to run on GPU, build this example with `--features cuda`
loaded wav data: Header { audio_format: 1, channel_count: 1, sampling_rate: 16000, bytes_per_second: 32000, bytes_per_sample: 2, bits_per_sample: 16 }
pcm data loaded 287216
loaded mel: [1, 80, 4500]
0.0s -- 30.0s:  This is a free online audio recorder application program. You can record sound from microphone. After recording, you can edit sound and edit any parts, adjust the balance and sound. Let's use the recording first.
30.0s -- 45.0s:  I'm sorry.
```

**Comment by LaurentMazare** [comment]
Could you try using `--task transcribe`? The default is similar to the python implementation which doesn't choose between `transcribe` and `translate` so it's hard to know what the model will do, but you can force it with this `--task` flag.
If it's still translating with this flag, maybe you can share the audio file so that we can investigate.

**Comment by LeeeSe** [comment]
是的我以前已经尝试过几乎所有参数，包括 `--task` ，但仍然只输出英文

这段录音是我通过ffmpeg录制的
```
ffmpeg -f avfoundation -i ":0" -ar 16000 -acodec pcm_s16le -ac 1 output.wav
```
你可以通过此链接下载：[output.wav](https://drive.google.com/file/d/1WUbfv8c7sNc6N0JTf2zRT8Q_WylA--NR/view?usp=drive_link)

**Comment by LaurentMazare** [comment]
Could you make the link public? Seems to be access controlled at the moment.

**Comment by LeeeSe** [comment]
Sorry, this is the first time I've used Google Cloud Drive to share files, and now I think I've managed to open up the permissions.

**Comment by LaurentMazare** [comment]
Turns out we were putting the `transcribe` token after the language one rather than before which was causing this issue. I just merged #553 that gets around this. I'm not sure if it works properly now but at least it doesn't return english anymore.
Note that you will have to pass the `--task transcribe` flag to get this to work.
```bash
$ ./whisper --input output.wav --model tiny --language zh --task transcribe
loaded wav data: Header { audio_format: 1, channel_count: 1, sampling_rate: 16000, bytes_per_second: 32000, bytes_per_sample: 2, bits_per_sample: 16 }
pcm data loaded 287216
loaded mel: [1, 80, 4500]
0.0s -- 30.0s: 这是一个免费的在现因品记录器型程序可以从卖个风记录声音轮音完成后你可以编辑音轨修简日和片段调整据很气和声音混响快使用在现录音吧
```

**Comment by LeeeSe** [comment]
Works, but lacks punctuation

**Comment by LaurentMazare** [comment]
Fwiw here is what the python version from open ai returns for the same model (tiny),
```
text='正是一个免费的在现因品记录器型程序可以从卖个风记录声音轮音完成后你可以编辑音轨休言日后片段调整据空气和声音会想快使用在现录音吧'
```
A bit tricky for me to align these but they don't seem very different besides the first character? Maybe this whisper model doesn't support punctuation for chinese? Or maybe there is some special option to be turned on so as to generate these.

**Comment by LeeeSe** [comment]
I see, looks like I didn't fully explore before asking the question, thanks for your great work!
