### ISSUE TITLE
missing library 'cute/algorithm/copy.hpp' when using flash attention in stable diffusion example

### ISSUE THREAD

**Issue by xffxff** [huggingface/candle#581]
I encountered an error while trying to run the stable diffusion example with flash attention. I used the following command mentioned in [this comment](https://github.com/huggingface/candle/issues/567#issuecomment-1690011960):

```sh
cargo run --example stable-diffusion --profile=release-with-debug --features cudnn --features flash-attn -- --prompt "a photorealistic very rusty robot" --use-flash-attn
```

However, I received the following error message:

```
kernels/flash_fwd_kernel.h:8:10: fatal error: cute/algorithm/copy.hpp: No such file or directory
  8 | #include <cute/algorithm/copy.hpp>
    |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

It looks like missing some library. I have tried searching for a solution online but haven't been successful so far. The command works fine when I use the `--features cudnn` flag alone.

The output of `nvcc --version` is:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```

**Comment by LaurentMazare** [comment]
Did you initialize the submodules for the repo? This repo embeds cutlass as a submodule that should include cute. Maybe you want to run this at the top level of the repo.
```bash
git submodule update --init
```

**Comment by xffxff** [comment]
> Did you initialize the submodules for the repo? This repo embeds cutlass as a submodule that should include cute. Maybe you want to run this at the top level of the repo.
> 
> ```
> git submodule update --init
> ```

It works now, thank you for such a quick reply.

With flash attention, it's so much faster!

(with flash attention)
![image](https://github.com/huggingface/candle/assets/30254428/f149a4be-2d79-437a-b06d-efce1f60de14)

(without flash attention)
![image](https://github.com/huggingface/candle/assets/30254428/60d1b047-0c93-427d-adcf-a817a60ae28a)
