### ISSUE TITLE
Type issue: `candle_core::tensor::Tensor` vs `candle_core::Tensor`

### ISSUE THREAD

**Issue by AnubhabB** [huggingface/candle#618]
I might be missing something very basic here, but getting the following issue trying define `forward` for a `candle_nn::Linear` layer:
```
`candle_core::Tensor` and `candle_core::tensor::Tensor` have similar names, but are actually distinct types
perhaps two different versions of crate `candle_core` are being used?`
```

My `cargo.toml` looks like this:
```
[dependencies]
anyhow      = "1"
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.1.3", features = ["cuda"] }
candle-nn   = "0"
```

I have a simple definition like this:
```
use anyhow::Result;
use candle_core::Tensor;
use candle_nn::{Linear, VarBuilder, linear, Module};

struct Hello {
    w: Linear
}

impl Hello {
    pub fn load(vb: VarBuilder) -> Result<Self> {
        let w = linear(16, 1024, vb.pp("some.weight"))?;

        Ok(Self {
            w
        })
    }

    pub fn forward(&self, x: &Tensor) -> Result<Tensor> {
        // the problem: `x` is of type candle_core::Tensor but forward expects `candle_core::tensor::Tensor` which is private
        let y = self.w.forward(x)?;

        return Ok(y)
    }
}
```

Any tips for a proper way to set this up would be of great help.

**Comment by AnubhabB** [comment]
So adding `candle_nn` with `cargo add --git https://github.com/huggingface/candle.git candle-nn` resolves this.

Closing this.

**Comment by EndlessReform** [comment]
Ran into a similar problem with `candle_datasets::Batcher::new_r2`. Turns out I was using `candle_core` from Git and the other libraries from the published Cargo version. Putting them all to the same source fixed it for me.
