### ISSUE TITLE
How do I set number of threads in candle ?

### ISSUE THREAD

**Issue by okpatil4u** [huggingface/candle#626]
As in [set_num_threads](https://pytorch.org/docs/stable/generated/torch.set_num_threads.html) equivalent.

**Comment by LaurentMazare** [comment]
Depends on the backend, if you don't use mkl, then `RAYON_NUM_THREADS` if you use mkl then `OMP_NUM_THREADS`.

**Comment by okpatil4u** [comment]
Thanks !
