### ISSUE TITLE
Asset 404 about the llama2 wasm examples

### ISSUE THREAD

**Issue by hanzooo** [huggingface/candle#639]
## Description

Follow example to start a test server for llama2 wasm example, got error(fetch asset 404).

```
For LLaMA2, run the following command to retrieve the weight files and start a
test server:

cd candle-wasm-examples/llama2-c
wget https://huggingface.co/spaces/lmz/candle-llama2/resolve/main/model.bin
wget https://huggingface.co/spaces/lmz/candle-llama2/resolve/main/tokenizer.json
trunk serve --release --public-url /candle-llama2/ --port 8081

And then head over to
[http://localhost:8081/candle-llama2](http://localhost:8081/candle-llama2).

```
<img width="524" alt="image" src="https://github.com/huggingface/candle/assets/16368939/ebcffbe8-83aa-4f65-b11f-e0d6bf0fe0a5">

After removed `--public-url /candle-llama2/`, and use the base path`http://localhost:8081`, it works fine.

**Comment by LaurentMazare** [comment]
Thanks for reporting, we've tweaked this recently I'll fix the readme instructions.

**Comment by LaurentMazare** [comment]
Closing this as hopefully not an issue anymore with the new instructions.
