### ISSUE TITLE
Support for powf 

### ISSUE THREAD

**Issue by louisfd** [huggingface/candle#660]
Support element-wise power function on tensors:
`tensor.powf(x)` where x is a scalar. 

Similar to https://pytorch.org/docs/stable/generated/torch.pow.html when exponent is a scalar value.

**Comment by LaurentMazare** [comment]
Could you expand a bit more on what you would use this for?
In particular I'm wondering how important it is to support integer tensors on this, integer powers, etc.
(also obviously a quick workaround at the moment would be `(tensor.log()? * x)?.exp()?` though it's certainly inefficient and may have numerical precision issues)

**Comment by louisfd** [comment]
The workaround does the job, thanks. 
I only use it on floats, but I use it rather often so it would indeed benefit from having its own kernel.

**Comment by LaurentMazare** [comment]
Just merged #664 that adds this as a specialized op so hopefully this will be more efficient. Note that however we'll probably want to limit the number of basic ops so may well convert this back to being the workaround version at some point (but this shouldn't involve any user facing change).

**Comment by LaurentMazare** [comment]
Closing as complete but feel free to re-open if needed or to open a fresh issue.
