### ISSUE TITLE
Support for slice assign

### ISSUE THREAD

**Issue by louisfd** [huggingface/candle#663]
Slice assignment: assigns the selected elements corresponding for the given ranges to the given value.

For instance,  suppose tensor is [[0.0, 1.0, 2.0], [3.0, 4.0, 5.0]] and value is [[10.0, 5.0]]
Then tensor.slice_assign([1..2, 0..2], value) would give [[0.0, 1.0, 2.0], [10.0, 5.0, 5.0]]

In Torch, one would do
tensor[1..2, 0..2] = value

This would be a great feature to have. I think it is not currently achievable with the public API, although I might have missed something. Thanks.

**Comment by LaurentMazare** [comment]
Right, I have to say that I'm not super thrilled by the idea of supporting this: tensor mutations are very hard to reason about, especially as tensors can be "views" on other tensors, so we prefer favoring a functional style and currently mutations are only allowed on `Var` (which are the tensors used for weights etc).
Would be good to know about specific use cases where this has an advantage over a functional way of doing things (e.g. you can check our `yolo-v8` and `yolo-v3` example where some assignment like this have been converted to `Tensor::cat` operations).

**Comment by leifu1128** [comment]
I think for scalar ```value``` it could be a good abstraction over creating a mask and chaining ```.where_cond()``` and ```.broadcast_as()``` separately. I'm not sure how stuff works under the hood, but creating a mask tensor just to update values does not seem efficient. Unless there is some easier way to assign specific elements I'm missing?

**Comment by louisfd** [comment]
@LaurentMazare I'm sorry, I realize my message did indeed hint that I was asking for a mutating op, but that's not actually what I need (the torch example is the best I could find). 

Just a function such as `let new_tensor = slice_assign(tensor, ranges, value)` or the like would be great!

**Comment by LaurentMazare** [comment]
Ah right, indeed this could be made in a non mutable way, let me think a bit about how we could provide that, there is always this tradeoff of re-using existing ops vs having something native but I doubt efficiency would be much of a concern here. Would be great if you have specific models where you want to use this so as to get a sense of how much this ends up in the hot loop.

**Comment by LaurentMazare** [comment]
Sorry for the late reply here but we just merged #927 that provides a `slice_scatter` operation (which is a simplified version of the pytorch one), hopefully this will do what you need here - it should be very close t othe `slice_assign` that you suggested.
You can see it in action in this [test](https://github.com/huggingface/candle/blob/8601537e31af610c0bbd32ee8c8ee17ed802427c/candle-core/tests/tensor_tests.rs#L677), let us know how it goes. Also please note that the current version is much more efficient when using the first dimension that when using other ones - we may optimize the other cases if it starts to be an issue.

**Comment by LaurentMazare** [comment]
Closing this as hopefully it's all good now. Feel free to re-open if some bits are still missing (or create a new issue).

**Comment by louisfd** [comment]
Hi, 
Sorry for my lateness, I have been working on other things in the last months. I've been juggling with slice_scatter for a while but I don't seem to be able to do what I need, see #1351. Thanks!
