### ISSUE TITLE
MatMulNonContiguous Cuda Error when multiply tensors

### ISSUE THREAD

**Issue by Ssslakter** [huggingface/candle#680]
Hi, the code below shows how to get the error from cuda about non-contiguous matrix multiplication, though I believe this should work since I just want to multiply two zero matrices
```rust
use candle_core::{DType, Device, Result, Tensor};

fn main() -> Result<()> {
    // Use Device::new_cuda(0)?; to use the GPU.
    let device = Device::new_cuda(0)?;

    let a = Tensor::randn(0f32, 1., (2, 2), &device)?;
    let b = Tensor::randn(0f32, 1., (2, 2), &device)?;

    let c = a.matmul(&b)?;

    println!("Digit {c:?} digit");

    let a = Tensor::zeros((1, 2), DType::F32, &device)?;
    let b = Tensor::zeros((2, 2), DType::F32, &device)?;

    let c = a.matmul(&b);
    
    // will print Digit Err(WithBacktrace { inner: Cuda(MatMulNonContiguous { lhs_stride: [0, 0], rhs_stride: [0, 0], mnk: (1, 2, 2) }), ...
    println!("Digit {c:?} digit");
    Ok(())
}
```
I tried to understand the part with gemm algorithms, but it's too hard just from reading the nvidia docs. 
The problem is with the `Tensor.layout.stride`  being just zeros in `Tensor::zeros`
The same happens with `Tensor::ones`.

_Machine info:
GPU - RTX 2060 
Windows 10
Cuda v11.8_

**Comment by LaurentMazare** [comment]
The `Tensor::zeros` function broadcast the zeros rather than creating a dense matrix with them (which would be contiguous), this explains the issue you're seeing. You probably just want to call `.contiguous()?` after creating the matrixes that you want to ensure are contiguous - maybe at some point this will be done automatically for you by `matmul` but for now we prefer erring on the explicit side.

**Comment by Ssslakter** [comment]
Ok, I see, I guess I was misleaded by the example from the book https://huggingface.github.io/candle/guide/hello_world.html which does not have a .`contiguous()?` before creating the model

**Comment by LaurentMazare** [comment]
Right, that's indeed a bit of a bummer than the default examples don't work on cuda. @Narsil what do you think? The easiest fix would probably be to replace the `zeros` with `randn` in the examples, would that sound reasonable to you?

**Comment by Narsil** [comment]
Very reasonable.

I'm torned on the `zeros` being broadcast tbh too.
I see why not allocating is a plus, but on the other hand it's very pratical when filling in a tensors from parts.

Let's just use `randn` for simplicity for now.

**Comment by RileySeaburg** [comment]
For those still scratching their heads...

This code works

```rust
use candle_core::{DType, Device, Result, Tensor};

struct Model {
    first: Tensor,
    second: Tensor,
}

impl Model {
    fn forward(&self, image: &Tensor) -> Result<Tensor> {
        let x = image.matmul(&self.first)?;
        let x = x.relu()?;
        x.matmul(&self.second)
    }
}

fn main() -> Result<()> {
    // use Device::new_cuda(0)?; to use the GPU.
    let device = match Device::new_cuda(0) {
        Ok(device) => device,
        Err(_) => Device::Cpu,
    };

    let first = Tensor::zeros((784, 100), DType::F32, &device)
        .unwrap()
        .contiguous()?;
    let second = Tensor::zeros((100, 10), DType::F32, &device)
        .unwrap()
        .contiguous()?;
    let model = Model { first, second };

    let dummy_image = Tensor::zeros((1, 784), DType::F32, &device)
        .unwrap()
        .contiguous()?;

    let digit = model.forward(&dummy_image)?;

    println!("Digit {digit:?} digit");

    Ok(())
}

```
