### ISSUE TITLE
Error: no cuda implementation for qmatmul

### ISSUE THREAD

**Issue by Pyroglyph** [huggingface/candle#696]
I'm not familiar with CUDA, so apologies if this turns out to be user error.

I've taken the [quantized LLaMA example](https://github.com/huggingface/candle/tree/main/candle-examples/examples/quantized) and placed it in a new project. By default it uses the CPU, and that works fine. However, when I modify it to use my GPU instead, I get this error: `Error: no cuda implementation for qmatmul`.

I have both CUDA (12.2) and cuDNN (8.9.4.25) installed, and both of those features are also enabled on the crate. My NVidia drivers are also up-to-date (537.13) and I have a recent card (RTX 3080), so as far as I'm aware it should be working.

Is this a bug with Candle or am I missing something?

<details><summary>Changes</summary>

main.rs:
```rs
use once_cell::sync::Lazy;
pub static DEVICE: Lazy<Device> = Lazy::new(|| Device::new_cuda(0).unwrap());
```

model.rs:
```rs
crate::DEVICE
```

And in both files:
```diff
- &Device::Cpu
+ &DEVICE
```

</details>

**Comment by LaurentMazare** [comment]
Right, quantized inference on the GPU is not supported at the moment but we're certainly planning on adding it so nothing wrong with your setup.

**Comment by danielclough** [comment]
## Related open issues
Support for quantisation: https://github.com/huggingface/candle/issues/359
CUDA support for QMatMul: https://github.com/huggingface/candle/issues/655
You are here: https://github.com/huggingface/candle/issues/696
Quantized models on Cuda: https://github.com/huggingface/candle/issues/1250

**Comment by LaurentMazare** [comment]
Closing this now in favor of more recent issues, e.g. #1250 (and #1754 should bring some preliminary support for quantized models on cuda).
