### ISSUE TITLE
unrecognized feature for crate candle-core: cuda

### ISSUE THREAD

**Issue by jremb** [huggingface/candle#698]
Your README file says to install via the following command:

`cargo add --git https://github.com/huggingface/candle.git candle-core --features "cuda"`

Running this command via cargo results in the following error:

```
error: unrecognized feature for crate candle-core: cuda
no features available for crate candle-core
```

**Comment by aegroto** [comment]
Try to clean Cargo.toml and execute this command again, that error randomly came out to me but then disappeared on a second attempt. As an alternative, add this dependency:

```
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.2.0", features = ["cuda"] }
```

**Comment by RileySeaburg** [comment]
> Try to clean Cargo.toml and execute this command again, that error randomly came out to me but then disappeared on a second attempt. As an alternative, add this dependency:
> 
> ```
> candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.2.0", features = ["cuda"] }
> ```

This is an interesting fix to an interesting error. 

I'm wondering why this isn't just a crate with a beta flag.

**Comment by jremb** [comment]
Running `cargo clean` resolved issue. But now a different issue compiling. I'll open a different issue.
