### ISSUE TITLE
Run model tiny failed with index-select invalid

### ISSUE THREAD

**Issue by simon-fu** [huggingface/candle#703]
cargo run --release --example whisper -- --input /tmp/Downloads/samples_jfk.wav --model tiny

pcm data loaded 176000
loaded mel: [1, 80, 3000]
Error: index-select invalid index 50259 with dim size 384

Apple M2 Pro 
MacOS 13.4.1 
rustc 1.71.1

**Comment by Narsil** [comment]
I just reproduced indeed.

**Comment by LaurentMazare** [comment]
Hopefully I just merged some fix for this, so please give a spin to the latest version and thanks for reporting the issue. Not sure when this started to be an issue, we have to put together some end to end testing so that we catch this earlier in the future.

**Comment by LaurentMazare** [comment]
Cool, closing this, feel free to re-open if needed.
