### ISSUE TITLE
Flash Attention Error: unexpected dtype, expected: F16, got: BF16

### ISSUE THREAD

**Issue by AnubhabB** [huggingface/candle#721]
Trying to call `candle_core::flash_attn` with `Dtype::BF16` tensors error out with `unexpected dtype, expected: F16, got: BF16`.

### OS
Ubuntu 22.04

### GPU
RTX 4090 (Ada Lovelace architecture which is supported by Flash Attention 2 for bf16 datatype)

### `nvcc --version`
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jun_13_19:16:58_PDT_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0
```

### Compute capability
`nvidia-smi --query-gpu=compute_cap --format=csv`
```
compute_cap
8.9
```

### Reproduction
```
fn test_flash_attn() {
        let dev = &Device::new_cuda(0).unwrap();
        let xq = Tensor::rand(0., 1., (1, 6, 40, 128), dev).unwrap().to_dtype(candle_core::DType::BF16).unwrap();
        let xk = Tensor::rand(0., 1., (1, 6, 40, 128), dev).unwrap().to_dtype(candle_core::DType::BF16).unwrap();
        let xv = Tensor::rand(0., 1., (1, 6, 40, 128), dev).unwrap().to_dtype(candle_core::DType::BF16).unwrap();

        let a = flash_attn(&xq, &xk, &xv, 1./128_f32.sqrt(), true).unwrap();

        println!("{a}");
}
```
#### Output
```
called `Result::unwrap()` on an `Err` value: UnexpectedDType { msg: "unexpected dtype", expected: F16, got: BF16 }
```

Converting the tensors to `DType::F16` goes through.

Am I missing something?

**Comment by LaurentMazare** [comment]
We've disabled the bf16 support in flash-attn as it takes twice longer to compile the kernels which is already taking a long long time. Maybe we should just re-enable it and put it behind a feature gate.

**Comment by LaurentMazare** [comment]
Just to mention that the latest github version should support flash-attn with bf16, feel free to give it a spin when you have a chance and let us know how it gets.

**Comment by AnubhabB** [comment]
It works.
Kudos to the pace and the effort.

Closing this.
