### ISSUE TITLE
Question around the tracing vs. typical python-based frameworks

### ISSUE THREAD

**Issue by blefaudeux** [huggingface/candle#750]
Hey there, congrats on the candle project to begin with, really nice. I've a quick question around the tracing support (which is a really nice surprise), coming from a python (pytorch) backend. I couldn't find the related doc, sorry about that. 

In the python world, one typically traces CPU and GPU independently, since the CPU thread runs in front and async vs. the CUDA queue. It doesn't seem to be the case here (screen attached on stable diffusion), which made me wonder whether:
- the same model (CPU running in front, everything async) was used by Candle
- the trace was with respect to the GPU time span (looks like it) or the CPU

Sidenote in that it looks like stable diffusion is spending a lot of time outside of the actual diffusion, but I'm planning to have a look, would love to PR :) Curious about pointers/recommendations though.

Thanks

![Screenshot from 2023-09-05 23-02-18](https://github.com/huggingface/candle/assets/3072861/984249a5-7d7b-44b6-a73a-e95b0db195fe)

**Comment by LaurentMazare** [comment]
Hey, thanks for the kind words on candle!
Re tracing, we only provide 'cpu tracing' at the moment as you've noticed. For gpu tracing,
- You can set `CUDA_LAUNCH_BLOCKING` to get a better sense of how long gpu ops take but that's not very representative of the overall performance.
- You can also use tools such as [nvidia nsight](https://docs.nvidia.com/nsight-compute/ProfilingGuide/index.html) so as to see what actually runs on the gpu.

If you have thoughts on how we could improve the tracing experience, they would be very welcome.
When it comes to stable diffusion, you've probably already done so but you should ensure to use cudnn and flash-attn for best performance with something like:
```
cargo run --example stable-diffusion --release --features cuda,cudn,flash-attn -- --use-flash-attn ...
```
flash-attn is pretty slow to build so you may want to set the `CANDLE_FLASH_ATTN_BUILD_DIR` environment variable to cache the build artifacts.
And if you don't use flash-attn, note that the performance of stable diffusion should have improved a lot yesterday with #747 (it's still pretty early days so likely we have a bunch of low hanging fruits to optimize like this).
