### ISSUE TITLE
when i run "cargo run --example mnist-training"

### ISSUE THREAD

**Issue by nihaoqingtuan** [huggingface/candle#755]
**_Error: Api error: request error: https://huggingface.co/datasets/mnist/resolve/refs%2Fconvert%2Fparquet/mnist/test/0000.parquet: Network Error: timed out reading response_**

**Comment by LaurentMazare** [comment]
I just tested the link and it works fine so my guess is that it's more a problem of internet connection than an actual candle issue.

**Comment by npuichigo** [comment]
@LaurentMazare same issue here and the code just ignore my network proxy, since I could just `wget` and download the file.
