### ISSUE TITLE
Benchmarking Speedups on M1 Max System

### ISSUE THREAD

**Issue by okpatil4u** [huggingface/candle#756]
Hello @LaurentMazare, [here](https://github.com/wynum/candle_llama) is our implementation of llama.c as promised. We have implemented cosine annealing scheduler for reducing the learning rate. Thanks for all your support.

These are my observations after running a few benchmarks on my M1 Max 64 GB System.
1. With accelerate enabled, `cargo build; time target/release/candle_llama` took following amount of execution time.
`target/release/candle_llama  147.06s user 33.57s system 114% cpu 2:37.83 total`
This was the memory and CPU consumption.
<img width="1606" alt="Screenshot 2023-09-06 at 4 33 28 PM" src="https://github.com/huggingface/candle/assets/3041904/23d5460a-230f-423f-8930-eca783555b31">

2. With accelerate disabled, `cargo build; time target/release/candle_llama` took following amount of execution time.
`target/release/candle_llama  147.58s user 33.39s system 114% cpu 2:37.69 total`
This was the memory and CPU consumption.
<img width="1609" alt="Screenshot 2023-09-06 at 4 37 03 PM" src="https://github.com/huggingface/candle/assets/3041904/34a7684f-ae3c-4a4b-ac92-d87e50895201">

3. With accelerate disabled and 'export RAYON_NUM_THREADS=8'
`target/release/candle_llama  144.97s user 29.85s system 111% cpu 2:37.10 total`
This was the memory and CPU consumption
<img width="1616" alt="Screenshot 2023-09-06 at 4 41 11 PM" src="https://github.com/huggingface/candle/assets/3041904/a77d4a2c-6c93-41c5-b749-b459e86637f0">

It seems that neither multi threading, nor enabling the accelerate is speeding up the training. Are we doing anything wrong ? Could you please check our code repository and let me know what may be the issue ?

**Comment by okpatil4u** [comment]
That makes sense. But increasing number of rayon threads should improve CPU
utilisation. I am not seeing that happening. What’s the correct way to
configure them ?

I am using export RAYON_NUM_THREADS=8

Is this correct ?

**Comment by LaurentMazare** [comment]
`RAYON_NUM_THREADS` should indeed control the level of threading, though not when using accelerate. You can try setting it to 1, and you should see only a single core being used.

**Comment by okpatil4u** [comment]
Just a followup note, stable-diffusion example does run with 500-700% cpu utilization when number of rayon cores is 8.

**Comment by LaurentMazare** [comment]
That doesn't strike me as very surprising, mnist only involves a small amount of computation so the threading overhead is likely to be worse and the speedup are less than linear whereas stable-diffusion is a much larger model so more likely to have (almost) linear speedups.

**Comment by okpatil4u** [comment]
Do you think that this low CPU utilization has something to do with my naive batch data loader ?

https://github.com/wynum/candle_llama/blob/master/src/main.rs#L558
https://github.com/wynum/candle_llama/blob/master/src/main.rs#L56C1-L72C1

**Comment by okpatil4u** [comment]
Seems like llama2.c example has good cpu utilization. I will try it out.

**Comment by okpatil4u** [comment]
> `RAYON_NUM_THREADS` should indeed control the level of threading, though not when using accelerate. You can try setting it to 1, and you should see only a single core being used.

Do you mean that accelerate cannot work on multiple cores ?

**Comment by LaurentMazare** [comment]
I think it should work on multiple cores by default (at least for some functions like the matmul) but don't know how to control it.

**Comment by okpatil4u** [comment]
Okay. It seems that accelerate wasn’t enabled by default. I was able to
reduce time for each iteration by 40% after enabling accelerate. Thanks for
your help.
