### ISSUE TITLE
LoRA implementation?

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#774]
Hello all,

I was looking through the docs for Candle and noticed that there is a Llama example.

However, I want to fine-tune the 70b model. In Python, I currently use Peft and bitsandbytes. Is there an implementation of LoRA or something similar to Peft yet? What about quantization like bitsandbytes?

Thanks!

**Comment by LaurentMazare** [comment]
I haven't seen any equivalent to LoRA/Peft at the moment, would be great if you want to take a stab at it though!
Re quantization, we do support it in a similar way as ggml does, there is a dedicated [quantized llama example](https://github.com/huggingface/candle/tree/main/candle-examples/examples/quantized), and you can see how to create quantized weights in the [tensor-tools command line](https://github.com/huggingface/candle/blob/c1453f00b11c9dd12c5aa81fb4355ce47d22d477/candle-core/examples/tensor-tools.rs#L13), there is certainly more to be built on this side too!

**Comment by EricLBuehler** [comment]
Ok, I will look into the implementation of LoRA (just for fun for now ;) ). Regarding the quantization example, I saw that but could not tell what bit-width it would be quantized to. Ideally, 4bit for inference. Is there a parameter I can set?

**Comment by LaurentMazare** [comment]
In the command line tool, you should be able to actually pick the quantization via the `--quantization` flag, see [here](https://github.com/huggingface/candle/blob/c1453f00b11c9dd12c5aa81fb4355ce47d22d477/candle-core/examples/tensor-tools.rs#L233).

**Comment by EricLBuehler** [comment]
Thanks!

**Comment by EricLBuehler** [comment]
See mine (in development as of writing):
https://github.com/EricLBuehler/candle-lora
