### ISSUE TITLE
Thoughts on adding .weight, .bias methods to Conv*?

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#806]
I noticed that `Conv1d` and `2d` both do not have weight and bias methods to extract the inner tensors, unlike `Embedding` or `Linear`. I am implementing [LoRA](https://github.com/EricLBuehler/candle-lora), and it would be helpful to not need to wrap the `Conv` layer with the weights and biases. 

Is there a reason these methods were left out? 
Thanks!

**Comment by EricLBuehler** [comment]
Note: This problem also occurs in `Embeddings`, where there is no way to get the `hidden_size`.

**Comment by LaurentMazare** [comment]
You can probably get the `hidden_size` for `Embeddings` by looking at the shape of the embeddings tensor.
No good reason for not exposing the weights, for `Conv1d` and `Conv2d`, feel free to make a PR for it (otherwise I'll add them at some point).

**Comment by EricLBuehler** [comment]
Sure, I will submit a PR.
