### ISSUE TITLE
rustdoc of hub.md fails on windows

### ISSUE THREAD

**Issue by Ssslakter** [huggingface/candle#818]
Hi! I'm going deeper into simple documentation tests and I seem actually liked investigating it

The initial problem was when I tried to run `mdbook test` on the candle-book crate.
So the problem boiled down to running 
```cmd
cd candle-book
cargo build
rustdoc .\src\inference\hub.md --test -L ..\target\debug\deps\
```
Then we got the linker error
```
Couldn't compile the test.
---- .\src\inference\hub.md - Using_the_hub::Using_in_a_real_model_ (line 50) stdout ----

error: linking with `link.exe` failed: exit code: 1181
//very long chain of linking
 = note: LINK : fatal error LNK1181: cannot open input file 'windows.0.48.5.lib'

---- .\src\inference\hub.md - Using_the_hub (line 12) stdout ----                
       
error: linking with `link.exe` failed: exit code: 1181 
//very long chain of linking
 = note: LINK : fatal error LNK1181: cannot open input file 'windows.0.48.5.lib'
```
The strange thing is that the code in the test is actually compiles and runs outside of doc tests.

The toolcahain is
* stable-x86_64-pc-windows-msvc (default) 
* rustc 1.72.0 (5680fa18f 2023-08-23)

**Comment by LaurentMazare** [comment]
Just to mention that these commands worked well on my linux box (though with `cd cargo-book` -> `cd candle-book`) so pretty tricky to reproduce the issue here I'm afraid as I don't have access to a windows box.

**Comment by Ssslakter** [comment]
It took took me couple days to figure out how the linking works, so basically some of the native libraries are located in different directories, so you have to pass them as an argument for linker as well.
This command should now correctly run tests for the docs on windows with msvc toolchain:
```cmd
mdbook test -L ..\target\debug\deps\ -L native= %USERPROFILE%\.cargo\registry\src\index.crates.io- 
\n6f17d22bba15001f\windows_x86_64_msvc-0.42.2\lib -L native= %USERPROFILE%\.cargo\registry\src
\index.crates.io-6f17d22bba15001f\windows_x86_64_msvc-0.48.5\lib
```

**Comment by LaurentMazare** [comment]
Wow that must have been a pain to dig out. Maybe you could add an entry to the [Common Errors](https://github.com/huggingface/candle#common-errors) section of the readme in case anyone else also runs into this?

**Comment by Ssslakter** [comment]
Sounds good, sure
