### ISSUE TITLE
the crate `candle-core@https://github.com/huggingface/candle.git` could not be found at `https://github.com/huggingface/candle.git`

### ISSUE THREAD

**Issue by radicelle** [huggingface/candle#845]
Crate seems not accessible anymore.
I am using windows
Tried with RustRover
Tried with NuShell

**Comment by EricLBuehler** [comment]
Can you give a minimum reproducible example? Is this in your Cargo.toml?

**Comment by radicelle** [comment]
Using RustRover
Create a new project test1
![image](https://github.com/huggingface/candle/assets/75542740/5166a3f7-023f-4af9-9ed6-71d33177fb61)
in the project: cargo add --git https://github.com/huggingface/candle.git candle-core

Fails with error: the crate candle-core@https://github.com/huggingface/candle.git could not be found at https://github.com/huggingface/candle.git

**Comment by radicelle** [comment]
Yes, often time Windows is not very collaborative with developer experience...

**Comment by LaurentMazare** [comment]
Closing as no recent updates.
