### ISSUE TITLE
Consider Linux Foundation for hosting

### ISSUE THREAD

**Issue by marvin-hansen** [huggingface/candle#850]
The Linux Foundation (LF) has a strategic focus on open innovation in artificial intelligence and I suggest hosting your project with the LF. 

https://lfaidata.foundation/all-projects/hosting

My humble crate [DeepCausality](https://deepcausality.com/) was recently accepted into the LF (press release is scheduled for next week) and my experience with LF is simply amazing.

**Comment by Narsil** [comment]
Nice ! 

We have no such plans at the moment but good to know !

**Comment by marvin-hansen** [comment]
Please keep an eye on it when the time is due because my experience with
the foundation is beyond amazing and I highly recommend it especially if
you seek outside contributors and a vendor neutral ground that keeps
everything focused on the project.

Anyway, thank you for your great work.
