### ISSUE TITLE
index using tensor or non-consecutive indices

### ISSUE THREAD

**Issue by GeauxEric** [huggingface/candle#855]
Current indexing scheme seems to only support scalar, range (which is consecutive), or their combinations. 
There is often a need to index a certain dimension by explicit non-consecutive indices or even directly using tensor (which is [supported by pytorch](https://pytorch.org/cppdocs/notes/tensor_indexing.html))

```
#[cfg(test)]
mod tests {
    use candle_core::{Device, IndexOp};


    #[test]
    fn index() -> anyhow::Result<()> {
        let dev = Device::Cpu;
        let tensor = candle_core::Tensor::arange(0u32, 2 * 5, &dev)?.reshape((2, 5))?;
       // col 2 for the 1st row, and col 4 for 2nd row
        let i = tensor.i((..2, [2usize, 4]))?;
        Ok(())
    }
}
```

In the current version of candle, I wonder if there is any work around to achieve this. Any plan to support in the roadmap?

**Comment by GeauxEric** [comment]
I just found out 
```
    /// Indexing via a 1d tensor
    IndexSelect(Tensor),
```
it is not in the 0.2.1 release yet. Let me try it out.

**Comment by LaurentMazare** [comment]
Right this was added yesterday actually, I have to say that I find indexing with a multi-dimensional tensor very confusing (at least with the pytorch semantics) hence the limitation. The example you gave should work well with this though.

**Comment by GeauxEric** [comment]
Just found out `pub fn gather<D: Dim>(&self, indexes: &Self, dim: D) -> Result<Self>` which can do the work.

**Comment by LaurentMazare** [comment]
Yes, `gather` is a bit different and allows you to do indexing using a multi-dimensional tensor (and should have the same semantics as the [PyTorch version](https://pytorch.org/docs/stable/generated/torch.gather.html)).

**Comment by kikijiki** [comment]
@LaurentMazare Could you explain me how can I replicate this pytorch code?

```py
# x.shape = [batch_size, n_ctx, dims]
# text.shape = [batch_size, n_ctx]
# text_projection.shape = [dims, dims]
# take features from the eot embedding (eot_token is the highest number in each sequence)
x = x[torch.arange(x.shape[0]), text.argmax(dim=-1)] @ text_projection
```

What I tried is:

```rust
let argmax = text.argmax(D::Minus1)?; // [2]
let x = x.gather(&argmax, 1)?; // [2, 2, 768]
```

When I try to use `gather()` I get an output tensor of shape `[2,2,768]`, while the `x[torch.arange(x.shape[0]), text.argmax(dim=-1)]` operation produces a tensor of shape `[2,768]`.

**Comment by LaurentMazare** [comment]
I'm not sure what the semantics of indexing a tensor with multiple other tensors are in pytorch, so it's unclear to me what `x[torch.arange(x.shape[0]), text.argmax(dim=-1)]` is actually doing. Maybe you could explain what you would expect this to do and we can try to do the same thing with candle ops?

**Comment by kikijiki** [comment]
It was taken directly from the OpenAI CLIP implementation here https://github.com/openai/CLIP/blob/a1d071733d7111c9c014f024669f959182114e33/clip/model.py#L354

Each batch item has 77 tokens each with its 768 dimensional embedding. This step is supposed just leave the embedding for the biggest (EOT) token for each batch item, going from `[batch_size, n_ctx, dims]` to `[batch_size, 1, dims]`, or `[batch_size, dims]`. The index of the EOT token can be different for each batch item though, so it has to come from argmax.

**Comment by LaurentMazare** [comment]
You can try along the lines of the python snippet below:
```python
import candle
t = candle.tensor(
 [[[-0.6257, -2.0103, -0.0145],
  [ 0.7390, -3.5205,  0.5833],
  [-0.1699,  0.2690,  0.3833],
  [ 0.7064, -0.8789,  1.3285]],
 [[-1.0139,  0.9933,  1.4314],
  [-1.1443, -0.0604,  0.2624],
  [-0.2376,  2.1882, -1.2499],
  [-0.8305,  0.4660,  0.9780]]])
text = candle.tensor([[1, 2, 0, 5], [1, 0, 2, 2]])
am = text.argmax_keepdim(-1).unsqueeze(2).broadcast_as(2, 1, 3)
print(t.gather(am.contiguous(), 1))
```
So you do the argmax which creates a tensor of shape `(b_size, 1)`, then broadcast it to `(b_size, 1, dims)` and then do a gather on it which should return the values at the select indexes. The results seems identical to your pytorch snippet.

**Comment by kikijiki** [comment]
Thank you, that worked!
