### ISSUE TITLE
Missing symbols when compiling SAM example with the mkl feature

### ISSUE THREAD

**Issue by SineYuan** [huggingface/candle#857]
Hi,  when i trying to compiling SAM example with mlk feature

```
cargo build --features mkl --example segment-anything --release
```

i got error below

```
....
  = note: /usr/bin/ld: /data/learnzone/candle/target/release/deps/libcandle_core-26a9bb9108cc0fc3.rlib(candle_core-26a9bb9108cc0fc3.candle_core.aa949fb36abd088b-cgu.00.rcgu.o): in function `<candle_core::cpu_backend::CpuStorage as candle_core::backend::BackendStorage>::matmul':
          candle_core.aa949fb36abd088b-cgu.00:(.text._ZN93_$LT$candle_core..cpu_backend..CpuStorage$u20$as$u20$candle_core..backend..BackendStorage$GT$6matmul17ha4095c0205bb8a69E+0x2818): undefined reference to `hgemm_'
          collect2: error: ld returned 1 exit status
...
```

By reading the Readme,  i notice that crate `intel_mkl_src` already included.

same error occur even i uncomment the feature cfg
```
//#[cfg(feature = "mkl")]
extern crate intel_mkl_src;
```
can you guys build sam example with mkl ?

BTW, thanks for the great works!

**Comment by LaurentMazare** [comment]
I would suspect this is because `intel_mkl_src` installs its own version of the mkl when it's not already available and this version is out of date.
Could you install a recent version of mkl on your system and see if this is still an issue?
(also I would expect the issue to happen with any mkl example)

**Comment by SineYuan** [comment]
you're right,  I try install latest mkl on system and then build success !  

thank a lot
