### ISSUE TITLE
Candle's (MKL) inferencing is slow compared to llama2.c's (Openmp)

### ISSUE THREAD

**Issue by akhildevelops** [huggingface/candle#881]
I like candle library and thinking of using it in my ML workflows. But I need to rethink, after comparing the candle inference speeds  against llama2.c by kaparthy. Below are the token generation speed for both llama2.c and candle's llama2.c implementation present in candle-examples folder.

### For stories15M.bin
|Library|command|token generation speed|Features|
|---|---|---|---|
|llama2.c|`gcc -Ofast -fopenmp -o run -march=native run.c -lm && OMP_NUM_THREADS=10 ./run stories15M.bin`|401.41|Openmp (CPU)|
|llama2.c|`gcc -O3 -fopenmp -o run -march=native run.c -lm && OMP_NUM_THREADS=10 ./run stories15M.bin`|332.67|Openmp without fastmath (CPU)|
|candle|`cargo run --example llama2-c --features mkl --profile release-one`|293.04|MKL feature (CPU)|
|candle|`cargo run --example llama2-c --features cuda --profile release-one`|290.67|Cuda feature (GPU)|
|llama2.c|`gcc -Ofast -o run run.c -lm && ./run stories15M.bin`|210.05|[Ofast optimization](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-Ofast) (CPU)|
|candle|`cargo run --example llama2-c --profile release-one`|200.23|None (CPU)|
|llama2.c|`gcc -O3 -o run run.c -lm && ./run stories15M.bin`|72.264|[O3 optimization](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-O3) (CPU)|

## For stories42M.bin
|Library|command|token generation speed|Features|
|---|---|---|---|
|candle|`cargo run --example llama2-c --features cuda --profile release-one -- inference --which-model stories42M.bin`|185.31|Cuda feature (GPU)|
|llama2.c|`gcc -Ofast -fopenmp -o run -march=native run.c -lm && OMP_NUM_THREADS=10 ./run stories42M.bin`|147.6|Openmp (CPU)|
|llama2.c|`gcc -O3 -fopenmp -o run -march=native run.c -lm && OMP_NUM_THREADS=10 ./run stories42M.bin`|133.96|Openmp without fastmath (CPU)|
|llama2.c|`gcc -Ofast -o run run.c -lm && ./run stories42M.bin`|75.15|[Ofast optimization](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-Ofast) (CPU)|
|candle|`cargo run --example llama2-c --features mkl --profile release-one -- inference --which-model stories42M.bin`|72.84|MKL feature (CPU)|
|candle|`cargo run --example llama2-c --profile release-one -- inference --which-model stories42M.bin`|55.93|None (CPU)|
|llama2.c|`gcc -O3 -o run run.c -lm && ./run stories42M.bin`|24.33|[O3 optimization](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-O3) (CPU)|

### release-one profile in Cargo.toml
```toml
[profile.release-one]
inherits="release"
lto = true
panic = 'abort'
```

Leaving out the GPU, llama2.c (openmp) is excelling in CPU only inferencing compared to candle's MKL feature. I've even tried to set MKL_NUM_THREADS=10 / OMP_NUM_THREADS=10 while running candle (as mkl uses openmp internally) still the results of candle (MKL feature) are same.

**Comment by passchaos** [comment]
This should be caused by the gcc's -Ofast option,  rust does't have fast-math support, you can test the performance data of llama2.c after -Ofast is disabled but openmp is enabled.

**Comment by akhildevelops** [comment]
I've updated the table, disabled fastmath and ran it at O3 optimization, still it tops candle.

**Comment by akhildevelops** [comment]
> From the point of view of the parameters, the gcc version also has native cpu architecture choice, perhaps you can try to use the environment variable `RUSTFLAGS="-Ctarget-cpu=native"` to enable rust's native architecture support

Already tried targeting to native but there's no difference with or without `-C target-cpu=native` rustflag.

**Comment by katopz** [comment]
Is this better for 2024? This kinda block me to promote candle 🫣

**Comment by akhildevelops** [comment]
I’m closing it Cheers.
