### ISSUE TITLE
Question: How to properly use VarBuilder?

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#883]
Hello everybody,

I am working on implementing LoRA and want to use the VarBuilder system. However, when I try to get a tensor with get_with_hints, I get a CannotFindTensor Err. To create the Tensor, I do:
```rust
vb.pp("a").get_with_hints(
...lora specific shape...
"weight",
...lora specific hints...
)
```
However, this fails with the CannotFindTensor error. How can I create the Tensor, or perhaps am I using the API incorrectly?

Thanks!
Eric

**Comment by LaurentMazare** [comment]
This depends on whether you're trying to run inference for a model where you can create the var builder from for example a safetensor file or whether you want to train a model in which case you want to create a var builder based on a varmap. In this last case, tensors are generated on the flight based on the hints that you provide, you can find some example using this in the [mnist training](https://github.com/huggingface/candle/blob/main/candle-examples/examples/mnist-training/main.rs).

**Comment by EricLBuehler** [comment]
I am trying to add tensors to a VarBuilder loaded from a safetensors file. Could this be the issue? If so, how can I modify the VarBuilder?

**Comment by EricLBuehler** [comment]
It looks like the VarBuilder is created with VarBuilder::from_tensors. How can I add tensors, or do I need to make another VarBuilder?

**Comment by LaurentMazare** [comment]
If your goal is to train the tensors loaded from the file, you should still use a varmap based var builder but you can use `load` on the var-map to get the values from the safetensors file ([example here](https://github.com/huggingface/candle/blob/06cc329e715cbb820343f9849a4a45c818cb8c5e/candle-examples/examples/mnist-training/main.rs#L127)).
If you want to have both trainable variables, and tensors that come from a safetensor file, you can either use two var builders or write a custom var builder backend based on the [backend trait](https://github.com/huggingface/candle/blob/7cafca835a4bb9a21f3c8111e2f61b7a6b1270fd/candle-nn/src/var_builder.rs#L46)).

**Comment by EricLBuehler** [comment]
Ok, thank you. In my case using LoRA with inference with the model when it is loaded from a safetensors does not make sense anyway. This also reinforces the immutability of non-trainable models.
