### ISSUE TITLE
How to fine-tune Llama?

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/candle#894]
Hello everybody,

I am trying to fine-tune the Llama model, but cannot load the safetensors file. I have modified the training loop for debugging and development:
```rust
pub fn run(args: &crate::TrainingCmd, common_args: &crate::Args) -> Result<()> {
    let config_path = match &args.config {
        Some(config) => std::path::PathBuf::from(config),
        None => {
            let api = hf_hub::api::sync::Api::new().unwrap();
            println!("loading the model weights from {}", args.model_id);
            let api = api.model(args.model_id.clone());
            api.get(&args.which_model).unwrap()
        }
    };


    let device = candle_examples::device(common_args.cpu)?;
    let config = Config::tiny();
    
    let mut varmap = candle_nn::VarMap::new();
    let vb = candle_nn::VarBuilder::from_varmap(&varmap, DType::F32, &device);
    varmap.load(config_path).unwrap();

    /*let cache = Cache::new(false, &config, vb.pp("rot"))?;
    let model = Llama::load(vb, &cache, config, true)?;

    let params = candle_nn::ParamsAdamW {
        lr: args.learning_rate,
        ..Default::default()
    };
    let mut opt = candle_nn::AdamW::new(varmap.all_vars(), params)?;
    for (batch_index, batch) in batch_iter.enumerate() {
        let (inp, tgt) = batch?;
        let logits = model.forward(&inp, 0)?;
        let loss = candle_nn::loss::cross_entropy(&logits.flatten_to(1)?, &tgt.flatten_to(1)?)?;
        opt.backward_step(&loss)?;

        if batch_index > 0 && batch_index % 1000 == 0 {
            varmap.save("checkpoint.safetensors")?
        }
    }*/
    Ok(())
}
```

I realize this error is likely because I cannot use VarMap::load to load such a large safetensors file (as described [here](https://github.com/huggingface/safetensors/blob/main/README.md#benefits)). However, how can I use VarMap (or something else that allows me to modifiy the tensor map) to load the weights? If there is not such a method, how should I implement this myself?

Thank you!
Eric

**Comment by EricLBuehler** [comment]
Would something like a new `VarMap::from_tensors` be a viable option?

**Comment by LaurentMazare** [comment]
What is the error message that you got?
Note that you should call `load` _after_ creating the model with the varmap and not before. Calling `load` will copy the safetensors data in the tensors that were created during the model initialization (so I would refrain from adding a `from_tensors` bit here as it wouldn't make much sense). See how it's done in the [mnist-example](https://github.com/huggingface/candle/blob/92db8cecd32df9f9a338b89160d3072586595e96/candle-examples/examples/mnist-training/main.rs#L123).

I'll try to find some time today to add some documentation around this, most likely by adding comments/tutorials to the [llama2-c training](https://github.com/huggingface/candle/blob/main/candle-examples/examples/llama2-c/training.rs), this doesn't support loading the model yet but it should be a couple line change.

**Comment by EricLBuehler** [comment]
I got the SafeTensor HeaderTooLarge error. I was calling load after creating the model with the varmap as in the mnist example. When I looked at the Llama example, I realized that it does not call load and instead uses a special method that loads the VarBuilder from tensors. I need a varmap to be the backend for the VarBuilder (for mutability), so that is why I submitted the PR.

**Comment by LaurentMazare** [comment]
Would you mind making a minimal repro for the error? I feel that we should look at the underlying cause rather than tweaking the var-map. For now one of its invariant is that it only holds variables and not non-trainable tensors so it's easy to plug it in optimizers and the new `from_tensors` function would break this invariant.

**Comment by LaurentMazare** [comment]
Let's have a look at the original error first and if there is no better workaround we'll go for something like you suggested but again would prefer keeping the api as simple as possible for `VarMap` as it's already pretty tricky to understand.

**Comment by EricLBuehler** [comment]
@Narsil, thank you for the idea! I tried that multiple times, making sure it was redownloading the file, but the error did not change. Here is the error:
```
"/home/ericbuehler/.cache/huggingface/hub/models--karpathy--tinyllamas/snapshots/0bd21da7698eaf29a0d7de3992de8a46ef624add/stories15M.bin"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WithPath { inner: SafeTensor(HeaderTooLarge), path: "/home/ericbuehler/.cache/huggingface/hub/models--karpathy--tinyllamas/snapshots/0bd21da7698eaf29a0d7de3992de8a46ef624add/stories15M.bin" }', examples/llama/training.rs:49:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I am able to run the normal Llama inference example, so memory is not an issue. I noticed the inference example uses `TransformerWeights::var_builder` to load the varbuilder, so I wanted to add `VarMap::from_tensors` to allow mutability of the map (I want to test candle-lora). 

@LaurentMazare, [here](https://github.com/EricLBuehler/candle-lora/tree/min_repro) is a min-repro repo. To see the error, please `cargo run --example llama -- train` after a clone.

**Comment by LaurentMazare** [comment]
Thanks for the repro. Looking at the error message you give, it could be that the input file is not in the safetensors format: thes files are likely to end with `.safetensors`, whereas `stories15M.bin` is most likely using Karphaty's custom binary format.

**Comment by EricLBuehler** [comment]
Right - this is likely why there is a custom loader in the inference example.

Based on this (and the fact I need mutability of the VarBuilder), what are your thoughts on the necessity of the `VarMap::from_tensors` method - or is there another way to get this sort of mutability?

**Comment by LaurentMazare** [comment]
The easiest would probably be to convert the `.bin` file to `.safetensors` and use a safetensors file, these have other advantages.

Besides this, I think you could just mimick the behavior of `load` once you've created the model based on the `VarMap` by doing something like.
```rust
let model = build_model(vb);
let data = var_map.data().lock().unwrap();
for (key, var) in data.iter() {
    let init_value = // get the tensor value that you're interested in based on its name
    var.set(&init_value)?
}
```
The current api should expose the necessary functions. Would that work for you?

We could think about supporting more file formats in `VarMap::load` but sounds better to provide hooks so that users can do arbitrary manipulations here.

**Comment by EricLBuehler** [comment]
True, that would work - thanks!

Regarding `VarMap::load`, it would likely be hard to support loading .bin files unless they have some sort of type header.

**Comment by LaurentMazare** [comment]
> Regarding `VarMap::load`, it would likely be hard to support loading .bin files unless they have some sort of type header.

Right, either we would need some optional argument for the format. In tch we try to guess it based on the extension but it ends up being flaky and confusing so probably not the best idea (e.g. everyone uses `.bin` as an extension).

**Comment by EricLBuehler** [comment]
Right.
