### ISSUE TITLE
Add `good-first-issue` tag

### ISSUE THREAD

**Issue by julien-blanchon** [huggingface/candle#916]
Hey, I'm willing to contribute here.

I'm not very familiar with rust and I prefer to start easy in order to understand the current codebase, could some maintainers tag some easy issue with a `good-first-issue` tag so newbie can figure out what may be easy.

**Comment by LaurentMazare** [comment]
Hey, I don't think we have much such issues yet as the project is very much in flux but we'll try adding some.
At the moment, the best way to both contribute and to get used to this library is to build models using it, or to write external material (tutorials, blog posts etc).
So I would suggest finding a model/application that you care about and writing a candle version of it, this is usually pretty easy if the original model is in PyTorch though candle still has some rough edges (please report if you find anything missing), for example you can see a text search in an image database using candle [here](https://github.com/flaribbit/imgfind).
And if you get anything out that works well, we're pretty happy to add a link to it from the "external resources" section of the readme.
