### ISSUE TITLE
falcon example error on m1 macbook pro

### ISSUE THREAD

**Issue by YUFAN2GA** [huggingface/candle#920]
# run output
```bash
cargo run --example falcon   --release -- --prompt "how to learn css quickly"
    Finished release [optimized] target(s) in 0.61s
     Running `target/release/examples/falcon --prompt 'how to learn css quickly'`
Running on CPU, to run on GPU, build this example with `--features cuda`
retrieved the files in 1.320542ms
loaded the model in 35.508071542s
starting the inference loop
Error: unsupported dtype BF16 for op matmul
```

# code version
git version 
commit 871efc0307e39441236327643abb397b3ab200d0 (HEAD -> main, origin/main, origin/HEAD)

# os info
sys info as below:
  model：	MacBook Pro
  model id：	MacBookPro17,1
  type：	MYD92CH/A
  cpu：	Apple M1
  kernels：	8
  memory：	8 GB
  firmware：	8422.141.2
  bios：	8422.141.2

# toolchain info
> rust toolchain info:
> rustup show -v
> Default host: aarch64-apple-darwin
> 
> installed targets for active toolchain
> 
> aarch64-apple-darwin
> wasm32-unknown-unknown
> 
> active toolchain
> 
> stable-aarch64-apple-darwin (default)
> rustc 1.70.0 (90c541806 2023-05-31)

**Comment by LaurentMazare** [comment]
Yes that's sadly expected. There is no good cpu support for bf16 at the moment so the falcon model that uses it has to run on a gpu through cuda.

**Comment by Narsil** [comment]
There also must be GGML versions that work and adapting the `quantized` example would be a good approach I think

**Comment by vitali2y** [comment]
The same error on _Linux_ too:
```
➜  ✗ cat /proc/cpuinfo | grep 'cpu cores' | wc -l
12
➜  ✗ cat /proc/meminfo | grep MemTotal
MemTotal:       65570916 kB
➜  ✗ grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Linux Mint 21.2"
➜  ✗
```

**Comment by LaurentMazare** [comment]
Closing stale issues, feel free to open a fresh one if you're still having problems.

**Comment by jpchen** [comment]
Having this issue on M4 Max too, was there ever a resolution/support added?
