### ISSUE TITLE
Clip

### ISSUE THREAD

**Issue by kikijiki** [huggingface/candle#928]

**Comment by LaurentMazare** [comment]
Closing this issue as it doesn't provide any context/content/... Please provide more context and details in a new issue if you want someone to actually have a look.
If you're looking for a clip model in candle, there is actually one as part of stable diffusion that can be found [here](https://github.com/huggingface/candle/blob/main/candle-transformers/src/models/stable_diffusion/clip.rs).

**Comment by kikijiki** [comment]
Sorry I think I created this by mistake 😓

**Comment by marcusinthesky** [comment]
This just seems to be the text model.

**Comment by kikijiki** [comment]
Yeah originally I was looking for something like `CLIPProcessor` and `CLIPModel` that are in the transformers python library.
Doesn't seem to be implemented here.
