### ISSUE TITLE
llama-multiprocess examples requires sync on stream after NCCP call

### ISSUE THREAD

**Issue by gterzian** [huggingface/candle#967]
I'm looking more into this CUDA/NCCL stuff, and I believe the `llama-multiprocess` example should synchronize on the stream used in the `all_reduce` call. 

I believe [this part](https://github.com/huggingface/candle/blob/2dd43d6cdd3242bcbe49a0558e56e24549a866d0/candle-examples/examples/llama_multiprocess/model.rs#L67) should look something like the below:

```rust
self.comm.all_reduce(s, &mut dst, &ReduceOp::Sum).unwrap();
dev.wait_for(&device.stream).unwrap();
```

See the [`cudarc` stream example](https://github.com/coreylowman/cudarc/blob/54f363ab18e14304b10c700aec34b72f11b5d823/examples/04-streams.rs#L32), and the [examples](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/examples.html) in the NCCL docs. 

I'd open a PR myself but I can't compile the example on my Mac(and installing CUDA on mac seems to be a rabbit hole) :)

**Comment by Narsil** [comment]
No there is no need.

the NCCL examples are synchronizing before making a sync free call, which is required to happen AFTER the op has finished, but this is not the case in this example.

Synchronizing is something you want to do *as little as possible*. It's a big performance loss when you have to do it.

**Comment by gterzian** [comment]
Thanks for the info!
