### ISSUE TITLE
An API to check if the application is using apple accelerate or not

### ISSUE THREAD

**Issue by okpatil4u** [huggingface/candle#979]
I think there should be some kind of documentation on accelerate usage and some API code to check whether the compiled executable is using accelerate or not. 

I have been able to enable and compile it on my M1-Max, but my colleagues are having trouble while running on M2-Ultra with 192 GB RAM. Only benchmarks cannot be the way to verify if the application is running on accelerate or not.

Is it possible ?

**Comment by LaurentMazare** [comment]
Actually there is already an api for this: [candle_core::utils::has_accelerate()](https://docs.rs/candle-core/latest/candle_core/utils/fn.has_accelerate.html).

**Comment by okpatil4u** [comment]
Thanks Laurent.
