### ISSUE TITLE
feature request: `ModelWeights` `from_safetensors`

### ISSUE THREAD

**Issue by RatanRSur** [huggingface/candle#981]
Similar to `from_ggml` and `from_gguf`

**Comment by LaurentMazare** [comment]
Could you give more details on how you will want to use this, which model etc?
The main reason to have `from_ggml` and `from_gguf` is for quantized model. For models that are not quantized, we very commonly use some `from_safetensors` instead, e.g. [here](https://github.com/huggingface/candle/blob/03348e2e6f6c1904b4c41504c2fcd5887366c437/candle-examples/examples/phi/main.rs#L220).

**Comment by LaurentMazare** [comment]
Closing this as no recent discussion, feel free to reopen.
