### ISSUE TITLE
[Question] Slow model load and weird result with Mistral

### ISSUE THREAD

**Issue by katopz** [huggingface/candle#993]
## Spec
```
GPU  NVIDIA GeForce RTX 4090 24GB
CPU  13th Gen Intel(R) Core(TM) i7-13700K, 3400 Mhz, 16 Core(s), 24 Logical Processor(s)
RAM  DDR5 32GB BUS 5200 KINGSTON FURY BEAST BLACK
SSD  1TB SAMSUNG 980 PRO (R 7,000MB/s,W 5,000MB/s) M.2 NVMe
OS   Windows 11 WSL Ubuntu 22.04
```
## Command
```
cargo run --example mistral --release --features cuda,cudnn -- --prompt "Write helloworld code in Rust" --weight-files=pytorch_model-00001-of-00002.safetensors,pytorch_model-00002-of-00002.safetensors --tokenizer-file=tokenizer.json
   Compiling cudarc v0.9.14
   Compiling candle-examples v0.2.3 (/mnt/c/Users/katop/git/candle/candle-examples)
   Compiling candle-core v0.2.3 (/mnt/c/Users/katop/git/candle/candle-core)
   Compiling candle-nn v0.2.3 (/mnt/c/Users/katop/git/candle/candle-nn)
   Compiling candle-transformers v0.2.3 (/mnt/c/Users/katop/git/candle/candle-transformers)
   Compiling candle-datasets v0.2.3 (/mnt/c/Users/katop/git/candle/candle-datasets)
    Finished release [optimized] target(s) in 49.13s
     Running `target/release/examples/mistral --prompt 'Write helloworld code in Rust' --weight-files=pytorch_model-00001-of-00002.safetensors,pytorch_model-00002-of-00002.safetensors --tokenizer-file=tokenizer.json`
avx: true, neon: false, simd128: false, f16c: true
temp: 0.00 repeat-penalty: 1.10 repeat-last-n: 64
retrieved the files in 15.854382ms
loaded the model in 357.099360209s
starting the inference loop
Write helloworld code in Rust
=============================

Thisisasimpleexampleofhowtowrite"Hello,world!"programinRust.

##Compileandrun

```bash
$cargobuild--release
 Compilinghello-worldv0.1.0(/home/user/rust/hello-world)
  Finishedrelease[optimized]target(s)in0.26s
$./target/release/hello-world
100 tokens generated (11.67 token/s)
```

## Question
it took `357.099360209s` to load model and got `11.67 token/s`, is this expected?

**Comment by LaurentMazare** [comment]
Ah actually I just pushed some changes that should help with this a couple minutes ago. Could you run a git update and retry?

**Comment by katopz** [comment]
better token/s but still long load model time and seem to cut off result in the end. 🧐

```
cargo run --example mistral --release --features cuda,cudnn -- --prompt "Write helloworld code in Rust" --weight-files=pytorch_model-00001-of-00002.safetensors,pytorch_model-00002-of-00002.safetensors --tokenizer-file=tokenizer.json
   Compiling cudarc v0.9.14
   Compiling candle-examples v0.2.3 (/mnt/c/Users/katop/git/candle/candle-examples)
   Compiling candle-core v0.2.3 (/mnt/c/Users/katop/git/candle/candle-core)
   Compiling candle-nn v0.2.3 (/mnt/c/Users/katop/git/candle/candle-nn)
   Compiling candle-datasets v0.2.3 (/mnt/c/Users/katop/git/candle/candle-datasets)
   Compiling candle-transformers v0.2.3 (/mnt/c/Users/katop/git/candle/candle-transformers)
    Finished release [optimized] target(s) in 46.34s
     Running `target/release/examples/mistral --prompt 'Write helloworld code in Rust' --weight-files=pytorch_model-00001-of-00002.safetensors,pytorch_model-00002-of-00002.safetensors --tokenizer-file=tokenizer.json`
avx: true, neon: false, simd128: false, f16c: true
temp: 0.00 repeat-penalty: 1.10 repeat-last-n: 64
retrieved the files in 18.32907ms
loaded the model in 381.629533085s
starting the inference loop
Generated text:
Write helloworld code in Rust
=============================

This is a simple example of how to write "Hello, world!" program in Rust.

## Compile and run

```bash
$ cargo build --release
   Compiling hello-world v0.1.0 (/home/user/rust/hello-world)
    Finished release [optimized] target(s) in 0.26s
$ ./target/release/hello-world

100 tokens generated (21.44 token/s)
```

I use downloaded file btw `--weight-files=pytorch_model-00001-of-00002.safetensors,pytorch_model-00002-of-00002.safetensors --tokenizer-file=tokenizer.json`

**Comment by LaurentMazare** [comment]
You can control the generated length via the `--sample-len xxx` flag, default is 100 which is a bit small.
Re speed, it's a lot faster on my linux box (~8s), not sure if it's related to windows/your local disk/something else though.

**Comment by katopz** [comment]
`--sample-len 400` did the trick, thx. I think will blame `WSL` in case i have very fast `SSD  1TB SAMSUNG 980 PRO (R 7,000MB/s,W 5,000MB/s) M.2 NVMe` here 🫠

**Comment by LaurentMazare** [comment]
Yeah actually we mmap the weight files to speed up loading but on windows/WSL this may well be counter productive - and your SSD should be a ton faster here. Maybe we should have an option to disable the mmap for windows users as it could be the case that it's a lot faster without.

**Comment by katopz** [comment]
Maybe related here: https://github.com/microsoft/WSL/issues/9555

Did candle support Windows btw? (Asking before wasting my time setup cuda on Windows) 😅.

**Comment by LaurentMazare** [comment]
Well I haven't tried, we do have a windows CI but not sure what it actually uses - the config doesn't mention WSL so maybe it's pure windows - also note that we only have a linux CI for cuda so uncertain about this too :)

**Comment by katopz** [comment]
Now i know what's going on! `/mnt/c/Users/katop/git/candle` [is the problem](https://stackoverflow.com/questions/68972448/why-is-wsl-extremely-slow-when-compared-with-native-windows-npm-yarn-processing).
When i move it to `/home/katopz/candle` now it's ALOT faster.

```
retrieved the files in 1.630166ms
loaded the model in 7.777573557s
```

Awwww, sorry for wasting your time. 🥹

**Comment by LaurentMazare** [comment]
Ah glad that you sorted it out ~8s is a much more reasonable timing. I've added an entry to the [faq](https://github.com/huggingface/candle#extremely-slow-model-load-time-with-wsl) about this so that it's easier to discover, thanks for reporting it along with the underlying problem.
